### ISSUE TITLE
Store all sizes with pgfkeys

### ISSUE THREAD

**Issue by benjamin-weiss** [matze/mtheme#101]
Most of the sizes in the theme are hardcoded right now. There are only the few beamersizes which can be set via `\setbeamersize{•}` and the `frametitleoffset` which can be set as an option. It would be nice to have them all stored as subkeys of `/metropolis/sizes`. Then all the sizes could be set very conveniently by the user with an additional macro `\metrosetsize{•}` .

**Comment by rchurchley** [comment]
If I recall correctly, `frametitleoffset` is a bit of a hack to get text better centred on the frame, right? According to this [StackExchange answer](http://tex.stackexchange.com/questions/247826/beamer-full-vertical-centering), we can fix this more precisely by patching `\beamer@framebottomskip` with no need for manually setting a magic length.

**Comment by benjamin-weiss** [comment]
Yes I think so. I will look into that. Yet there are still a lot of hardcoded sizes in the code. So what do you think about my proposal?

**Comment by rchurchley** [comment]
Can the remaining sizes be set with `setbeamersize`?

**Comment by benjamin-weiss** [comment]
Which remaining sizes do you mean? The ones defined by beamer? AFAIK there are only the following (maybe I missed some?). And most of them are not even used by us. And they can and should still be set with `setbeamersize`. 

- text margin left
- text margin right
- sidebar width left
- sidebar width right
- description width
- description width of
- mini frame size
- miniframe offset

**Comment by rchurchley** [comment]
Oh, I think I misinterpreted your original comment — cancel my last question :) What sizes remain hard coded?

**Comment by benjamin-weiss** [comment]
There are some. So this list is not intended to be exhaustive.

- distances of the elements on the title page
- height of the frame title block
- headline/footline left/rightskip
- progress bar height
- section page minpage width
- dimension of the block elements

**Comment by benjamin-weiss** [comment]
Maybe we can also define our own beamersizes and use `setbeamersize` for that purpose. But after a quick search in the documentation there is no `defbeamersize`.

**Comment by matze** [comment]
IMHO it really boils down if we have to give users the option to customize sizes or provide the "best" possible sizes ourselves remedying any need for customization. Overriding the height of the frame title or dimensions of block elements asks for complex logic to make sure everything still looks alright. If you think this is a non-issue, we can do that but I am a bit sceptical concerning long-term maintenance.

**Comment by benjamin-weiss** [comment]
> Overriding the height of the frame title or dimensions of block elements asks for complex logic.

I don't see it that way. If the user wants to do that, he has to take care of that himself. But it would minimize the effort necessary. If a user wants to adjust the block title height, right now he would have to redefine the three beamer templates `block begin`, `block alerted begin` and `block example begin`. That would be around 75 lines of code. With a key=value based size implementation this could be reduced to something like this.

```TeX
\metrosetsize{
  block title height = 3ex,
  block title depth = 1.25ex,
}
```

But the question is still valid: Do we want the user to be able to make such adjustments.

**Comment by rchurchley** [comment]
I don't think we should worry about these lengths until they come up naturally. If we get the lengths right, the user won't want to change them unless they're doing something that requires them to redefine the template anyways.

**Comment by benjamin-weiss** [comment]
I don't think of it just as a feature for the user. I also think of it as a feature for us developers. Not having any hardcoded values at all is – from my point of view – good coding style. And if we start to define all the sizes via `\newlength{•}`, we can also store them as pgfkeys. But I'm also fine with dropping this feature if you both think it is not necessary.

**Comment by rchurchley** [comment]
I'd be fine with storing the hard coded lengths with `\newlength` as a matter of style. (And I'd definitely be open to solutions that remove the need for "magic lengths".) I just don't think there's yet a strong reason to incorporate them into pgfkeys, which I would prefer reserving for user-facing options.

**Comment by benjamin-weiss** [comment]
Ok, reserving the pgfkeys for user-facing options is fine with me to. So I propose we just get rid of all the hardcoded values as we go along and I close this issue.

**Comment by rchurchley** [comment]
Sure thing.
