### ISSUE TITLE
`beamerthemem.sty' not found.

### ISSUE THREAD

**Issue by digen** [matze/mtheme#102]
Hi there, 
Thanks for the theme. Facing a bit of an issue getting it to build inside a docker container. 

When I run the build.sh, get the following,
```
! LaTeX Error: File `beamerthemem.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name:
```

The file beamerthemem.sty does not exist in the current working directory(repo). Surprisingly, the repo which I had downloaded a few days ago on a different computer has the file. Can anyone point out if I am missing some step ?

**Comment by benjamin-weiss** [comment]
Try to run `make sty` before building the docker container. We converted the theme to the "Documented LaTeX Format", so the `sty` files must be created first.

@eddelbuettel, @awalterschulze I personally do not use docker, so I can't really help fixing the build rules. Can you have a look at the docker build rules again.

**Comment by digen** [comment]
@benjamin-weiss That fixed it. Thanks !

**Comment by awalterschulze** [comment]
I'll take a look at this.

**Comment by eddelbuettel** [comment]
I went the other way and just created a .deb for my own use which puts

- all the font files on in the right place
- ditto for the beamer files
- as well as a small local variant I made for my use.

It is in [this PPA on launchpad](https://launchpad.net/~edd/+archive/ubuntu/misc/+packages).

**Comment by matze** [comment]
#103 should've fixed the problem for our Docker users.
