### ISSUE TITLE
add an installation(manual) for Windows systems running MiKTeX

### ISSUE THREAD

**Issue by StefJar** [matze/mtheme#108]
It would be great to have an installation or least a installation guide for the miktex dist. running on windows.

**Comment by matze** [comment]
This will partially be solved as soon as the theme is up on CTAN. However, an installation guide must be provide from the community, I personally don't run Windows.

**Comment by StefJar** [comment]
if it will be on CTAN all gone be fine. You have any idea when it will happen?

**Comment by matze** [comment]
As soon as all issues concerning milestone tagged 1.0 are resolved.

**Comment by benjamin-weiss** [comment]
@matze This issue here is probably not the right place to discuss this, but I think we should talk about which features we really want in version 1.0, e.g. #11, #53, #65 are imho not must have features for the first CTAN release.

**Comment by ptheywood** [comment]
The new readme since #132 provides sufficient information for window installation in my opinion:
> run LaTeX directly on source/metropolistheme.ins.
> ...
> move the *.sty files to a folder in your TeX path instead.

Although there is potential for increased clarity by splitting the installation instruction to be OS specific or provide separate instructions for installing with / without make.

**Comment by DfAC** [comment]
from command
```
cd ,/source/
line run latex .beamerthememetropolis.ins
```
