### ISSUE TITLE
Allow the possibility of old style figures in text

### ISSUE THREAD

**Issue by apuignav** [matze/mtheme#109]
I would like to use old style figures in text and title, keeping the normal, lining figures in math mode.

I have tried to modify the `beamerfontthememetropolis.dtx` file to achieve so but I've been unable to: essentially, I have tried replacing `fontspec` by `mathspec` and adding `setmathfont` and `setmathsf`, so I have

```
\RequirePackage{mathspec}
\defaultfontfeatures{Mapping=tex-text}
\setsansfont[BoldItalicFont={Fira Sans Italic},%
             ItalicFont={Fira Sans Light Italic},%
             BoldFont={Fira Sans},
             Numbers={OldStyle}]{Fira Sans Light}
\setmonofont{Fira Mono}
\newfontfamily\ExtraLight{Fira Sans ExtraLight}[Numbers={OldStyle}]
\newfontfamily\Light{Fira Sans Light}[Numbers={OldStyle}]
\newfontfamily\Book{Fira Sans}[Numbers={OldStyle}]
\newfontfamily\Medium{Fira Sans Medium}[Numbers={OldStyle}]
\setmathfont[Numbers={Lining, Proportional}]{Fira Sans Medium}
\setmathsf[Numbers={Lining,Proportional}]{Fira Sans Medium}
```

The additions in `newfontfamily` are necessary for titles and so on (it matches much better the small caps, IMO). However, this gives `OldStyle` numbers in math. If I remove the `OldStyle` from `setsansfont`, then regular text doesn't have old style figures.

I would like to do a PR request adding this feature, but I cannot get it to work. Any hints/comments on what may be missing?

**Comment by matze** [comment]
Right now, I cannot really help but if you come up with something, a PR is very welcome. However, that behaviour should be customizable with an appropriate option key.

**Comment by apuignav** [comment]
Thanks! I'll try to do it, maybe some other expert can come up with a hint on how to continue...

**Comment by benjamin-weiss** [comment]
Suppose you have the latest version of metropolis you can do it like that:
```TeX
\documentclass{beamer}
\usetheme{m}
\usefonttheme{professionalfonts} % necessary that mathspec works
\usepackage{mathspec}
\setsansfont[BoldFont={Fira Sans}, Numbers={OldStyle}]{Fira Sans Light}
\setmathsfont(Digits)[Numbers={Lining,Proportional}]{Fira Sans Light}
\begin{document}
\begin{frame}{Numbers}
Normal:
\begin{center}
	+49 175 12\,34\,567 
\end{center}
Math:
\begin{equation}
	25 \cdot 10 = 250
\end{equation}
\end{frame}
\end{document}
``` 
The important part is, that you load the `professionalfonts` beamer theme. Otherwise `mathspec` does not work.

**Comment by matze** [comment]
I checked this and it works fine. For further reference, I added a note in the manual. So without further ado, I'll close this.

**Comment by alcarazr** [comment]
I'm sorry to re-open this issue, but adding the suggestion from the manual (the one proposed by @benjamin-weiss), not only changes the numbers but also the math font. Is it possible to only add the old style figures in text, keeping lining and proportional figures in math, but keeping the same font for all other letters?

Thanks in advance,
Rodrigo
