### ISSUE TITLE
Remove voffset

### ISSUE THREAD

**Issue by rchurchley** [matze/mtheme#111]
Currently, the metropolis outer theme adds space after the frame title (with a package option to remove it) in order to get text better centred on the frame. This hacky solution has several problems, including imprecision and the fact that it doesn't work on slides with no frame title.

Fortunately, this [StackExchange answer](http://tex.stackexchange.com/questions/247826/beamer-full-vertical-centering) has a better solution for this. We can fix the vertical alignment precisely by patching `\beamer@framebottomskip`, presumably in the inner theme, and removing all references to `\metropolis@voffset`.

**Comment by matze** [comment]
Does this require having to specify `[c]` on each frame or could we enforce that on all frames?

**Comment by rchurchley** [comment]
I believe frames are `[c]` by default, so this solution should apply to all frames whose vertical alignment are not otherwise specified by the user.
