### ISSUE TITLE
Name changes

### ISSUE THREAD

**Issue by rchurchley** [matze/mtheme#112]
We've discussed (in #74 and #75) changing the name of the theme to be more descriptive for CTAN. Recent development has adopted naming conventions under the assumption that the theme will be renamed `metropolis`. Before 1.0 and the CTAN release, we will have to

* decide whether to use `metropolis` as the new name,
* update the manual to reflect the name change, and
* rename the main file(s).

**Comment by benjamin-weiss** [comment]
I think after the recently introduced naming conventions and the proposed logo, `metropolis` is the obvious choice. And I like it. So I'm in favor of renaming the theme to `metropolis`.

**Comment by matze** [comment]
There have been a series of commits fixing this issue. As of now, I am not aware of any more occurences of the old name, so I'll close this issue.
