### ISSUE TITLE
Links cannot be distinguished from plain text

### ISSUE THREAD

**Issue by ibrahima** [matze/mtheme#114]
Hi, first of all I just wanted to say that I love your theme! But one issue I have is that links look like normal text. I'd like to change the color or add an underline to links but I can't figure out if this is possible. I tried adding `\setbeamercolor*{button}{fg=UniBlue}` naively but that didn't seem to work. Is it possible to change the link color somehow? Thanks!

**Comment by benjamin-weiss** [comment]
This should be possible using the hyperref settings.

```TeX
\hypersetup{colorlinks=true,linkcolor=red}
```

**Comment by ibrahima** [comment]
Oh thanks! The latter command was exactly what I needed. I guess my Google-fu wasn't strong enough to find that. I think it might be nice if there was some distinction by default but for me personally that solves my immediate issue.
