### ISSUE TITLE
Enumeration in block does not look nice.

### ISSUE THREAD

**Issue by jakob-r** [matze/mtheme#118]
The numbers of the enumeration within a block element are slightly to far on the left.

**Comment by benjamin-weiss** [comment]
I suppose this was meant with respect to a metropolis version before #113 got merged and can be closed now. Right?

**Comment by matze** [comment]
@jakob-r: could you verify if this is still an issue for you?

**Comment by matze** [comment]
Two weeks time should be long enough for verification :smile:

If this is still an issue, please re-open.
