### ISSUE TITLE
Spacing of blocks in columns, minipages etc. is off

### ISSUE THREAD

**Issue by matze** [matze/mtheme#119]
While [cleaning up the demo](https://github.com/matze/mtheme/commit/e4764c6642f06cefa32454588d9948037cdff4ab), I noticed an issue with `block` environments within columns or minipages. The spacing of the block content is off and is noticeably bad for blocks with background enabled. The following MWE illustrates the problem

```latex
\documentclass[10pt]{beamer}
\usetheme{m}

\begin{document}
\begin{frame}{Blocks in columns}
  \begin{columns}
    \column{1.0\textwidth}
      \begin{block}{Inside}
        Content.
      \end{block}
  \end{columns}

  \begin{block}{Outside}
    Content.
  \end{block}

  \metroset{block=fill}
  \begin{columns}
    \column{1.0\textwidth}
      \begin{block}{Inside}
        Content.
      \end{block}
  \end{columns}

  \begin{block}{Outside}
    Content.
  \end{block}
\end{frame}
\end{document}
```

![blocks](https://cloud.githubusercontent.com/assets/115270/8821715/1da3bcba-3060-11e5-8ff5-0851cca1322c.png)

**Comment by tmgriffiths** [comment]
I'm not alone! I noticed theother day when working on my own theme. I don't think it's endemic to the metropolis theme; It's also in default theme. It's hard to see as there is no background in the default theme, but the small change in vertical space is still there.

```latex
\documentclass[aspectratio=1610]{beamer}

\begin{document}

\begin{frame}
\frametitle{Blocks}
   \begin{block}{Blocks are Used for Emphasis in Beamer}
      Anything can go in a block.
      \begin{itemize}
         \item Bullet points.
         \item For demonstration,
         \item or to summarise something.
      \end{itemize}
   \end{block}
\end{frame}

\begin{frame}[fragile]
\frametitle{Blocks}
   \begin{columns}
      \begin{column}{0.48\textwidth}
         \begin{block}{Blocks}
            Anything can go in a block.
            \begin{itemize}
               \item Bullet points.
               \item For demonstration,
               \item or to summarise something.
            \end{itemize}
         \end{block}
      \end{column}
      \begin{column}{0.48\textwidth}
         \footnotesize
         \begin{verbatim}
\begin{block}{Blocks are Used for Emphasis in Beamer}
   Anything can go in a block.
   \begin{itemize}
      \item Bullet points.
      \item For demonstration,
      \item or to summarise something.
   \end{itemize}
\end{block}
         \end{verbatim}
      \end{column}
   \end{columns}
\end{frame}
```

![one_column](https://cloud.githubusercontent.com/assets/4878624/9036570/0bc32e02-3a26-11e5-8f23-d11c63014f97.png)
![two_column](https://cloud.githubusercontent.com/assets/4878624/9036572/0e68a146-3a26-11e5-98ea-7f482311316e.png)

**Comment by khalid-hussain** [comment]
Love the theme but I've recently come across this as well. Is there a temporary solution?

**Comment by benjamin-weiss** [comment]
@khalid-hussain Your post motivated me to look into this problem again and I finally found a solution. It looks like `\column` sets `\parskip` back to `0pt`. So manually setting it again after `\column` fixes this issue. I'm not sure yet what's the best way to fix this in the theme, but I will prepare a PR soon.

```TeX
\documentclass[10pt]{beamer}
\usetheme[block=fill]{metropolis}

\begin{document}
\begin{frame}{Blocks in columns}

  \begin{columns}
      \column{1.0\textwidth}
      \setlength{\parskip}{0.5em}
      \begin{block}{Inside}
        Content.
      \end{block}
  \end{columns}
  
  \begin{block}{Outside}
    Content.
  \end{block}
\end{frame}
\end{document}
```

**Comment by tmgriffiths** [comment]
Congratulations @benjamin-weiss and @khalid-hussain! I've been staring at this for ages and I never thought to look at `\parskip`. Look forward to to the PR.

**Comment by matze** [comment]
:+1:

Thanks for looking into that issue @benjamin-weiss!
