### ISSUE TITLE
Use of metropolisset macro

### ISSUE THREAD

**Issue by julianofischer** [matze/mtheme#121]
When I try:

**\metropolisset[inner/titleformat=regular]**

The following error is shown:
Undefined control sequence \metropolisset

Could someone help me, please?

**Comment by matze** [comment]
Hi, this is an error in the manual and should actually be `\metroset` instead of `\metropolisset`. I fixed that [in a recent commit](https://github.com/matze/mtheme/commit/fbaf3f83e0efd0cfac8368f74e8cedf920c97dc4) but haven't yet updated the manual.
