### ISSUE TITLE
PDF display issues

### ISSUE THREAD

**Issue by AndySchroder** [matze/mtheme#123]
I've just tested out mtheme and have had some display issues.

On the system I was first working on, the PDF file displayed fine in Okular. Then I copied the final version to my laptop to head out to give a presentation. I noticed that in Okular the titles were not there. I am able to select the titles (they must be hidden), and copy and paste them, but I can't see them. Text in the body of each page did display though. On the same system, I opened up the PDF file in Document Viewer and GIMP, and the titles were displayed.

Then I tried opening the PDF file up on the same machine as it was created on in Adobe Reader 9, and some pages had a black rectangle at the top and then the rest of them had the stardard green rectangle.

I'm using XeLaTeX from within Kile on ubuntu 13.04 to create the PDF file. The laptop is ubuntu 14.04.

The ubuntu 13.04 machine had mtheme installed using the .deb package that was linked to in the instruction manual for mtheme. I installex XeLaTeX using the ubuntu package manager.

I'm not sure if the problem is with XeLaTeX or mtheme, or okular. I've never had a problem like this with okular before. I have never used XeLaTeX before, only PDFLaTeX. I'm really not sure why XeLaTeX is needed for this theme really.

I do plan to install mtheme on the ubuntu 14.04 machine eventually because I will be editing files on there too, but right now, I'm holding off doing so until I get this display issue resolved. I plan to distribute my PDF files on the internet, but I don't want to do so with mtheme until consistently rendering PDF files are produced. Right now the ubuntu 14.04 machine is my test case for this failure, so I don't want to modify it's configuration until I'm comfortable the problem is resolved with mtheme.

**Comment by matze** [comment]
Can you upload the slides or a single slide where this issue occurs?

> I'm really not sure why XeLaTeX is needed for this theme really.

It's "needed" to use system fonts such as in our case *Fira Sans*. PDFLaTeX is unable to load them. You could also try compiling with LuaTeX instead of XeLaTeX and see if the problem persists. I put needed in quotes because it is not strictly required. If you load the individual theme components (inner, outer, color themes) you could use PDFLaTeX.

**Comment by unidesign** [comment]
I totally agree to what Andy said about XeLaTeX resp. `fontspec` and have seen this as a downside of this theme; here's an idea to supply latex / pdflatex support, too.
Since `FiraSans` and `FiraMono` already take care about which pdf creator was used you could easily extend your `beamerfonttheme` by asking if those packages are installed:
```
\IfFileExists{FiraSans.sty}
	{fira sans exists}
	{fira sans doesnt exist}
	
\IfFileExists{FiraMono.sty}
	{fira mono exists}
	{fira mono doesnt exist}
```

 and if not you could check for LuaLaTeX / XeLaTeX and run your code which uses `fontspec`.

Also there is a script `getFiraFont.sh` so it only works on linux and when taking a look in it I see it only works on ubuntu. Here a Lua script would be better since every/most TeX users have the interpreter installed because of LuaLaTeX.

**Comment by AndySchroder** [comment]
After a long and drawn out troubeshooting process, I discovered that the PDF file displays okay if "Enable Text Hinting" is turned off in okular. Apparently the old ubuntu/okular version did not have this option and so that is why that one was working. My newer system had that option and it was selected. I don't know if that is a default setting or if I turned it on myself or not, but if I run as another user on the same machine, the option seemed to be turned off already. Turning it off makes the PDF file display okay in okular. I'm not sure if this is an okular problem or an mtheme problem or xelatex problem. The setting is under settings->configure okular->performance .

Regarding the adobe reader problem. It seems as though this is related some how to including a png image in a slide. It doesn't happen for all png images though. Below are the two images. Here is a simple tex file that reproduces the problem. I can't figure out how to attach the PDF file to this note. Image "a.png" is the one that causes the black instead of green on the top title rectangle. I got these images from wikipedia somewhere, but I don't remember if I resized them or anything.

    \documentclass{beamer}
    \usetheme{m}


    \begin{document}
      	\begin{frame}{Examples: Global and Local Optima}
    		\includegraphics[height=5cm]{a.png}
    	\end{frame}

    	\begin{frame}{Examples: Local Optimum}
    		\includegraphics[height=5cm]{b.png}
    	\end{frame}
    \end{document}


Image "a.png"

![a](https://cloud.githubusercontent.com/assets/4065710/9531023/79467e80-4cd1-11e5-8dd8-99e92433c74e.png)

Image "b.png"

![b](https://cloud.githubusercontent.com/assets/4065710/9531024/79541be4-4cd1-11e5-9155-f0bbd85a684f.png)

**Comment by AndySchroder** [comment]
I should also note that now that I've figured how to trigger the issue is with okular on ubuntu 14.04, I went ahead and installed the mtheme .deb package and tried the above example on there, and it still produces the black rectange rather than green rectangle for the slide with "a.png" in it.

**Comment by matze** [comment]
Hmm, I don't really know what you mean by black rectangle. This is what it looks like at the moment with evince:

![output](https://cloud.githubusercontent.com/assets/115270/9540157/7289f20e-4d5b-11e5-90c2-4d3a9ba35967.png)

The only difference is that a.png has a transparency channel which makes it integrate more nicely with the shaded background whereas b.png has a noticeable border.

As far as I can see, your problems are not related to the theme in particular but with the unfortunate combination of (maybe) XeTeX and your PDF viewers.

**Comment by AndySchroder** [comment]
That is how it looks on my main PDF viewers, but I was also checking with Adobe Reader 9. I was assuming that Adobe would be the most compatible with it's own file format. The black rectangle I am talking about is in place of the green rectangle that is at the top of the slide around the slide title of the first slide (or whatever slide you put "a.png" in).

**Comment by matze** [comment]
You are not [alone](https://forums.adobe.com/thread/86092) but that's clearly an issue with Adobe Reader not with the theme nor TeX nor fontspec. [This](https://forums.adobe.com/thread/395348) might help you.

**Comment by AndySchroder** [comment]
I'm not positive that the links you referenced are the same issue I was having. Regardless, I don't care too teribly much about this issue, so I'm okay that you decided to just close it.
