### ISSUE TITLE
support picture credit line

### ISSUE THREAD

**Issue by maxheld83** [matze/mtheme#129]
**Thanks** (I have to say it):

> I absolutely love this theme, and I can't tell you how happy I am that someone is taking the time and has the skill to make a *great*-looking beamer theme. (which is something that I've been looking for a long time).
> I'm also excited that this is still being actively developed (as opposed to sthklm and hsrm etc.).

The actual **issue**:

I like that these other themes have some support for a picture credit line.

I often use full-screen pictures, and it'd be nice to have a credit line say, at the bottom of the screen, maybe even with CC logos? (of course I use CC assets).

**Comment by benjamin-weiss** [comment]
Although I implemented it at the time for the `hsrmbeamertheme`, I don't think anymore it is a really good idea to have something like that. But you can easily just add the definition of the `hsrmbeamertheme` to your preamble if it is useful for you. Here is a MWE:

```TeX
\documentclass{beamer}
\usetheme{m}
\usepackage{mwe}

\newbox\mytempbox
\newdimen\mytempdimen

\setbeamerfont{copyright text}{size=\tiny}
\newcommand\includegraphicscopyright[3][]{%
  \leavevmode\vbox{\vskip3pt\raggedright\setbox\mytempbox=\hbox{\includegraphics[#1]{#2}}%
    \mytempdimen=\wd\mytempbox\box\mytempbox\par\vskip1pt%
    \usebeamerfont{copyright text}{{\vbox{\hsize=\mytempdimen#3}}}\vskip3pt%
}}

\begin{document}
\begin{frame}{picture with credit line}
  \centering
  \includegraphicscopyright[width=0.75\linewidth]{example-image}{Copyright by \href{https://www.ctan.org/pkg/mwe}{mwe package}}
\end{frame}
\end{document}
```

**Comment by benjamin-weiss** [comment]
You could also use a footnote without numbering or marker.

```TeX
\documentclass{beamer}
\usetheme{m}
\usepackage{mwe}
\newcommand{\creditline}[1]{{\let\thefootnote\relax\footnotetext[1]{#1}}}
\begin{document}
\begin{frame}{picture footnote credit line}
  \centering
  \includegraphics[width=0.75\linewidth]{example-image}
  \creditline{Copyright by \href{https://www.ctan.org/pkg/mwe}{mwe package}}
\end{frame}
\end{document}
```

**Comment by matze** [comment]
@maxheld83: is this still an issue for you or do the snippets by Benjamin help?

**Comment by maxheld83** [comment]
sorry haven't had a chance to try this yet, will report back soon.

**Comment by matze** [comment]
Until then I'll close this issue. Re-open it if it is still pressing or a problem.

**Comment by ArchangeGabriel** [comment]
Sorry to revive this, I’m interested in this too. I like the second example, but it produces a dot in front of the copyright, how can I remove it?

**Comment by benjamin-weiss** [comment]
@ArchangeGabriel It doesn't for me. Is your tex system up to date? Did you actually try my MWE or did you include the code in a existing presentation?

**Comment by ArchangeGabriel** [comment]
Hum, TeX is up-to-date, but you’re right, MWE works. The change that introduces this in `\usepackage[french]{babel}`, but I have not enough knowledge to understand why. I guess babel is redefining footnotes, but found nothing in the doc relevant to that.

**Comment by benjamin-weiss** [comment]
You shoud have looked at the [frenchb documentation](http://mirrors.ctan.org/macros/latex/contrib/babel-contrib/french/frenchb.pdf). Just add `\StandardFootnotes` after you have loaded `babel`.

**Comment by ArchangeGabriel** [comment]
@benjamin-weiss Thank you so much! I didn’t even know they was a `frenchb` documentation…
