### ISSUE TITLE
\metroset{background=dark} does not invert all text colors on title slide

### ISSUE THREAD

**Issue by maxheld83** [matze/mtheme#130]
Oddly, `\metroset{background=dark}` does not affect all parts of the title slide, but only the title and subtitle.
The font color of the rest remains unchanged.

The behavior is different when using `background=dark` as an option; in that case, *all* colors are inverted appropriately on the title slide.

**Comment by maxheld83** [comment]
oddly, setting `\setbeamercolor{normal text}{fg = white, bg = white}` inside that group also does not change the color of date, institute etc.

**Comment by maxheld83** [comment]
I should add: I've set `\texorpdfstring{}...` inside `author{}`, such as:

```
\author[Held \& Zabala]{
  \texorpdfstring{
    \begin{columns}
      \column{.45\linewidth}
      %\centering
      Maximilian Held\\
      \href{mailto:info@maxheld.de}{info@emaxheld.de}\\
      \href{http://www.maxheld.de}{www.maxheld.de}\\
      \column{.45\linewidth}
      %\centering
      Aiora Zabala\\
      \href{mailto:aiora.zabala@gmail.com}{aiora.zabala@gmail.com}\\
      \href{http://people.ds.cam.ac.uk/az296/}{people.ds.cam.ac.uk/az296/}\\
    \end{columns}
  }{
    Maximilian Held \inst{1}
    \and
    Aiora Zabala \inst{2}
  }
}
```

adding this line fixes things:

```
 \usebeamercolor[white]{author}
```

Notably ` \usebeamercolor[fg]{author}` *does not work in this place*

**Comment by rchurchley** [comment]
Thanks for the report! I think I've isolated the issue and submitted a pull request to fix it.

**Comment by treuherz** [comment]
Still getting this problem with a normal slide. Colours invert fine across the presentation when it's set in the preamble, but when using \metroset{background=dark} before a specific slide I want to look different, the title renders fine but all body text is invisible.

**Comment by benjamin-weiss** [comment]
This seems to be a bug in beamer itself. I encountered this problem on another occasion. The workaround mentioned [on StackExchange](http://tex.stackexchange.com/questions/288408/beamer-show-notes-on-second-screen-with-xelatex-and-atbeginsection) seems to be also working here.

```TeX
\documentclass{beamer}
\usetheme{metropolis}

\makeatletter
\def\beamer@framenotesbegin{% at beginning of slide
  \usebeamercolor[fg]{normal text}
  \gdef\beamer@noteitems{}%
  \gdef\beamer@notes{}%
}
\makeatother

\begin{document}
\begin{frame}{Frametitle 1}Frame Content\end{frame}
{
\metroset{background=dark}
\begin{frame}{Frametitle 2}Frame Content\end{frame}
}
\begin{frame}{Frametitle 3}Frame Content\end{frame}
\end{document}
```

**Comment by treuherz** [comment]
Works like a charm, thank you!

**Comment by pinetreemoonlight** [comment]
A maybe related question, how can we invert the pages (background dark, text light) on the title page? I couldn't get it to work somehow.
