### ISSUE TITLE
Wrong frametitle spacing with tailed letters

### ISSUE THREAD

**Issue by elauksap** [matze/mtheme#131]
First of all thank you for your work, I just started using your theme and love it!

The issue I noticed is that the frametitle box has a different height when using the Fira fonts and when the frametitle contains the letters "Q", "Y", etc. due to their tails: it's just as if the rule printed by the command \@metropolis@frametitlestrut had the wrong height (maybe the fonts are not correctly loaded when defining it?).

Thanks in advance!

Edit: obviously the issue is gone when replacing \@metropolis@frametitlestrut with LaTeX default \strut.

Edit2: this figure shows what's going on with the demo.
![metropolis](https://cloud.githubusercontent.com/assets/5830450/9983643/34496ae0-6004-11e5-9568-d15976a98a3b.jpg)

**Comment by matze** [comment]
Thanks for the report. A quite lengthy [PR](https://github.com/matze/mtheme/pull/115) led to the current implementation. I think this issue here is a good place concerning @rchurchley's comment:

> [...] and move discussion of the spacing to a new issue.

**Comment by mindv0rtex** [comment]
To add to this issue - the height of a frame title box also increases when one puts question or exclamation marks in the title.

**Comment by benjamin-weiss** [comment]
Yes you are right. The proposal of @rchurchley with `\vphantom{•}` solves this problem. At the time I thought @tmgriffiths implemented it already and agreed to the merge. Although it doesn't solve all the problems discussed in #115, it is the best solution so far and should imho be implemented.
