### ISSUE TITLE
Head and foot in section page

### ISSUE THREAD

**Issue by MatteoRagni** [matze/mtheme#134]
It is possible to add some shortcut to add code in section pages? (for example to add transition effects just before `/end{frame}` command)

The theme is amazing.

**Comment by benjamin-weiss** [comment]
You want to add the same code just before every `\end{frame}`? This should be possible with the package `etoolbox` and the command `\AtEndEnvironment{⟨environment⟩}{⟨code⟩}`.

Have a look at the documentation of the package here: http://www.ctan.org/pkg/etoolbox

**Comment by MatteoRagni** [comment]
Tried but does not work at all. The idea is perfect...

``` latex
\usepackage{etoolbox}
\AtEndEnvironment{frame}{\transfade[duration=0.25]}
```

**Comment by benjamin-weiss** [comment]
Ok, `\AtEndEnvironment` doesn't seem to work with beamer frames:

http://tex.stackexchange.com/questions/226319/run-a-command-at-end-of-each-frame

I have never used transitions. Does it matter whether the command is inserted at the beginning  or at the end of the `frame`environment? Maybe you could just use `\AtBeginEnvironment{⟨environment⟩}{⟨code⟩}`.

**Comment by MatteoRagni** [comment]
Nope. Tried and not works.
No problem, I'll keep it without transition. This theme is too wonderful.
