### ISSUE TITLE
Is there a support for the \framesubtitle-command?

### ISSUE THREAD

**Issue by reliak** [matze/mtheme#135]
Hi there,

I'm trying to use `\framesubtitle', but it is not working with the metropolis template (i.e. the frame sub title is not displayed).
Am I doing something wrong or is there no support for this command? If so, do you have any alternative solutions?

**Comment by matze** [comment]
As of now, there is no frame subtitle support. Two reasons:

1. It's actually hard to come up with a nice visual representation that does not clutter the frame or cause excessive whitespace.
2. It's a deliberate choice. IMHO, I don't see any good reason to give a single slide yet another title. There's always the (let's say) macro structure of sections and frames and the micro structure of lists, paragraphs, blocks etc. What problem would a subtitle?

**Comment by benjamin-weiss** [comment]
I agree with @matze. We should not support the `\framesubtitle` command. The metropolis theme is and should remain a clutter free theme. But if you really need `\framesubtitle` support it is not that hard to add it on your own. You just have to add some code to the frametitle beamer template. Here is an MWE to get you going.

```TeX
\documentclass{beamer}
\usetheme{m}
\usepackage{blindtext}

\setbeamercolor{framesubtitle}{fg=mDarkTeal, bg=black!2}
\addtobeamertemplate{frametitle}{}{%
  \ifx\insertframesubtitle\@empty\else%
  \usebeamerfont{framesubtitle}%
  \usebeamercolor[fg]{framesubtitle}%
  \insertframesubtitle%
  \fi%
}

\begin{document}
\begin{frame}
  \frametitle{Frametitle}
  \framesubtitle{Framesubtitle}
  \blindtext
\end{frame}
\end{document}
```

**Comment by benjamin-weiss** [comment]
@matze I think we are on the same page here, that we should not implement this. If someone really wants to use it my MWE should be sufficient. Close?

**Comment by matze** [comment]
Fully agree!
