### ISSUE TITLE
lower case in frames and slides

### ISSUE THREAD

**Issue by friolz** [matze/mtheme#137]
Is it normal that the text is in lower case?
Is there a way to change it?

**Comment by matze** [comment]
There is the `everytitleformat` and assorted options to configure the titles. However, by default, the titles should be set in small caps not lower cased. Could you give us a minimum working example and output of what you see?

**Comment by benjamin-weiss** [comment]
To be precise, the default is small caps and lower case. So I suppose he loads a different font without small caps support.

**Comment by friolz** [comment]
** Privatkopie
*** Bild
    :PROPERTIES:
    :BEAMER_COL: 0.48
    :END:
    #+ATTR_LATEX: width=\textwidth
    [[file:img/runner.jpg]]
![medienrecht dragged](https://cloud.githubusercontent.com/assets/2101906/10479942/7e81067a-7267-11e5-982a-244eafecdbe9.png)

**Comment by friolz** [comment]
@benjamin-weiss I have both FiraSans and FiraMono under /Library/Fonts

**Comment by benjamin-weiss** [comment]
Ok. Are there any errors like that it your log file?

```
LaTeX Font Warning: Font shape `...' undefined
(Font)              using `...' instead on input line ... .
```

**Comment by friolz** [comment]
Maybe I should mention that I'm using Emacs org mode. Is it using XeLaTeX?

**Comment by benjamin-weiss** [comment]
Ahh right. I haven't really looked at your screenshot. It looks like you are not typesetting with XeLaTeX or LuaLaTeX, hence the metropolis font theme doesn't get loaded. I never used Emacs org mode so I have no idea how to configure it that XeLaTeX will be used.

**Comment by friolz** [comment]
Ok, with XeLaTeX it's working. Thanks!
