### ISSUE TITLE
Cannot change the section title and frame title into lowercase

### ISSUE THREAD

**Issue by likanzhan** [matze/mtheme#138]
Hi,
I tried to change the frame title and section into lowercases, as follows.
But it does not change (the results are attached).
Any suggestions?

```Tex
\documentclass{beamer}
\usetheme{m}                     % Use metropolis theme
\title{A minimal example}
\date{\today}
\author{Matthias Vogelgesang}
\institute{Centre for Modern Beamer Themes}

\metroset{inner/sectiontitleformat=lowercase} % changes the section title into lowercase
\metroset{outer/frametitleformat=lowercase}  % changes the frame title into lower case

\begin{document}
  \maketitle
  \section{First Section}
  \begin{frame}{First Frame}
    Hello, world!
  \end{frame}
\end{document}
```
![ch08-00](https://cloud.githubusercontent.com/assets/10531698/10532886/8293a558-73f5-11e5-8f25-c8cab582f694.jpg)
![ch08-01](https://cloud.githubusercontent.com/assets/10531698/10532891/8aa3f7e8-73f5-11e5-9805-a81734b0fe0e.jpg)
![ch08-02](https://cloud.githubusercontent.com/assets/10531698/10532892/8ff7cca6-73f5-11e5-9e42-f47600cdb7c5.jpg)

**Comment by benjamin-weiss** [comment]
They are lowercase by default. But they are also set in small caps. So you have to change the small caps to regular. Replace

```Tex
\metroset{inner/sectiontitleformat=lowercase}
\metroset{outer/frametitleformat=lowercase}
```
in your MWE to
```TeX
\setbeamerfont{section title}{family=\Book, size=\Large, shape=\normalfont}
\setbeamerfont{frametitle}{family=\Book, size=\large, shape=\normalfont}
```

**Comment by likanzhan** [comment]
It works.
Thank you very much Benjamin,
Cos I'm relatively new to this and the latex itself, so please forgive me if my questions are two naive.

I got two more questions here:
*1. I actually want to keep all the capital characters as they are, not changing their cases, such as leaving "First" as "First", not changing it to "first". Is it possible?
*2. When an logical operator is included in the frame title, the frame title (the part with blue color) bar gets higher, how can I keep it fixed? For example, if I add a second frame with the frame title as "Second & frame", then the two frame title' bars are different.
```tex
\documentclass{beamer}
\usetheme{m}                     % Use metropolis theme
\title{A minimal example}
\date{\today}
\author{Matthias Vogelgesang}
\institute{Centre for Modern Beamer Themes}

\begin{document}
  \maketitle
  \section{First Section}
  \begin{frame}{First Frame}
    Hello, world!
  \end{frame}
  \begin{frame}{Second \& Frame}
    Thank you
   \end{frame}
\end{document}
```
![ch08-00](https://cloud.githubusercontent.com/assets/10531698/10542904/0555998a-744e-11e5-9041-a5ca94098be0.jpg)
![ch08-01](https://cloud.githubusercontent.com/assets/10531698/10542905/05e51f6a-744e-11e5-964b-5e8c12bdc15a.jpg)
![ch08-02](https://cloud.githubusercontent.com/assets/10531698/10542907/05e93816-744e-11e5-962b-bf10b8c19e1d.jpg)
![ch08-03](https://cloud.githubusercontent.com/assets/10531698/10542906/05e5ec74-744e-11e5-846a-32e2b330cf81.jpg)

**Comment by benjamin-weiss** [comment]
Because of the default value with *lowercase* and *small caps*, I think that the `titleformat` setting is a bit confusing in the theme. But that is a design choice we made and I don't see how we could make that more transparent.

1) To achieve what you want you need to set the `titleformat` to `regular`. As I said. It is a bit confusing.
```TeX
\metroset{inner/sectiontitleformat=regular}
\metroset{outer/frametitleformat=regular}
```
2) This is a known bug last discussed in #131 which I thought was already fix. As a workaround until it is fixed, you can add the following code to your preamble.
```TeX
\makeatletter
\renewcommand{\@metropolis@frametitlestrut}{%
    \vphantom{ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz}
  }
\makeatother
```

**Comment by rchurchley** [comment]
> Because of the default value with lowercase and small caps, I think that the titleformat setting is a bit confusing in the theme. But that is a design choice we made and I don't see how we could make that more transparent.

I think we could help avoid this understandable confusion by:
- renaming `titleformat=lowercase` to `titlecase=allsmallcaps`
- renaming `titleformat=uppercase` to `titlecase=allcaps`

**Comment by benjamin-weiss** [comment]
This would probably help many people, but I don't like it because lowercase and uppercase are actually the proper names.

**Comment by rchurchley** [comment]
"Lowercase" and "uppercase" shed light onto how the options are implemented, but I don't think they're the proper names. According to [Wikipedia's definition](https://en.wikipedia.org/wiki/Small_caps), case refers to the shape, not size, of the letter, so I don't think it's accurate to refer to anything set in `\scshape` as "lowercase" — it has no ascenders or descenders.

That said, you are definitely right that it's important to know that MakeUppercase and MakeLowercase are part of the implementation, so I would also propose highlighting that in the documentation (especially since those macros are a common source of incompatibilities)

**Comment by benjamin-weiss** [comment]
You are right, I was solely looking at it from the implementation point of view. So maybe we should also change the beamer font shape with this option and add a fourth one.

1. `regular` → No case adjustment and `shape=\normalfont`
2. `regularsmallcaps` → No case adjustment and `shape=\scshape`
3. `allsmallcaps` → `\MakeLowercase` and `shape=\scshape`
4. `allcaps` → `\MakeUppercase` and `shape=\normalfont`

This should probably cover all regular use cases and is imho a proper nomenclature.

**Comment by weijy026a** [comment]
If I want the frame title capitalized as this "Statistics and Mathematics", How should I set the command?

**Comment by benjamin-weiss** [comment]
I suppose you mean something like this.
```TeX
\documentclass{beamer}
\usetheme[frametitleformat=regular]{m}
\setbeamerfont{frametitle}{shape=\normalfont}
\begin{document}
\begin{frame}{Statistics and Mathematics}
\end{frame}
\end{document}
```
The frame title is set to small caps by default. So you have to reset that setting too.

**Comment by benjamin-weiss** [comment]
What do you guys think about my proposed renaming for the title format? Shall I implement it?

**Comment by matze** [comment]
:+1:

**Comment by rchurchley** [comment]
I would prefer `regular`, `smallcaps`, `allsmallcaps`, and `allcaps`, just because it's a little easier to remember (especially if `regular` is the default value).

**Comment by benjamin-weiss** [comment]
Sure, that's better. Yet I suppose @matze still wants to have `allsmallcaps` as default, right?

**Comment by matze** [comment]
Yes, from an asthetic viewpoint I still prefer upper cased letters in small caps.

**Comment by rchurchley** [comment]
The `allsmallcaps` option looks better aesthetically but requires some strong assumptions about the contents of each title; it should be avoided, for example, if any title contains anything in math mode. I think it's a great option to offer --- it's the best choice for anyone who has plaintext-only titles --- but is probably a bad choice for the default behaviour.

Perhaps we could continue showing off `allsmallcaps` in the demo slides but change the default value of the title format to `regular` or `smallcaps`?

**Comment by benjamin-weiss** [comment]
I have to agree with @rchurchley. At least we should add a warning to the documentation, that the `allsmallcaps` and `allcaps` options can lead to problems. Maybe even add a PackageWarning when they are used.

@rchurchley Do you know of any other problems apart from the math related problems I should mention in the documentation.

At the moment we completely ignore the subtitle format. Any opinions how we should handle it? Shall I add another theme option `subtitleformat`?

**Comment by rchurchley** [comment]
@benjamin-weiss 
> At least we should add a warning to the documentation, that the allsmallcaps and allcaps options can lead to problems. Maybe even add a PackageWarning when they are used.

We definitely need warnings in the documentation, and I don't have a problem with raising a PackageWarning to remind the user of the potential headaches. This option is useful but it has definitely been the biggest cause of support issues! 

> Do you know of any other problems apart from the math related problems I should mention in the documentation.

Off the top of my head, people who use `allsmallcaps` should be mindful of the following:

- `\MakeLowercase` applies to math mode but `\scshape` does not. This can easily introduce mathematical errors that are hard to catch until it is too late. Examples:

    ```
    $O(m)$ and $o(n^2)$ algorithms    →    o(m) ᴀɴᴅ o(n²) ᴀʟɢᴏʀɪᴛʜᴍs
    The case where $F=f$              →    ᴛʜᴇ ᴄᴀsᴇ ᴡʜᴇʀᴇ f=f
```

- It is impossible to typeset symbols which are encoded as uppercase letters in a different font. In particular, `\mathbb` and `\mathcal` letters will be replaced by other math glyphs. (See #153)

- Only alphabetic characters are affected by `\MakeLowercase`, so numerals and punctuation remain at full height. This can spoil some of the aesthetic benefits of `allsmallcaps`. (See #33)

- Some commands, like `\\`, do not work inside `\MakeLowercase`. (See #125)

- `\MakeLowercase` is incompatible with `allowframebreaks` and similar frame options. (See #20)

- Since `\protect` cancels out `\MakeLowercase`, `smallcaps` should be preferred to `allsmallcaps` if the `protectframetitles` option is also used. (See #59)

> At the moment we completely ignore the subtitle format. Any opinions how we should handle it? Shall I add another theme option subtitleformat?

I think it's fine if the subtitle uses the same format as `titleformat`. Frankly, I wouldn't object to merging the `titleformat`, `frametitleformat`, and `everytitleformat` options together either; I don't think it's a common use case to set the title, subtitle, and frametitle formats independently.

**Comment by benjamin-weiss** [comment]
I knew there were other issues, but obviously there are even more than I expected. Although the `allowframebreaks` issue should be resolved afaik. So I think I more or less copy and paste your list into the *Known Issues* section of the documentation and refer to it from the *Package Options* section. Agreed?

I don't think merging the titleformats is a good idea. From a users perspective there is no downside, that every titleformat can be set independently. But once merged it would really need some effort to set them independently. Furthermore the subtitle is typeset as `smallcaps` right now, so linking it to the `titleformat` would change the default behavior.

**Comment by matze** [comment]
You start convincing me to change the default, however I suppose we will get further support requests if users see small caps in the demo but regular titling in their presentations. I guess the best solution would be to stick to one (I suppose you prefer regular) but show *switching* between title formats within the demo. AFAIR that was possible last time I checked.

**Comment by benjamin-weiss** [comment]
Yes, I think `regular` would be the best choice. Because even `smallcaps` is problematic if you typeset with `pdfTeX`, as Computer Modern Sans Serif doesn't support small caps and uses the Computer Moden Serif small caps instead.

I like the idea of showcasing the switching in the demo.

**Comment by rchurchley** [comment]
@benjamin-weiss 
> Although the `allowframebreaks` issue should be resolved afaik.

Ah, you're right. For some reason I thought that `allowframebreaks` required `protectframetitle` but it seems I was mistaken.

> Agreed?

Sounds good.

> I don't think merging the titleformats is a good idea. From a users perspective there is no downside, that every titleformat can be set independently. But once merged it would really need some effort to set them independently. Furthermore the subtitle is typeset as smallcaps right now, so linking it to the titleformat would change the default behavior.

Good points. The primary user benefit for merging the options would be to have more easily memorable option names — I expect `everytitleformat` to be the most commonly used option, but it is not easy to remember. In that case, I should amend my comment to: I wouldn't object to renaming the titleformat options to follow a clearer naming convention. The following seriously breaks backwards compatibility, but something like it might be a little clearer?
```
titleformat
titleformat title
titleformat subtitle
titleformat section
titleformat plain
```

@matze 
> You start convincing me to change the default, however I suppose we will get further support requests if users see small caps in the demo but regular titling in their presentations. I guess the best solution would be to stick to one (I suppose you prefer regular) but show switching between title formats within the demo. AFAIR that was possible last time I checked.

Good point about support requests. I like showcasing the switching in the demo too.

**Comment by benjamin-weiss** [comment]
> Ah, you're right. For some reason I thought that `allowframebreaks` required `protectframetitle` but it seems I was mistaken.

It did. But I think I fixed that some time ago by patching `\beamer@@frametitle`.

> The following seriously breaks backwards compatibility, but something like it might be a little clearer?

I like your proposed naming scheme and I think right now is the right time to change it, if we want to. As of backwards compatibility we could just add aliases, like we already did with `usetitleprogressbar`, `noslidenumbers` and so on.

**Comment by matze** [comment]
> I like your proposed naming scheme and I think right now is the right time to change it, if we want to.

:+1: 

As far as I can see it's the last remaining point before we can upload the first version to CTAN.

**Comment by rchurchley** [comment]
With the new renamed `titleformat` options now implemented with clearer option values, can we call this issue resolved?

**Comment by matze** [comment]
Yes we can! :-)

**Comment by likanzhan** [comment]
Yes!

Thank you guys very much!!

Likan
——————————————————————————————
