### ISSUE TITLE
Offset of the progress bar if option used

### ISSUE THREAD

**Issue by EHadoux** [matze/mtheme#14]
Hi,

when I compile my slides with the progress bar option, there is a gap:
![image](https://cloud.githubusercontent.com/assets/1655646/5701557/018453a4-9a4d-11e4-93c4-0fef6f83c90b.png)

However, when I modify https://github.com/matze/mtheme/blob/master/beamerthemem.sty#L207 and set the vspace to -.6em it looks like:
![image](https://cloud.githubusercontent.com/assets/1655646/5701572/4f6b3d26-9a4d-11e4-9857-22d92e0017a0.png)
as it should be.
It is the case in both a Mac and a PC with Debian.

Actually, some stuffs are not similar to the example like section pages and progress bar in section pages.

Cheers,
Emmanuel

**Comment by matze** [comment]
Thanks for pointing out that issue. That regression was probably caused by edacbdc2c50bc5fa3f445c22d.
