### ISSUE TITLE
Problem with mlineplot, mbarplot (using Sharelatex)

### ISSUE THREAD

**Issue by emghufran** [matze/mtheme#141]
Hi, 

There seems to be a problem with the graphs/plots color schemes. After trying to (un)successfully installing it on Windows, I decided to use it on ShareLatex website. 

It turns out that the mlineplot/mbarplot keys are not recognized. 
The error reported: 
Package pgfkeys Error: I do not know the key '/tikz/mlineplot' and I am going to ignore it. Perhaps you misspelled it.

The latex :
\begin{frame}[fragile]
  \frametitle{Evaluation I}
  \begin{figure}
    \begin{tikzpicture}
      \begin{axis}[
        mlineplot,
        width=0.9\textwidth,
        height=6cm,
      ]

        \addplot {sin(deg(x))};
        \addplot+[samples=100] {sin(deg(2*x))};

      \end{axis}
    \end{tikzpicture}
  \end{figure}
\end{frame}

Also, this example is not part of the github demo anymore but was found on your blog. Any suggestions to make it work?

**Comment by benjamin-weiss** [comment]
Please post a Minimal Working Example (MWE) in the future and put the code in a syntax highlighted markdown block in the future. This makes it easier for us to help you. Here is an example how to do that:

    ```TeX
    \begin{example} ... \end{example}
    ```
The following MWE works fine with the latest version of the theme.
```TeX
\documentclass{beamer}
\usetheme{m}
\usepackage{pgfplots}

\begin{document}
\begin{frame}[fragile]{Evaluation I}
  \begin{figure}
    \begin{tikzpicture}
      \begin{axis}[mlineplot, width=0.9\textwidth, height=6cm]
      \addplot {sin(deg(x))};
      \addplot+[samples=100] {sin(deg(2*x))};
      \end{axis}
    \end{tikzpicture}
  \end{figure}
\end{frame}
\end{document}
```
Maybe you can share your ShareLaTeX project to give us more insight.

**Comment by emghufran** [comment]
Thank you for your reply and sorry about the mark-up mess.

I started a completely new project from sharelatex and put your sample code in it. I attach the screenshots with this message. I can share the project with you if you let me know the address to share it with. 

![capture](https://cloud.githubusercontent.com/assets/2620/10545910/74db9110-742b-11e5-8f35-121d93f43892.PNG)
![capture2](https://cloud.githubusercontent.com/assets/2620/10545911/74ddc502-742b-11e5-86d7-350178c6dd1a.PNG)

**Comment by benjamin-weiss** [comment]
I just shared a ShareLaTeX project with you. It is a bit of a mess to get Metropolis up and running on ShareLaTeX, as you have to manually edit the `beamerfontthememetropolis.sty` file. At least I don't see an other way right now. After the planned overhaul of the font theme this will hopefully be easier.

**Comment by benjamin-weiss** [comment]
@matze This issue also seems to be resolved.
