### ISSUE TITLE
mtheme using 'fontspec' package unconditionally

### ISSUE THREAD

**Issue by XVilka** [matze/mtheme#143]
It is valid only for the XeTeX and LuaTeX, and not valid for the pdfLaTeX. Would be nice to have the conditional use of it.

**Comment by benjamin-weiss** [comment]
I don't know if i really understand what you mean. Do you want to use `fontspec` with pdfLaTeX? Because that doesn't make no sense as`fontspec` doesn't support pdfLaTeX.

**Comment by XVilka** [comment]
@benjamin-weiss nope, looks like the theme itself does using fontspec, which is not available for pdfLaTeX, yes. And I would like to use it with pdfLaTeX too.

**Comment by gavinsimpson** [comment]
What @XVilka is getting at is that they'd like to use the theme with pdflatex and hence is requesting whether the use of fontspec could be made optional with a default of on.

**Comment by benjamin-weiss** [comment]
You can use the theme with pdfLaTeX. If you compile a presentation with pdfLaTeX `fontspec` will not be loaded. I think I still don't get the issue here.

**Comment by XVilka** [comment]
Yes, it works now. Sorry, I was using an old version of the theme.
