### ISSUE TITLE
Graph background becomes dack grey

### ISSUE THREAD

**Issue by superpronker** [matze/mtheme#144]
Thanks for an awesome theme, it really looks great. 

However, when I insert a Matlab 3D graph, the background becomes black instead of "white" (rather, the off-white default in the theme). Here is a screenshot: http://imgur.com/k2tWK66

It works well with standard 2D graphs from Matlab. The 3D graph is saved as a pdf by the way so that it is in vector graphic format. I assume this is why the error happens but I don't see why there's a difference between 2D and 3D graphs. 

More generally, some graphs have white background which becomes clear since the standard background color is not white but some off-white color. But I suppose this is an option?

**Comment by benjamin-weiss** [comment]
Please provide a MWE. Without one it, is really difficult to find the problem and help you.

**Comment by superpronker** [comment]
If you insert this graph: https://dl.dropboxusercontent.com/u/4785175/graph.pdf
(I cannot upload due to writing permissions, it seems) 

and use this code to reproduce the problem. 

--------
\documentclass{beamer}
\usetheme{m}

\begin{document}
	
\setbeamercolor{background canvas}{bg=white} % -> does not help 
\begin{frame}\frametitle{Test}
	\includegraphics[width=.65\textwidth]{graph.pdf}
\end{frame}

\end{document}
---

**Comment by benjamin-weiss** [comment]
This is not really a theme related problem, not even a beamer related problem. Your PDF strangly uses the current color as part of the image.
```TeX
\documentclass[11pt]{article}
\usepackage{xcolor}
\usepackage{graphicx}

\begin{document}
  \color{red}
  \includegraphics[width=.65\textwidth]{graph.pdf}
\end{document}
```
But this doesn't happen if the color is black or grey. Then it uses white instead. So this at least results in a white background.
```TeX
\documentclass{beamer}
\usetheme{m}
\begin{document}
\begin{frame}\frametitle{Test}
{
  \color{black}
  \includegraphics[width=.65\textwidth]{graph.pdf}
}
\end{frame}
\end{document}
```
The only proper solution I found is to remove the background part of the PDF which gets colored manually. But it should be possible to directly export a pdf with a transparent background from Matlab. This could be helpful:

http://www.mathworks.com/matlabcentral/fileexchange/23629-export-fig

Here is the edited graph:

https://www.dropbox.com/s/gqu3lg0ynk1az9f/graph_edited.pdf?dl=0

**Comment by matze** [comment]
Since this issue is not related to this theme, I'll close this issue for now.

**Comment by superpronker** [comment]
Yes, please do that. And thank you so much Benjamin, wonderful work (and impressively found!) - I really appreciate the help.
