### ISSUE TITLE
Set block body example bg et fg colour

### ISSUE THREAD

**Issue by danjjl** [matze/mtheme#146]
*Probably not an issue/missing feature but a limit of my LaTex skills.*

It is not possible to change the background or foreground colour of an example block using:

```latex
\setbeamercolor{block body example}{%
    use=block title example,
    bg=block title example.bg!10,
    fg=block title example.fg
}
```

**Comment by benjamin-weiss** [comment]
Actually this is a bug. I will prepare a PR for this.
