### ISSUE TITLE
`Arithmetic overflow` when using `titleprogressbar` with > 45 frames

### ISSUE THREAD

**Issue by liantze** [matze/mtheme#15]
Here are the error message and minimal example that produces it:

````
[44]
! Arithmetic overflow.
\progressbar@titleprogressbar ...essbar@tmpcounta 
                                                  \divide \progressbar@tmpdi...
l.51 \test
          
? 
````

````
\documentclass{beamer}
\usetheme[titleprogressbar]{m}

\newcommand{\test}{\begin{frame}{Title}blahblahblah\end{frame}}

\begin{document}
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\test
\end{document}
`````

**Comment by matze** [comment]
Thanks for reporting that issue!

**Comment by liantze** [comment]
That was fast -- thanks!

**Comment by mike-ghes** [comment]
Arithmetic overflow now seems to occur at 75 pages. I'm using a version off of overleaf so it may just be out of date.

I've been tinkering with values for "\divide\progressbar@tmpdim by" and "\multiply\progressbar@tmpdim by" but can't seem to find any magic numbers.

**Comment by matze** [comment]
This is indeed an issue again :frowning:

**Comment by bgat** [comment]
I haven't worked through all the math in the current template, but at one point I vaguely recall concluding that the problem was actually an underflow, not an overflow. I added an if() to replace a zero result with 1, and the problem seemed to go away.

Darned if I can find that code, though. I meant to send it, but I don't think I ever did...

**Comment by eddelbuettel** [comment]
I am having on sections too in a presentation with > 75 pages.

**Comment by eddelbuettel** [comment]
My bad.  Only happens with the copy of the code base I took in May (to make minor adjustments).  Works fine with the current code -- so :+1:.

**Comment by liantze** [comment]
Current code doesn't seem to have this problem any more with any number of slides -- yeay!
