### ISSUE TITLE
mathcal command in frame title and section title

### ISSUE THREAD

**Issue by Dralliag** [matze/mtheme#153]
In regular beamer I can use mathcal in frame title and section title like

    \begin{frame}{$\mathcal{F}$}
    \end{frame}

with mtheme it does not work. The $\mathcal{F}$ is replaced by a curly brace in the frame title.

**Comment by benjamin-weiss** [comment]
By default `metropolis` typesets the frame title as all lowercase small caps. And the `\MakeLowercase` seems to be the problem here. As a workaround you can either set the `frametitleformat` to `uppercase` or `regular`. At the moment I don't see any other solution.

```TeX
\documentclass{beamer}
\usetheme[frametitleformat=uppercase]{metropolis}
\begin{document}
\begin{frame}{$\mathcal{F}$}
	Regular: $\mathcal{F}$

	Uppercase: \MakeUppercase{$\mathcal{F}$}
	
	Lowercase: \MakeLowercase{$\mathcal{F}$}
\end{frame}
\end{document}
```

**Comment by Dralliag** [comment]
Thanks! It even simply works with lowercase with

  \documentclass{beamer}
  \usetheme{metropolis}
  \begin{document}
  \begin{frame}{\MakeUppercase{$\mathcal{F}$}}
  \end{frame}
  \end{document}
