### ISSUE TITLE
\plain not working with pandoc

### ISSUE THREAD

**Issue by op8867555** [matze/mtheme#157]
Hi, I'm trying to use pandoc to generate slides but `\plain` is not working: plain slide aren't generated.

an example here:
run `pandoc -t beamer -o test.pdf test.pdc --latex-engine xelatex -V theme:metropolis`
the generated pdf is missing the plain slide.

test.pdc:
```markdown
---
title: Test
include-after:
  - \plain{Hello}
---

## Test
- 1
- 2
```

**Comment by matze** [comment]
That is caused by Pandoc insisting to add `ignorenonframetext` to Beamer's package load options. See also #28.

**Comment by op8867555** [comment]
Thanks, didn't notice that.
