### ISSUE TITLE
Section background

### ISSUE THREAD

**Issue by kikijiki** [matze/mtheme#16]
When I compile the demo document the section background is different.

![capture](https://cloud.githubusercontent.com/assets/784077/5793006/59881148-9f76-11e4-9fd4-21e2d40c7bbb.PNG)

**Comment by kikijiki** [comment]
Ops, just found your comment here https://github.com/matze/mtheme/commit/514f95f8f6161e1e05a910623914776e768bfe39

**Comment by matze** [comment]
Maybe I will make it optional. But I found the dark backgrounds pretty hard on the eyes.

**Comment by kikijiki** [comment]
I see, I thought I was compiling it wrong.
I'll close this!

**Comment by matze** [comment]
I should probably update the demo ;-)
