### ISSUE TITLE
Line breaks in section heading

### ISSUE THREAD

**Issue by twsh** [matze/mtheme#163]
If a section heading is too long there will be a line break with hyphenation. This doesn't look right to me (although I'm prepared to be told otherwise). I'm not an expert with Beamer, but I looked at the code and it seems to be that this is where the section heading slides are defined:
```
\defbeamertemplate{section page}{progressbar}{
  \centering
  \begin{minipage}{22em}
    \usebeamercolor[fg]{section title}
    \usebeamerfont{section title}
    \insertsectionhead\\[-1ex]
    \usebeamertemplate*{progress bar in section page}
  \end{minipage}
  \par
}
```
Would something as simple as adding `\raggedright` inside the minipage change the behaviour in the right way?

**Comment by matze** [comment]
I agree that it looks really bad, not the hyphenation but rather the stretching to achieve justification. If there are no other implications, I suppose the proposed fix could help. I'll see if that is a feasible solution.

**Comment by benjamin-weiss** [comment]
You are right. A `\raggedright` would change this behavior. But whether the current behavior or your proposed change is the "right" one is probably a matter of taste. imho one should try to keep section titles as short as possible that a line break does not even happen.

Although I don't have a strong opinion on the hyphenation, I recognized something else while looking into this matter. If a line break happens the progress bar gets shifted down. I think it would be best if the progress bar stays at the same position.

**Comment by matze** [comment]
> imho one should try to keep section titles as short as possible that a line break does not even happen.

That is very true but I guess we cannot demand how people lay out their slides. And the hyphenated title can really look bad

![comparison](https://cloud.githubusercontent.com/assets/115270/11680885/a6ba3560-9e5b-11e5-844d-2db43ab49b5e.png)

> If a line break happens the progress bar gets shifted down.

Indeed … I suppose if we want to support a fixed progress bar, we really have to go down the rabbit hole regardless of hyphenation or not. So I suggest to change at least to `\raggedright`.

**Comment by benjamin-weiss** [comment]
Ok, you are right. Your example looks really bad. So let us just add the `\raggedright`.

But as I already said, the progress bar should keep its position. Like this for example:

```TeX
\defbeamertemplate{section page}{progressbar}{
  \centering
  \begin{minipage}{22em}
    \raggedright
    \usebeamercolor[fg]{section title}
    \usebeamerfont{section title}
    \insertsectionhead\\[-1ex]
    \usebeamertemplate*{progress bar in section page}
  \end{minipage}
  \par
  \vspace{0.48\paperheight} % add fixed space to the bottom
}
\newcommand{\@metropolis@sectionpage@progressbar}{
  \setbeamertemplate{section page}[progressbar]
  \AtBeginSection{
    \ifbeamer@inframe
      \sectionpage
    \else
      \frame[plain,b]{\sectionpage} % vertically align at the bottom
    \fi
  }
}
```

**Comment by rchurchley** [comment]
I think we all agree we need to add `\raggedright` to the progress bar section page template. Perhaps we should do that for now and discuss tweaking the spacing in another issue (#184)?
