### ISSUE TITLE
File `beamerthememetropolis.sty' not found.

### ISSUE THREAD

**Issue by psamim** [matze/mtheme#167]
I get the following error:

```
! LaTeX Error: File `beamerthememetropolis.sty' not found.
```

And after renaming beamerthemem.sty to beamerthememetropolis.sty the problem is fixed.

**Comment by psamim** [comment]
I installed the package via AUR in Archlinux, I am not sure if it is a packaging problem or not. I think it is outdated.

**Comment by benjamin-weiss** [comment]
I suppose you were using this package: https://aur.archlinux.org/packages/texlive-mtheme/

If so, you are right. This package installs a quite outdated version of the theme, namely this commit https://github.com/matze/mtheme/commit/eb5a7d7c9d64eeccf1913baa3234ac51ca7da139.

**Comment by rchurchley** [comment]
It looks like this issue is now resolved, thanks to [a new AUR package](https://aur.archlinux.org/packages/beamer-theme-metropolis/) pointing to the 1.0 version of Metropolis!

**Comment by matze** [comment]
@psamim: please re-open if still an issue or better yet talk directly to the package maintainer.

**Comment by RoyiAvital** [comment]
Could you provide pre compiled `beamerthememetropolis.sty`?

Thank You.
