### ISSUE TITLE
Problem with fira font

### ISSUE THREAD

**Issue by zoraidafb** [matze/mtheme#168]
Hi! I have just started using the metropolis theme and I am unable to get the pdf with the Fira Font, and since the Fira package is not a hard dependancy I get the font by default.  

I have checked I have the fira package updated in MikTeX (2.9). I am using Windows 7. 
I am just using the small example provided in the user manual. 

Any help is appreciated.

**Comment by matze** [comment]
I don't have a Windows machine (whoever does: please chime in) but all you need, is install the Fira font in your system and use XeLaTeX instead of the default pdfTeX compiler and you should be fine.

**Comment by zoraidafb** [comment]
Thank you for your response! I was using pdftex. Now it works, but I get the codding of the title and sections wrong, i.e. when typing x it appears y, and Á instead of A, etc.,  Any idea?

Thnk you very much.

**Comment by matze** [comment]
This is really hard for me to tell without seeing the input file but there are certain situations I can imagine causing this problem:

* The file encoding is broken. Can you verify, your file is saved as UTF-8?
* You installed a weird version of the font. Did you get it from a trusted source?

**Comment by matze** [comment]
Please re-open if this is still a problem for you. Thanks.
