### ISSUE TITLE
Wrong math symbols using Fira

### ISSUE THREAD

**Issue by alcarazr** [matze/mtheme#170]
Hi,

I am using the minimal example provided in the documentation. I also have the Fira font installed in my system, working. If I write an equation (after the 'Hello, world!' text for example) and compile with pdfTeX, everything is just fine. However, if I compile with XeTeX, I see the Fira font but the math symbols in the equation are wrong.

I am almost sure this has to do with a (very) recent update of other packages I performed yesterday (before it was working fine). I am using Mac OS X 10.11.3 with a full MacTeX-2015 distribution, updated using Tex Live Utility.

I will be glad to provide further details if you cannot reproduce this issue.

Thanks in advance,

Rodrigo

**Comment by alcarazr** [comment]
I just got an update for fontspec today:

> Change history
--------------

- v2.5a (2016/02/01) "bugs fixed"

    * Rather embarrassing bug fix! (`unicode-math` was broken.)

Nevertheless I still suffer the problem (no warnings or errors in the console log).

Thanks!

**Comment by KristofferC** [comment]
Same here, 

for example:

![image](https://cloud.githubusercontent.com/assets/1282691/12791046/95a62cb8-caa5-11e5-95a4-50060bad835e.png)


![image](https://cloud.githubusercontent.com/assets/1282691/12791027/805ff884-caa5-11e5-8f27-c358da777e06.png)

**Comment by benjamin-weiss** [comment]
This is a problem with the current version of Latex2e (2016/02/01) and a fix is already on its way. See my question on [SE](http://tex.stackexchange.com/questions/290970/wrong-math-symbols-with-xelatex-and-luatex-after-texlive-update). So just wait a few days and update TeX Live again and the problem should go away.

**Comment by benjamin-weiss** [comment]
The fix is now available on TeX Live.

@matze This issue can be closed.
