### ISSUE TITLE
How do I install this theme?

### ISSUE THREAD

**Issue by manujgarg10** [matze/mtheme#176]
Hi, this theme looks beautiful! I have been trying to install it using the instructions given here: https://github.com/matze/mthem... But I can't quite follow what 2 and 3 are saying. How do I do this? (I'm using MacTex on OSX El Capitan). Thanks!

"2. Compile the style files by running make sty inside the downloaded directory. (Or run LaTeX directly on source/metropolistheme.ins.)

3. Move the resulting *.sty files to the folder containing your presentation. To use Metropolis with many presentations, run make install or move the *.sty files to a folder in your TeX path instead (might require sudo rights)."

**Comment by benjamin-weiss** [comment]
You have to run these commands (`make` and `make install`) in the Terminal application of OS X. You can find it in the folder `/Applications/Utilities`. Open it and change to the directory you extracted the theme to. So if you downloaded it to your Downloads folder type `cd ~/Downloads/mtheme-master`, then `make` to create the `sty` files and `make install` to copy them to your TeX path.

**Comment by manujgarg10** [comment]
Thank you so much Benjamin! This worked!
Btw, the subtitles slide are not showing up. Is this a limitation of the theme?

**Comment by benjamin-weiss** [comment]
You are welcome.

> Btw, the subtitles slide are not showing up. Is this a limitation of the theme?

Yes we decided not to support the frame subtitles. Have a look at this issue on how to add a simple subtitle to the theme: https://github.com/matze/mtheme/issues/135

**Comment by manujgarg10** [comment]
Thanks Benjamin, I agree that it's cleaner without a subtitle. I'll just redo the few titles where this is an issue.
 
However, one thing: a lot of my previous slides need to be reworked now since each slide in Metropolis captures less text (compared with, say, Madrid) and there is always a line or two getting cut off :( Is there a way to force the text into the slide?
...for future, I can just write slides according to Metropolis.

**Comment by benjamin-weiss** [comment]
A simple method to achieve that would be to use the `shrink` option on those frames.
```TeX
\documentclass{beamer}
\usetheme{metropolis}

\begin{document}
\begin{frame}[shrink=5]{Frame Title}
	Frame Content
\end{frame}
\end{document}
```

**Comment by manujgarg10** [comment]
Thank you very much Benjamin!
