### ISSUE TITLE
Adjust spacing on section pages

### ISSUE THREAD

**Issue by rchurchley** [matze/mtheme#184]
In #163, @benjamin-weiss suggested

> If a line break happens [in a section title] the progress bar gets shifted down. I think it would be best if the progress bar stays at the same position.

He proposed to bottom-align the section page and add a space underneath:
```latex
\defbeamertemplate{section page}{progressbar}{
  \centering
  \begin{minipage}{22em}
    \raggedright
    \usebeamercolor[fg]{section title}
    \usebeamerfont{section title}
    \insertsectionhead\\[-1ex]
    \usebeamertemplate*{progress bar in section page}
  \end{minipage}
  \par
  \vspace{0.48\paperheight} % add fixed space to the bottom
}
\newcommand{\@metropolis@sectionpage@progressbar}{
  \setbeamertemplate{section page}[progressbar]
  \AtBeginSection{
    \ifbeamer@inframe
      \sectionpage
    \else
      \frame[plain,b]{\sectionpage} % vertically align at the bottom
    \fi
  }
}
```

**Comment by rchurchley** [comment]
I actually don't think we need to worry too much about fixing the progress bar. Since section pages will never be consecutive slides in the presentation, it won't be jarring to the audience if it moves around a little bit.

However, @benjamin-weiss is right that the spacing is not ideal when the section title is too long. The title and progress bar seems to sink a little too far down to the bottom of the slide:
![screen shot 2016-03-02 at 2 22 04 am](https://cloud.githubusercontent.com/assets/1131743/13457562/c4323026-e01d-11e5-8957-931acd4b04e6.png)

We probably should visually compensate for this somehow, but I don't think fixing the progress bar is the right solution. With it, long titles can rise too high to the top of the slide:
![screen shot 2016-03-02 at 2 11 24 am](https://cloud.githubusercontent.com/assets/1131743/13457580/de7947ee-e01d-11e5-8bd3-fe6bfd7cb52c.png)

---
I would instead propose keeping `[c]` on the frame and adding a little extra `vspace` below the progress bar. On closer inspection, even one- and two-line section titles are a little lower down than they could be, so I think this is a reasonably well-balanced solution for all title lengths.

```latex
\defbeamertemplate{section page}{progressbar}{
  \centering
  \begin{minipage}{22em}
    \raggedright
    \usebeamercolor[fg]{section title}
    \usebeamerfont{section title}
    \insertsectionhead\\[-1ex]
    \usebeamertemplate*{progress bar in section page}
  \end{minipage}
  \par
  \vspace{\baselineskip}
}
\newcommand{\metropolis@sectionpage@progressbar}{
  \setbeamertemplate{section page}[progressbar]
  \AtBeginSection{
    \ifbeamer@inframe
      \sectionpage
    \else
      \frame[plain,c,noframenumbering]{\sectionpage}
    \fi
  }
}
```

What do you think?

![screen shot 2016-03-02 at 2 19 01 am](https://cloud.githubusercontent.com/assets/1131743/13457460/3e62a336-e01d-11e5-8ce3-31be6b8fc804.png)
![screen shot 2016-03-02 at 2 19 16 am](https://cloud.githubusercontent.com/assets/1131743/13457464/40a68a0e-e01d-11e5-966d-ccb95b4643a7.png)
![screen shot 2016-03-02 at 2 19 27 am](https://cloud.githubusercontent.com/assets/1131743/13457467/42ba18a6-e01d-11e5-958a-d57699f264d8.png)

**Comment by matze** [comment]
Looks good to me. Anything longer should really make the presenter suspicious …

Do you want to make the relevant change?
