### ISSUE TITLE
White used as font colour if notes enabled

### ISSUE THREAD

**Issue by andreskytt** [matze/mtheme#191]
When building the following MVE:

```
\documentclass{beamer}
\usepackage{pgfpages}
\setbeameroption{show notes on second screen=right} 

\usetheme{metropolis}           % Use metropolis theme
\title{A minimal example}
\date{\today}
\author{Matthias Vogelgesang}
\institute{Centre for Modern Beamer Themes}
\begin{document}
  \maketitle
  \section{First Section}
  \begin{frame}{First Frame}
    Hello, world!
  \end{frame}

\end{document}

```
The words "Hello, world!" are rendered in white instead of the regular colour. The result is attached.
[metropolisdemo.pdf](https://github.com/matze/mtheme/files/160293/metropolisdemo.pdf)

**Comment by benjamin-weiss** [comment]
Have a look at this TeX.SE question: http://tex.stackexchange.com/questions/288408/beamer-show-notes-on-second-screen-with-xelatex-and-atbeginsection

**Comment by andreskytt** [comment]
This does indeed fix the font colour problem but messes up formatting for section titles, references, etc.
```
\documentclass{beamer}
\usepackage{pgfpages}
\setbeameroption{show notes on second screen=right} 

\usetheme{metropolis}           % Use metropolis theme
\title{A minimal example}
\date{\today}
\author{Matthias Vogelgesang}
\institute{Centre for Modern Beamer Themes}


\AtBeginSection{
    \frame{\insertsectionhead}
}

\makeatletter 
\def\beamer@framenotesbegin{% at beginning of slide
     \usebeamercolor[fg]{normal text}
      \gdef\beamer@noteitems{}% 
      \gdef\beamer@notes{}% 
}
\makeatother

\begin{document}
  \maketitle
  \section{First Section}
  \begin{frame}{First Frame}
    Hello, world!
  \end{frame}

\end{document}
```

[metropolisdemo.pdf](https://github.com/matze/mtheme/files/160394/metropolisdemo.pdf)

My LaTeX knowledge is limited but I'll try to have a stab at creating a pull request for fixing this.

**Comment by benjamin-weiss** [comment]
I think you misunderstood something here. We use
```TeX
\AtBeginSection{...}
```
in the metropolis theme to create the section frames. That's why you are affected of this beamer bug if you are using the metropolis theme. And
```TeX
\AtBeginSection{
    \frame{\insertsectionhead}
}
```
overwrites the metropolis section frames. To fix the bug you only need
```TeX
\makeatletter 
\def\beamer@framenotesbegin{% at beginning of slide
     \usebeamercolor[fg]{normal text}
      \gdef\beamer@noteitems{}% 
      \gdef\beamer@notes{}% 
}
\makeatother
```

**Comment by matze** [comment]
Documented workaround is in place, therefore I will close this issue for now.

**Comment by andreskytt** [comment]
Works a treat in conjunction with dspdfviewer, thanks for clearing this up!

**Comment by kumo** [comment]
Sorry for reopening this, but I saw that this causes problems with the standout frames, where the font colour is usually white.
