### ISSUE TITLE
Content-dependent header height

### ISSUE THREAD

**Issue by alcarazr** [matze/mtheme#192]
Hi,

I have noticed that the height of the header is content-dependent. This is especially notorious when using the `smallcaps` option for the `titleformat`. A MWE (compile with XeTeX):
```TeX
\documentclass{beamer}
\usetheme[titleformat=smallcaps]{metropolis} % Use metropolis theme
\begin{document}
\begin{frame}{Hí}
Hello, world! \end{frame}
\begin{frame}{Hi}
Hello, world! \end{frame}
\end{document}
```

Is this expected? According to this [TeX-LaTeX Stack Exchange question](http://tex.stackexchange.com/questions/110677/fix-height-of-frametitle-independent-of-content), a couple of `\strut` (before and after) in the `\insertframetitle` command should do. By looking at the source code of _metropolis_, I would say this is already included.

Thank you very much in advance,
Rodrigo

**Comment by benjamin-weiss** [comment]
This was a long discussion here. Have a look at the most recent issue #165 and the PR #183 merged 6 days ago. So you have to install the latest version of the theme here from Github and you should then get the following output for your MWE:

![metropolis_header](https://cloud.githubusercontent.com/assets/9158719/13605707/20d97d7c-e549-11e5-88e0-8808a1714729.gif)

**Comment by alcarazr** [comment]
Thanks a lot. Glad to see this was already noticed and has a working fix. I guess it will be included in the next version so for now I will wait until the package is updated. I suppose this issue can be closed then.

**Comment by benjamin-weiss** [comment]
It will sure be included in the next release. So yes, you can close this issue.

@matze @rchurchley As Ross was very active these last few weeks it probably makes sense to release a version 1.1 on CTAN. Or at least make a plan what we want to include in it before releasing.

**Comment by matze** [comment]
I labeled all pending issues some time ago and with Ross' fixes in place, I actually planned to release this weekend.
