### ISSUE TITLE
subsection slide right after section slide

### ISSUE THREAD

**Issue by dcherian** [matze/mtheme#197]
If you use the `subsectionpage` option, a subsection page is inserted right after the section page for the first subsection. This seems unnecessary to me. I have subsections only for one particular section, the remaining sections don't have them.

Right now, I can disable it using `\metroset{sectionpage=none}` in the right place. It seems like a global option to disable section pages _if_ there is a subsection page would be a good idea. Do you agree?

**Comment by rchurchley** [comment]
I've added a quick note to the `subsectionpage` option documentation in pull request #195 .

**Comment by matze** [comment]
Alright, thanks.

**Comment by mikewojnowicz** [comment]
What about a subsubsection page?
