### ISSUE TITLE
Installation on Ubuntu

### ISSUE THREAD

**Issue by AndySchroder** [matze/mtheme#198]
I have ubuntu 14.04 LTS. Your documentation includes a link to a .deb package. I've used this in the past, but it looks like you have now released a version 1.0. There are features in the current documentation that don't seem to work in the 0.1 version that is available in the documentation as a deb package (which I already had installed before today). It's a little confusing that you've got a version 1.0 documentation with a 0.1 version .deb download link.

I've tried cloning your repository and running "make sty" as instructed, but I am getting the following error:

```
$ make sty
This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian)
 restricted \write18 enabled.
entering extended mode
! I can't find file `me/mtheme/.latex-cache'.
<*> me/mtheme/.latex-cache 
                           beamerthememetropolis.ins
(Press Enter to retry, or Control-D to exit)
```

, which I press Control-D to exit from.

Also,

    sudo tlmgr update --all

does not seem to work on ubuntu:

```
$ sudo tlmgr update --all
(running on Debian, switching to user mode!)
cannot setup TLPDB in /home/andy/texmf at /usr/bin/tlmgr line 5336.

```

Ultimately, I'd prefer to just have an updated deb package, but am looking for any solution to upgrade to your latest version.

Thanks,

**Comment by benjamin-weiss** [comment]
>  I guess you don't have something setup right to handle general path names with spaces in them.

See #196 

> However, I am still having a problem because "make sty" seems to use pdflatex and then I cannot compile my slide show with xelatex anymore.

`make sty` just extracts the `sty` files from the `dtx` files, so it doesn't matter if xelatex or pdflatex is used. You should still be able to compile your presentations with xelatex.

**Comment by AndySchroder** [comment]
Did the old version 0.1 deb package install the fonts local to wherever it was installing the sty files to?

**Comment by benjamin-weiss** [comment]
The deb package is not maintained by us. So I don't know.

What is the error you get when you compile with XeLaTeX?

**Comment by rchurchley** [comment]
I believe the Debian package may have been authored by @eddelbuettel, who also contributed the docker files to this theme; he might be able to shed some light on this.

For the time being, pull request #195 removes the link to the Debian package from the documentation until we can settle this versioning confusion.

**Comment by eddelbuettel** [comment]
I think I only fixed some minor aspects to the Docker theme -- but yes I once wrote a .deb that is still in my PPA.

I should update that, and the post a link here.

**Comment by benjamin-weiss** [comment]
Do you still see a benefit of having a .deb, now that metropolis is available via CTAN?

**Comment by eddelbuettel** [comment]
Yes, and strongly so. But that may just be me and why I created the package for myself.  At least half the reason had to do with the font integration.

**Comment by AndySchroder** [comment]
Here is the beginning of the error message I get from XeLaTeX:

```
(/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec.cfg)))kpathsea:make_tex: Invalid fontname `Fira Mono Medium/ICU', contains ' '


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
! 
! The font "Fira Mono Medium" cannot be found.
```

There is a lot more junk after this, but it's always extremely difficult for me to gain much meaning from most of the latex error messages beyond the first one. As I was saying above, XeLaTeX does not have this problem when I use mtheme from the old .deb package.

**Comment by AndySchroder** [comment]
In an unrelated matter, what is the point of the docker files with this project?

**Comment by AndySchroder** [comment]
Regarding CTAN: tlmgr does not seem to work in ubuntu, as I mentioned above. From what I can find, it's not even expected to work. Is this correct? I think ubuntu users may just be expected to wait for ubuntu repository's texlive packages to be manually updated with files from CTAN by the ubuntu package maintainers? If this is true, then I definitely agree there is a need for the .deb package for mtheme, at least until this theme matures enough that it is not changing significantly or rapidly like it has been in the last year or so (a lot of great things have happened in such a short time!). Any other opinions?

**Comment by benjamin-weiss** [comment]
> Yes, and strongly so. But that may just be me and why I created the package for myself. At least half the reason had to do with the font integration.

Ok. Although I cannot really believe, installing the Fira fonts is that difficult on a Linux machine. But I'm doing all my TeX stuff on OS X, so what do I know... Maybe you should wait with your update until 1.1 is officially released on CTAN, that the .deb package and the CTAN release are exactly the same version. 

> Here is the beginning of the error message I get from XeLaTeX ...

Ok seems like you are having exactly the problems @eddelbuettel tries to avoid with his .deb package. Maybe it is best if you just wait for the release of his updated package?

> tlmgr does not seem to work in ubuntu, as I mentioned above. From what I can find, it's not even expected to work. Is this correct?

It is possible to use tlmgr with ubuntu. Have a look here: http://tex.stackexchange.com/a/95373/30195

**Comment by matze** [comment]
> I think ubuntu users may just be expected to wait for ubuntu repository's texlive packages to be manually updated with files from CTAN by the ubuntu package maintainers?

Good news is that the theme was added by Debian to the TeXlive distribution and *will be* [available](http://packages.ubuntu.com/xenial/texlive-latex-extra) with the upcoming Ubuntu 16.04 LTS. So we don't have to wait indefinitely. However, I cannot promise that it will be version 1.1 of the theme but rather 1.0.

**Comment by xuhdev** [comment]
Check this link to install the latest package without installing a huge vanilla texlive: https://tex.stackexchange.com/questions/137428/tlmgr-cannot-setup-tlpdb

**Comment by matze** [comment]
> However, I cannot promise that it will be version 1.1 of the theme but rather 1.0.

It will be 1.1 as well 0.1.1 of @rchurchley's color theme (didn't know that it existed until now). Anyway, this issue is particular to OP's system, so I think we can archive this for the time being.

**Comment by benjamin-weiss** [comment]
>as well 0.1.1 of @rchurchley's color theme (didn't know that it existed until now but looks great!).

I didn't know it either. But your right. It looks really good. As Metropolis is quite popular now, we can maybe add some info about it in the README.md to advertise it a little bit.

**Comment by rchurchley** [comment]
> It looks really good.

You two are very kind. I made the colour theme [owl](https://github.com/rchurchley/beamercolortheme-owl) at about the same time that we finalized the Metropolis 1.1 release, so I'm very happy we finished them both in time to make the next Ubuntu LTS.

I would be delighted to have Metropolis advertise `owl` in some way, but I'm not sure the `README` is the best place for it. If you don't object, perhaps we could use `owl` as an example in section 3.2 of the manual to show that other pre-made colour schemes can be used with Metropolis.

In any case, we're well off topic for this Issue now :)

**Comment by eddelbuettel** [comment]
At last, I sat down to create a new package and to upload it:

- [GitHub repo](https://github.com/eddelbuettel/pkg-latex-metropolis)
- [Ubuntu PPA](https://launchpad.net/~edd/+archive/ubuntu/misc/+packages)

The PPA (currently) has builds for wily (15.10) and xenial (16.04); these _will_ also run on older installations or Debian installations as they have no binary dependencies.  I kept the font outside of and also created a font package [in this GitHub repo](https://github.com/eddelbuettel/pkg-fonts-fira). It cannot build on Launchpad for PPAs as Launchpad does not let us fetch font files (or anything else for that matter) from GitHub.  So you have to build that locally -- see the README.

I guess it is a matter of personal preference if one likes the individual .deb packages better, or a full Docker container.  I prefer the former; but understand if that others may like Docker better.

I hope this is useful to one or two others.

**Comment by eddelbuettel** [comment]
As a follow-up, I found that what I wrote (in R + Markdown, processed by Pandoc, then LaTeX) on a 15.10 box with my local packages did **not** work on 16.04.  It failed for lack of Fira fonts, and LaTeX macro issue.

So how are folks experiences with what is in Ubuntu 16.04?  Good enough?  Or not really?
