### ISSUE TITLE
custom TOC style

### ISSUE THREAD

**Issue by ZacDiggum** [matze/mtheme#199]
Hi,
on the demo slides I've seen that your TOC is numbered, but when I compile my presentation it's just plain text. How do you force the numbered TOC? Also, are there other customization options?

Thanks...

**Comment by benjamin-weiss** [comment]
> How do you force the numbered TOC?

You can enable the numbering for the sections and subsections in the TOC with the following two commands. 
```TeX
\setbeamertemplate{section in toc}[sections numbered]
\setbeamertemplate{subsection in toc}[subsections numbered]
```
>Also, are there other customization options?

What kind of customizations are you looking for? Just have a look at the [documentation](http://mirrors.ctan.org/macros/latex/contrib/beamer-contrib/themes/metropolis/doc/metropolistheme.pdf) for the available customizations for the theme.

**Comment by ZacDiggum** [comment]
Thank you, that did the trick. I realize my questions are related to beamer, not to your theme. Which is beautiful btw. I'll dive into the beamer docs for more.
Thanks again...
