### ISSUE TITLE
Standout and labeled frames

### ISSUE THREAD

**Issue by jabranham** [matze/mtheme#203]
Hi - 

First, thanks for the awesome theme. 

Second, I get errors when I try to use standout with a labeled frame. To be clear

```latex
\documentclass{beamer}
\usetheme{metropolis}

\begin{document}
\begin{frame}[standout, label=conclusion]{Conclusion}
Awesome slide
  \end{frame}
\end{document}
```

results in an `error: label undefined` for me

**Comment by rchurchley** [comment]
Does it work if you change the order of the keys in the frame?

```latex
\documentclass{beamer}
\usetheme{metropolis}

\begin{document}
\begin{frame}[label=conclusion, standout]{Conclusion}
    Awesome slide
\end{frame}
\end{document}
```
The `standout` option creates a group to restrict the colour change to a single slide. When you put `label=conclusion` after `standout`, the label is defined inside the group and undefined outside of that scope. If you put `label=conclusion` before `standout` (and thus the beginning of the group) then I think it should work normally.

**Comment by jabranham** [comment]
Hrm... yes, it does. That's not a great solution for me, since I'm writing in org-mode, which exports to latex. It automatically adds the `label` *after* frame options. I'll see if I can change that behavior, though. Thanks!

**Comment by jabranham** [comment]
Just in case someone else stumbles here using org mode export to beamer with standout slides, you can get it to work with the following (using `org-set-property`)

```
* Start of a frame
   :PROPERTIES:
   :BEAMER_opt: label=findings,standout
   :END:
```

**Comment by dcherian** [comment]
What were you using earlier?

**Comment by jabranham** [comment]
No properties. Beamer adds a "label" attribute automatically (if one doesn't exist) in recent versions.

**Comment by matze** [comment]
@rchurchley: do you think the suggestion is good for the "tips & tricks" section?

**Comment by rchurchley** [comment]
@matze Sure — it certainly couldn't hurt!
