### ISSUE TITLE
Standout frames in Pandoc

### ISSUE THREAD

**Issue by fogwatt** [matze/mtheme#205]
Can't seem to get Standout frames to work in Pandoc: Pandoc suggests frame attributes like {.standout} but this is ignored. Any advice?

**Comment by matze** [comment]
Please refer to https://github.com/jgm/pandoc/issues/2462 and check if it applies to you. If so, please close this issue.

**Comment by fogwatt** [comment]
It doesn't, I have the most recent version of pandoc 1.17.0.3. But I'm happy to close this issue and raise it with Pandoc if you think it a Pandoc issue?

**Comment by matze** [comment]
I guess you might get a proper solution from Pandoc's side than ours, but until this issue is resolved you can keep it open.

**Comment by rchurchley** [comment]
I believe Pandoc [looks for a specific list of frame attributes](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/LaTeX.hs#L344), not arbitrary names of the form `{.foo}`. Pandoc ignores your `{.standout}` syntax because `standout` isn't on this list.

**Comment by fogwatt** [comment]
Thanks Ross -- it looks like  you're right. Unfortunately I can't use that attribute, and nor does it work if I use raw LaTex (\begin{frame}[standout]) in the Markdown file. I suppose I can do it in two stages, but it's a shame not to be able to use standout frames directly in Pandoc.

**Comment by jabranham** [comment]
Pandoc now supports `{.standout}` so this should work. Related pandoc issue: https://github.com/jgm/pandoc/issues/3007#event-711456707

**Comment by matze** [comment]
Great! Thanks for covering that issue over there :+1:

**Comment by fogwatt** [comment]
Thank you both for this - much appreciated. Happy to close the issue now.
