### ISSUE TITLE
Fira Font URLs yield 404

### ISSUE THREAD

**Issue by RalfJung** [matze/mtheme#206]
These URLs in the `getFiraFont.sh` script yield a 404 when downloading them:
```
wget "http://dev.carrois.com/wordpress/wp-content/uploads/downloads/fira_3_1/FiraSans3106.zip"
wget "http://dev.carrois.com/wordpress/wp-content/uploads/downloads/fira_3_1/FiraMono3106.zip"
```

**Comment by ChipmunkMath** [comment]
Looks like Fira development currently lives on GitHub:
https://github.com/mozilla/Fira

Don't necessarily see an easy way pull a small-ish collection (the entire thing is 102MB, unreasonably large for this purpose). Easier full collections are probably the [OTF font packages at Font Squirrel](https://www.fontsquirrel.com/fonts/list/find_fonts?q[term]=fira):
(direct download) https://www.fontsquirrel.com/fonts/download/fira-sans
(direct download) https://www.fontsquirrel.com/fonts/download/fira-mono

I don't know how to integrate that into the shell script, though.

**Comment by rchurchley** [comment]
If we stick with the Carrois versions of the fonts, I believe the new URLs should be:
```
http://www.carrois.com/downloads/fira_4_1/FiraFonts4106.zip
http://www.carrois.com/downloads/fira_mono_3_2/FiraMonoFonts3206.zip
```
The name of the folders in the shell script will also need to be changed, but other than that things should work fine.

I suppose this raises an important issue, though, as we're going to run into this problem every time a new version of Fira is released. Is anybody willing to keep an eye on the Fira repo or the Carrois URL and update `getFiraFont.sh` every time it changes?

**Comment by matze** [comment]
> I suppose this raises an important issue, though, as we're going to run into this problem every time a new version of Fira is released.

Well, ideally URLs wouldn't change and old versions not deleted. But of course we cannot demand anything in that regard.

> Is anybody willing to keep an eye on the Fira repo or the Carrois URL and update getFiraFont.sh every time it changes?

I certainly won't. It would be possible to set up a Travis job so we could see if the URLs are still working everytime we push a commit but on the other hand that sounds like a waste of resources. So, for now let's hope the URLs won't change :-)
