### ISSUE TITLE
Font Problem

### ISSUE THREAD

**Issue by Schaschka** [matze/mtheme#207]
Hello everybody, 

yesterday I installed the metropolis package. Very nice theme, thank you for all the work.
I tried to compile demo.tex from the metropolis ctan package and get the wrong fonts. It compiles but without the right fonts.

With:
```latex
\documentclass{beamer}
\usetheme{metropolis}
\begin{document}
  \section{Introduction}
  \begin{frame}
    Lorem ipsum dolor sit amet.
  \end{frame}
\end{document}
```
I get:
```
Package beamerthememetropolis Warning: Could not find Fira Sans fonts on input line 91.
Package beamerthememetropolis Warning: Could not find Fira Mono fonts on input line 91.
```

I use xubuntu 14.04 with texlive-full from the repositories, compiled with xelatex under kile and donloaded the fira and metropolis packages from ctan.  The file fira-samples.tex compiles fine and also

```latex
\documentclass{beamer}
\usetheme{Warsaw}
\usepackage[sfdefault]{FiraSans}
\begin{document}
  \section{Introduction}
  \begin{frame}
    Lorem ipsum dolor sit amet.
  \end{frame}
\end{document}
```

works. This is my first post on github, so I hope I gave you all necessary informations. 

Flo

The full output of demo.tex:

*****
*****     XeLaTeX output: 
*****     cd "/home/flo/Dokumente/Riorosum"
*****     xelatex -interaction=nonstopmode demo.tex
*****
This is XeTeX, Version 3.1415926-2.5-0.9999.3 (TeX Live 2013/Debian)
 restricted \write18 enabled.
entering extended mode
(./demo.tex
LaTeX2e <2011/06/27>
Babel <3.9h> and hyphenation patterns for 78 languages loaded.
(/usr/share/texmf/tex/latex/beamer/base/beamer.cls
(/usr/share/texmf/tex/latex/beamer/base/beamerbasercs.sty)
Document Class: beamer 2012/10/15 development version 3.24 A class for typesett
ing presentations (rcs-revision 24853e6b98cf)
(/usr/share/texmf/tex/latex/beamer/base/beamerbasemodes.sty
(/usr/share/texmf/tex/latex/beamer/base/beamerbasedecode.sty))
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/share/texmf/tex/latex/beamer/base/beamerbaseoptions.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty))
(/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
(/usr/share/texlive/texmf-dist/tex/latex/base/size12.clo)
(/usr/share/texmf/tex/latex/pgf/basiclayer/pgfcore.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/graphics.cfg)
(/usr/share/texlive/texmf-dist/tex/xelatex/xetex-def/xetex.def)))
(/usr/share/texmf/tex/latex/pgf/systemlayer/pgfsys.sty
(/usr/share/texmf/tex/latex/pgf/utilities/pgfrcs.sty
(/usr/share/texmf/tex/generic/pgf/utilities/pgfutil-common.tex)
(/usr/share/texmf/tex/generic/pgf/utilities/pgfutil-latex.def
(/usr/share/texlive/texmf-dist/tex/latex/ms/everyshi.sty))
(/usr/share/texmf/tex/generic/pgf/utilities/pgfrcs.code.tex))
(/usr/share/texmf/tex/generic/pgf/systemlayer/pgfsys.code.tex
(/usr/share/texmf/tex/generic/pgf/utilities/pgfkeys.code.tex
(/usr/share/texmf/tex/generic/pgf/utilities/pgfkeysfiltered.code.tex))
(/usr/share/texmf/tex/generic/pgf/systemlayer/pgf.cfg)
(/usr/share/texmf/tex/generic/pgf/systemlayer/pgfsys-xetex.def
(/usr/share/texmf/tex/generic/pgf/systemlayer/pgfsys-common-pdf.def)
(/usr/share/texmf/tex/generic/pgf/systemlayer/pgfsys-common-pdf-via-dvi.def)))
(/usr/share/texmf/tex/generic/pgf/systemlayer/pgfsyssoftpath.code.tex)
(/usr/share/texmf/tex/generic/pgf/systemlayer/pgfsysprotocol.code.tex))
(/usr/share/texmf/tex/latex/xcolor/xcolor.sty
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/color.cfg))
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcore.code.tex
(/usr/share/texmf/tex/generic/pgf/math/pgfmath.code.tex
(/usr/share/texmf/tex/generic/pgf/math/pgfmathcalc.code.tex
(/usr/share/texmf/tex/generic/pgf/math/pgfmathutil.code.tex)
(/usr/share/texmf/tex/generic/pgf/math/pgfmathparser.code.tex)
(/usr/share/texmf/tex/generic/pgf/math/pgfmathfunctions.code.tex
(/usr/share/texmf/tex/generic/pgf/math/pgfmathfunctions.basic.code.tex)
(/usr/share/texmf/tex/generic/pgf/math/pgfmathfunctions.trigonometric.code.tex)
(/usr/share/texmf/tex/generic/pgf/math/pgfmathfunctions.random.code.tex)
(/usr/share/texmf/tex/generic/pgf/math/pgfmathfunctions.comparison.code.tex)
(/usr/share/texmf/tex/generic/pgf/math/pgfmathfunctions.base.code.tex)
(/usr/share/texmf/tex/generic/pgf/math/pgfmathfunctions.round.code.tex)
(/usr/share/texmf/tex/generic/pgf/math/pgfmathfunctions.misc.code.tex)))
(/usr/share/texmf/tex/generic/pgf/math/pgfmathfloat.code.tex))
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcorepoints.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcorepathconstruct.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcorepathusage.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcorescopes.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcoregraphicstate.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcoretransformations.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcorequick.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcoreobjects.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcorepathprocessing.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcorearrows.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcoreshade.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcoreimage.code.tex
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcoreexternal.code.tex))
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcorelayers.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcoretransparency.code.tex)
(/usr/share/texmf/tex/generic/pgf/basiclayer/pgfcorepatterns.code.tex)))
(/usr/share/texmf/tex/latex/pgf/utilities/xxcolor.sty)
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty)
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty)

Package hyperref Message: Stopped early.

)

Package hyperref Message: Driver (autodetected): hxetex.

(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hxetex.def
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/puenc.def)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/stringenc.sty)
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/se-ascii-print.def)
(/usr/share/texmf/tex/latex/beamer/base/beamerbaserequires.sty
(/usr/share/texmf/tex/latex/beamer/base/beamerbasecompatibility.sty)
(/usr/share/texmf/tex/latex/beamer/base/beamerbasefont.sty
(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty
(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty)))
(/usr/share/texmf/tex/latex/beamer/base/beamerbasetranslator.sty
(/usr/share/texmf/tex/latex/beamer/base/translator/translator.sty
(/usr/share/texmf/tex/latex/beamer/base/translator/translator-language-mappings
.tex))) (/usr/share/texmf/tex/latex/beamer/base/beamerbasemisc.sty)
(/usr/share/texmf/tex/latex/beamer/base/beamerbasetwoscreens.sty)
(/usr/share/texmf/tex/latex/beamer/base/beamerbaseoverlay.sty)
(/usr/share/texmf/tex/latex/beamer/base/beamerbasetitle.sty)
(/usr/share/texmf/tex/latex/beamer/base/beamerbasesection.sty)
(/usr/share/texmf/tex/latex/beamer/base/beamerbaseframe.sty)
(/usr/share/texmf/tex/latex/beamer/base/beamerbaseverbatim.sty)
(/usr/share/texmf/tex/latex/beamer/base/beamerbaseframesize.sty)
(/usr/share/texmf/tex/latex/beamer/base/beamerbaseframecomponents.sty)
(/usr/share/texmf/tex/latex/beamer/base/beamerbasecolor.sty)
(/usr/share/texmf/tex/latex/beamer/base/beamerbasenotes.sty)
(/usr/share/texmf/tex/latex/beamer/base/beamerbasetoc.sty)
(/usr/share/texmf/tex/latex/beamer/base/beamerbasetemplates.sty
(/usr/share/texmf/tex/latex/beamer/base/beamerbaseauxtemplates.sty
(/usr/share/texmf/tex/latex/beamer/base/beamerbaseboxes.sty)))
(/usr/share/texmf/tex/latex/beamer/base/beamerbaselocalstructure.sty
(/usr/share/texlive/texmf-dist/tex/latex/tools/enumerate.sty))
(/usr/share/texmf/tex/latex/beamer/base/beamerbasenavigation.sty)
(/usr/share/texmf/tex/latex/beamer/base/beamerbasetheorems.sty
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/share/texlive/texmf-dist/tex/latex/amscls/amsthm.sty))
(/usr/share/texmf/tex/latex/beamer/base/beamerbasethemes.sty))
(/usr/share/texmf/tex/latex/beamer/base/themes/theme/beamerthemedefault.sty
(/usr/share/texmf/tex/latex/beamer/base/themes/font/beamerfontthemedefault.sty)

(/usr/share/texmf/tex/latex/beamer/base/themes/color/beamercolorthemedefault.st
y)
(/usr/share/texmf/tex/latex/beamer/base/themes/inner/beamerinnerthemedefault.st
y)
(/usr/share/texmf/tex/latex/beamer/base/themes/outer/beamerouterthemedefault.st
y))) (./beamerthememetropolis.sty
(/usr/share/texlive/texmf-dist/tex/latex/etoolbox/etoolbox.sty
(/usr/share/texlive/texmf-dist/tex/latex/etex-pkg/etex.sty))
(/usr/share/texlive/texmf-dist/tex/latex/pgfopts/pgfopts.sty
(/usr/share/texmf/tex/latex/pgf/utilities/pgfkeys.sty
(/usr/share/texmf/tex/generic/pgf/utilities/pgfkeys.code.tex)))
(./beamerinnerthememetropolis.sty
(/usr/share/texlive/texmf-dist/tex/latex/tools/calc.sty)
(/usr/share/texmf/tex/latex/pgf/frontendlayer/tikz.sty
(/usr/share/texmf/tex/latex/pgf/basiclayer/pgf.sty
(/usr/share/texmf/tex/generic/pgf/modules/pgfmoduleshapes.code.tex)
(/usr/share/texmf/tex/generic/pgf/modules/pgfmoduleplot.code.tex)
(/usr/share/texmf/tex/latex/pgf/compatibility/pgfcomp-version-0-65.sty)
(/usr/share/texmf/tex/latex/pgf/compatibility/pgfcomp-version-1-18.sty))
(/usr/share/texmf/tex/latex/pgf/utilities/pgffor.sty
(/usr/share/texmf/tex/generic/pgf/utilities/pgffor.code.tex))
(/usr/share/texmf/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex
(/usr/share/texmf/tex/generic/pgf/libraries/pgflibraryplothandlers.code.tex)
(/usr/share/texmf/tex/generic/pgf/modules/pgfmodulematrix.code.tex)
(/usr/share/texmf/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarytopat
hs.code.tex)))) (./beamerouterthememetropolis.sty)
(./beamercolorthememetropolis.sty) (./beamerfontthememetropolis.sty
(/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3names.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3bootstrap.sty))
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3basics.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3expan.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3tl.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3seq.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3int.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3quark.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3prg.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3clist.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3token.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3prop.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3msg.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3file.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3skip.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3keys.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3fp.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3box.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3coffins.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3color.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3luatex.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3candidates.sty))
(/usr/share/texlive/texmf-dist/tex/latex/l3packages/xparse/xparse.sty)
(/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec-patches.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/fixltx2e.sty)
*************************************************
* LaTeX warning: "xparse/redefine-command"
* 
* Redefining document command \oldstylenums with arg. spec. 'm' on line 128.
*************************************************
) (/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty
(/usr/share/texlive/texmf-dist/tex/latex/euenc/eu1enc.def)
(/usr/share/texlive/texmf-dist/tex/latex/euenc/eu1lmr.fd))
(/usr/share/texlive/texmf-dist/tex/xelatex/xunicode/xunicode.sty
(/usr/share/texmf/tex/latex/tipa/t3enc.def
(/usr/share/texlive/texmf-dist/tex/latex/euenc/eu1lmss.fd)))
(/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec.cfg)))kpathsea:make_tex: Invalid fontname `Fira Sans Light', contains ' '
kpathsea:make_tex: Invalid fontname `Fira Sans Light Italic', contains ' '
kpathsea:make_tex: Invalid fontname `Fira Sans', contains ' '
kpathsea:make_tex: Invalid fontname `Fira Sans Italic', contains ' '
kpathsea:make_tex: Invalid fontname `Fira Sans Light OT', contains ' '
kpathsea:make_tex: Invalid fontname `Fira Sans Light Italic OT', contains ' '
kpathsea:make_tex: Invalid fontname `Fira Sans OT', contains ' '
kpathsea:make_tex: Invalid fontname `Fira Sans Italic OT', contains ' '
kpathsea:make_tex: Invalid fontname `Fira Mono', contains ' '
kpathsea:make_tex: Invalid fontname `Fira Mono Bold', contains ' '
kpathsea:make_tex: Invalid fontname `Fira Mono OT', contains ' '
kpathsea:make_tex: Invalid fontname `Fira Mono Bold OT', contains ' '

Package beamerthememetropolis Warning: Could not find Fira Sans fonts on input 
line 91.

Package beamerthememetropolis Warning: Could not find Fira Mono fonts on input 
line 91.

))
(/usr/share/texlive/texmf-dist/tex/latex/appendixnumberbeamer/appendixnumberbea
mer.sty) (/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)
(/usr/share/texlive/texmf-dist/tex/latex/ccicons/ccicons.sty
(/usr/share/texlive/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkeyval.tex)))
(/usr/share/texlive/texmf-dist/tex/latex/pgfplots/pgfplots.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.revision.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotscore.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/sys/pgfplotssysgeneric.code
.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/pgfplotslibrary.code.t
ex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/oldpgfcompatib/pgfplotsoldp
gfsupp_loader.code.tex
Package pgfplots: loading complementary code for your PGF version...

(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/oldpgfcompatib/pgfplotsoldp
gfsupp_misc.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/oldpgfcompatib/pgfplotsoldp
gfsupp_pgfkeys.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/oldpgfcompatib/pgfplotsoldp
gfsupp_pgfkeysfiltered.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/oldpgfcompatib/pgfplotsoldp
gfsupp_pgfmathfloat.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/oldpgfcompatib/pgfplotsoldp
gfsupp_pgflibraryplothandlers.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/oldpgfcompatib/pgfplotsoldp
gfsupp_pgflibraryfpu.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/oldpgfcompatib/pgfplotsoldp
gfsupp_pgfcorescopes.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/oldpgfcompatib/pgfplotsoldp
gfsupp_pgfcorelayers.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsutil.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotslists
tructure.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotslists
tructureext.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsarray
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsmatri
x.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/numtable/pgfplotstableshare
d.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsdeque
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsbinary.code.te
x
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsbinary.data.co
de.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsutil.verb.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/pgflibrarypgfplots.sur
fshading.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/sys/pgflibrarypgfplots.surf
shading.pgfsys-xetex.def
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/sys/pgflibrarypgfplots.surf
shading.pgfsys-dvipdfmx.def))))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotscolormap.code.
tex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotscolor.code.tex
))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsstackedplots.code.t
ex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsplothandlers.code.t
ex
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsmeshplothandler.cod
e.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.scaling.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotscoordprocessing.cod
e.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.errorbars.code.tex
) (/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.markers.code.tex
) (/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsticks.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.paths.code.tex)
(/usr/share/texmf/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarydecor
ations.code.tex
(/usr/share/texmf/tex/generic/pgf/modules/pgfmoduledecorations.code.tex))
(/usr/share/texmf/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarydecor
ations.pathmorphing.code.tex
(/usr/share/texmf/tex/generic/pgf/libraries/decorations/pgflibrarydecorations.p
athmorphing.code.tex))
(/usr/share/texmf/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarydecor
ations.pathreplacing.code.tex
(/usr/share/texmf/tex/generic/pgf/libraries/decorations/pgflibrarydecorations.p
athreplacing.code.tex)))
(/usr/share/texmf/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibraryplotm
arks.code.tex
(/usr/share/texmf/tex/generic/pgf/libraries/pgflibraryplotmarks.code.tex)))
(/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/tikzlibrarypgfplots.da
teplot.code.tex (/usr/share/texmf/tex/latex/pgf/utilities/pgfcalendar.sty
(/usr/share/texmf/tex/generic/pgf/utilities/pgfcalendar.code.tex)))
(/usr/share/texlive/texmf-dist/tex/latex/tools/xspace.sty)
(./pgfplotsthemetol.sty) (./demo.aux) (/usr/share/texmf/tex/latex/tipa/t3cmr.fd
)
*geometry* driver: auto-detecting
*geometry* detected driver: xetex
ABD: EveryShipout initializing macros
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
(./demo.out) (./demo.out)
(/usr/share/texmf/tex/latex/beamer/base/translator/dicts/translator-basic-dicti
onary/translator-basic-dictionary-English.dict)
(/usr/share/texmf/tex/latex/beamer/base/translator/dicts/translator-bibliograph
y-dictionary/translator-bibliography-dictionary-English.dict)
(/usr/share/texmf/tex/latex/beamer/base/translator/dicts/translator-environment
-dictionary/translator-environment-dictionary-English.dict)
(/usr/share/texmf/tex/latex/beamer/base/translator/dicts/translator-months-dict
ionary/translator-months-dictionary-English.dict)
(/usr/share/texmf/tex/latex/beamer/base/translator/dicts/translator-numbers-dic
tionary/translator-numbers-dictionary-English.dict)
(/usr/share/texmf/tex/latex/beamer/base/translator/dicts/translator-theorem-dic
tionary/translator-theorem-dictionary-English.dict)
Package pgfplots notification 'compat/show suggested version=true': document ha
s been generated with the most recent feature set (\pgfplotsset{compat=1.9}).

(./demo.nav)
Overfull \vbox (16.67491pt too high) detected at line 24
[1] (./demo.toc) [2] (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/umsa.fd)
(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/umsb.fd) [3] (./demo.vrb

LaTeX Font Warning: Font shape `EU1/lmss/bx/sc' undefined
(Font)              using `EU1/lmss/bx/n' instead on input line 3.

LaTeX Font Warning: Font shape `EU1/lmss/m/sc' in size <12> not available
(Font)              Font shape `EU1/lmr/m/sc' tried instead on input line 5.

(/usr/share/texlive/texmf-dist/tex/latex/euenc/eu1lmtt.fd)) [4] (./demo.vrb)
[5] [6] [7]

LaTeX Font Warning: Font shape `EU1/lmss/m/sc' in size <14.4> not available
(Font)              Font shape `EU1/lmr/m/sc' tried instead on input line 76.

[8]

Package beamerthememetropolis Warning: Be aware that titleformat frame=allsmall
caps can lead to problems on input line 80.

[9]

Package beamerthememetropolis Warning: Be aware that titleformat frame=allcaps 
can lead to problems on input line 93.

[10] [11] (./demo.vrb) [12]

LaTeX Font Warning: Font shape `EU1/lmtt/bx/it' in size <12> not available
(Font)              Font shape `EU1/lmtt/b/sl' tried instead on input line 129.

[13] [14] [15] [16] [17] [18] [19]
*************************************************
* fontspec warning: "addfontfeatures-ignored"
* 
* \addfontfeature(s) ignored; it cannot be used with a font that wasn't
* selected by fontspec.
*************************************************
[20] [21] [22] [23] [24] [25] (./demo.vrb) [26] [27] [28] [29] [30]

Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\translate ' on input line 316.

(./demo.vrb) [31] (./demo.bbl <use  "beamericonarticle.pdf" >
<use  "beamericonarticle.pdf" > <use  "beamericonarticle.pdf" >
<use  "beamericonarticle.pdf" > <use  "beamericonarticle.pdf" >
<use  "beamericonarticle.pdf" >) [32] [33] (./demo.aux)

LaTeX Font Warning: Some font shapes were not available, defaults substituted.

 )
(see the transcript file for additional information)
Output written on demo.pdf (33 pages).
Transcript written on demo.log.

**Comment by matze** [comment]
Have you installed the font with the GNOME font viewer or by moving them to `~/.local/share/fonts`?

**Comment by Schaschka** [comment]
Manually moved them to ~/usr/local/share/texmf and ran texhash.

**Comment by matze** [comment]
Please install the fonts according to one of the methods described in the [Ubuntu Wiki](https://wiki.ubuntu.com/Fonts). The location you have given is wrong and supposed to keep TeX packages.

**Comment by Schaschka** [comment]
Thank you very much, this helps. Seems to look fine now, Fira works but I still  get some warnings:

Be aware that titleformat frame=allsmallcaps can lead to problems on input line 80.
Be aware that titleformat frame=allcaps can lead to problems on input line 93.
Font shape `EU1/FiraMono(0)/m/it' undefined using `EU1/FiraMono(0)/m/n' instead on input line 129.
Font shape `EU1/FiraMono(0)/bx/it' undefined using `EU1/FiraMono(0)/bx/n' instead on input line 129.
Token not allowed in a PDF string (Unicode):(hyperref) removing `\translate ' on input line 316.
Some font shapes were not available, defaults substituted.
