### ISSUE TITLE
Line's color

### ISSUE THREAD

**Issue by TalgatDa** [matze/mtheme#209]
Hello,
Could you tell me how to change color of the line on the title page?

**Comment by benjamin-weiss** [comment]
Have a look at the section **3.2 Color Customization** in the [manual](http://mirrors.ctan.org/macros/latex/contrib/beamer-contrib/themes/metropolis/doc/metropolistheme.pdf). You can easily set the color of the title separator by setting the corresponding beamer color.
```TeX
\setbeamercolor{title separator}{fg=...}
```

**Comment by TalgatDa** [comment]
Thanks a lot. Sorry for my inattention.
