### ISSUE TITLE
Subsection title allsmallcaps

### ISSUE THREAD

**Issue by alcarazr** [matze/mtheme#212]
Hi,

when setting `titleformat=allsmallcaps`, the format of subsection titles changes to `small caps`instead. Wouldn't be better if it changed to `allsmallcaps`as well?

Also, in the documentation, in section 8.2.2, the second `sectionpage`should be `subsectionpage` right?

Thanks!

**Comment by rchurchley** [comment]
Good points. I've created a pull request (#213) to address both of these issues. Thanks for bringing them up!
