### ISSUE TITLE
Long Section Titles with Linebreaks in metropolis beamer

### ISSUE THREAD

**Issue by virash** [matze/mtheme#215]
Hi,
I am unable to have multiple lined section titles in my presentation. 
Please let me know asap.
Regards

**Comment by matze** [comment]
Multi-line section titles have been working forever and have recently been changed to ragged right formatting with #185. Please be more specific with your problem. Ideally you would attach a minimum working example ASAP …

**Comment by matze** [comment]
Please reopen if necessary.
