### ISSUE TITLE
titleformat frame not recognized on framebreak numbers

### ISSUE THREAD

**Issue by unidesign** [matze/mtheme#216]
If I set `titleformat frame=allsmallcaps` and use a frame with `allowframebreaks` enabled only the title will be set in smallcaps but not the corresponding latin number (e.g. I,II,III). This looks very strange in my opinion.

The following code will show the problem if titleformat frame=allsmallcaps is set:
`\begin{frame}[allowframebreaks]{Title}
  foo
  \newpage
  foo  
  \newpage
  foo
  \newpage
  foo
\end{frame}`

[Here](http://tex.stackexchange.com/questions/8376/how-to-change-partitioned-frame-title-number-from-roman-to-arabic) is a hint how to solve the problem.

**Comment by matze** [comment]
> This looks very strange in my opinion.

Indeed it does but that's what numerals (no matter if roman or arab) look like when typeset in small caps with Fira. This is an issue with a long history (see #33 for first report) that lead to the current implementation allowing you to choose different frametitle styles. Besides that, I don't think we can do much about it.

**Comment by unidesign** [comment]
I'm not sure if you're right, atleast the following code shows that these numerals will have its own smallcaps also with Fira.

```\documentclass[10pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[ngerman]{babel}
\usepackage[T1]{fontenc}
\usepackage[sfdefault]{FiraSans}
%\usepackage[default]{sourcesanspro}
\begin{document}
Xx \romannumeral 3 \textsc{\romannumeral 3} III
\end{document}
```

My assumption was that the `scshape` command is not passed to beamer's `\insertcontinuationcount`.
I think it could be easily changed by override this command to use `scshape` if smallcaps are requested in options.

**Comment by matze** [comment]
Sorry about the confusion. You were right!

**Comment by unidesign** [comment]
No problem, thanks for having a look at it. Unfortunately we face new problems with the new solution.
With `allsmallcaps` all is fine now, with `smallcaps` we get smallcaps for the latin numerals. I think it's okay to make the latin numerals all smallcaps or allcaps in this case (maybe from designers view the allcaps are prefered here, from the logical view the allsmallcaps would be chosen).
But the cases `allcaps` and no option will fail for the latin numerals, it seems they are just lowercase now.
I think the easiest way would be to add an if-check as mentioned above and only change `frametitle continuation` if `allsmallcaps` is given and maybe the thing I wrote about `smallcaps`.
