### ISSUE TITLE
Insert background in title page

### ISSUE THREAD

**Issue by MatteoRagni** [matze/mtheme#222]
I had to add an Image as background (_not as logo_), only for title page. I solved the problem using this definition in the preamble:

``` latex
%% Title page background
\pgfdeclareimage[height=\paperheight]{title-background}{img/title-background.pdf}

\setbeamertemplate{title page}{%
  \begin{picture}(0,0)%
    \put(-29,-136){%
      \pgfuseimage{title-background}%
    }%
%  
    \put(0,-110.7){%
      \begin{minipage}[b][\paperheight]{\textwidth}
        \ifx\inserttitlegraphic\@empty\else\usebeamertemplate*{title graphic}\fi
        \vfill%
        \ifx\inserttitle\@empty\else\usebeamertemplate*{title}\fi
        \ifx\insertsubtitle\@empty\else\usebeamertemplate*{subtitle}\fi
        \usebeamertemplate*{title separator}
        \ifx\beamer@shortauthor\@empty\else\usebeamertemplate*{author}\fi
        \ifx\insertdate\@empty\else\usebeamertemplate*{date}\fi
        \vspace*{0.5cm}
        \ifx\insertinstitute\@empty\else\usebeamertemplate*{institute}\fi
        \vfill
        \vspace*{1mm}
      \end{minipage}
    }%
  \end{picture}
}
```

In practice I have used exactly what is **inside the inner theme**.
(the image was a drawing in Inkscape from beamer template page). 

**It is possible to create some sort of option?** Something like `\mthemebackground{...}` that acts only on the next slide.

source: [Creating a background image on the title page only using Beamer](http://tex.stackexchange.com/a/170118/63928)

**Comment by rchurchley** [comment]
Thanks for the suggestion. I think Beamer's built-in `\usebackgroundtemplate` does what you want it to, provided you enclose it and the `\maketitle` in braces to limit its scope:

```latex
{
  \usebackgroundtemplate{\includegraphics[width=\paperwidth]{title-background}}%
  \maketitle
}
```

See also https://tex.stackexchange.com/questions/7916/how-to-insert-a-background-image-in-a-beamer-frame.

Does this meet your needs?

**Comment by MatteoRagni** [comment]
Actually it works better than my first version.

Thank you, I think we can close this issue...
