### ISSUE TITLE
Option for an even lighter color scheme

### ISSUE THREAD

**Issue by rpls** [matze/mtheme#224]
In most situations the theme works very well, but I've recently held a presentation with sub-optimal lighting and an older projector which resulted in barely legible slides due to bad contrast. Using a while background helped. An option for this would be nice =) Maybe named "highcontrast".

**Comment by matze** [comment]
This is related to #208 I guess. However, I doubt just making the background pure white would've helped. A darker and thicker font would probably be a better solution, however making this an option will quickly get out ouf hand. I am actually thinking about distributing new color and font schemes with metropolis, e.g. ones that are focused on readability.

**Comment by matze** [comment]
A new high contrast color theme has been added with #244.
