### ISSUE TITLE
Is there a way to get section in footer?

### ISSUE THREAD

**Issue by nbecker** [matze/mtheme#227]
I'm using
\usetheme[sectionpage=progressbar,numbering=fraction]{metropolis}

I got the page number 1/N on the bottom right, I'd like to get section name into bottom left, but don't know how to do that.  Any hints?

**Comment by matze** [comment]
I am sorry but the theme is in certain ways (mostly conceptually and aesthetically) "biased", means we won't sacrifice decisions already made for maximum customizability. Long story short: it is not possible with a simple switch and probably won't in the foreseeable future.

**Comment by nbecker** [comment]
Actually, I found a simple solution:
\setbeamertemplate{frame footer}{\insertsectionhead}
