### ISSUE TITLE
Conflict between \usebackgroundtemplate and standout frame

### ISSUE THREAD

**Issue by zhouyisu** [matze/mtheme#229]
Hi there, I was trying to create frame with a picture as the background so I use:

> {\usebackgroundtemplate{
>         \begin{picture}(100,280)
>             \includegraphics[width=.7\paperwidth]{picture}
>         \end{picture}
> }%
> \begin{frame}[t]\frametitle{Example}
>     something
> \end{frame}
> \usebackgroundtemplate{...}

I notice once \usebackgroundtemplate was used, the standout command won't change the background color of that particular frame but only the text color. Any suggestions?

**Comment by benjamin-weiss** [comment]
Please always provide a complete [MWE](http://meta.tex.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-example-what-is-that). I cannot reproduce your problem. The following code works just fine for me.

```tex
\documentclass{beamer}
\usetheme{metropolis}

\begin{document}
{
  \usebackgroundtemplate{
  \begin{picture}(100,280)
  \includegraphics[width=.7\paperwidth]{example-image-a}
  \end{picture}
  }%
  \begin{frame}{Example}
  Example
  \end{frame}
}

\begin{frame}[standout]
  Standout Frame
\end{frame}

\end{document}
```

**Comment by zhouyisu** [comment]
Below is an example based on the demo.tex. I insert a \usebackgroundtemplate{...} before the conclusion section

> % -*- program: xelatex -*-
> \documentclass[10pt]{beamer}
> 
> \usetheme{metropolis}
> \usepackage{appendixnumberbeamer}
> 
> \usepackage{booktabs}
> \usepackage[scale=2]{ccicons}
> 
> \usepackage{pgfplots}
> \usepgfplotslibrary{dateplot}
> 
> \usepackage{xspace}
> \newcommand{\themename}{\textbf{\textsc{metropolis}}\xspace}
> 
> \title{Metropolis}
> \subtitle{A modern beamer theme}
> \date{\today}
> \author{Matthias Vogelgesang}
> \institute{Center for modern beamer themes}
> % \titlegraphic{\hfill\includegraphics[height=1.5cm]{logo.pdf}}
> 
> \begin{document}
> 
> \maketitle
> 
> \section{Introduction}
> 
> \begin{frame}[fragile]{Metropolis}
> 
>   The \themename theme is a Beamer theme with minimal visual noise
>   inspired by the \href{https://github.com/hsrmbeamertheme/hsrmbeamertheme}{\textsc{hsrm} Beamer
>   Theme} by Benjamin Weiss.
> 
>   Enable the theme by loading
> 
>   \begin{verbatim}    \documentclass{beamer}
>     \usetheme{metropolis}\end{verbatim}
> 
>   Note, that you have to have Mozilla's \emph{Fira Sans} font and XeTeX
>   installed to enjoy this wonderful typography.
> \end{frame}
> 
> 
> \usebackgroundtemplate{...}
> \section{Conclusion}
> 
> \begin{frame}{Summary}
> 
>   Get the source of this theme and the demo presentation from
> 
>   \begin{center}\url{github.com/matze/mtheme}\end{center}
> 
>   The theme \emph{itself} is licensed under a
>   \href{http://creativecommons.org/licenses/by-sa/4.0/}{Creative Commons
>   Attribution-ShareAlike 4.0 International License}.
> 
>   \begin{center}\ccbysa\end{center}
> 
> \end{frame}
> 
> \begin{frame}[standout]
>   Questions?
> \end{frame}
> 
> \appendix
> 
> \begin{frame}[fragile]{Backup slides}
>   Sometimes, it is useful to add slides at the end of your presentation to
>   refer to during audience questions.
> 
>   The best way to do this is to include the \verb|appendixnumberbeamer|
>   package in your preamble and call \verb|\appendix| before your backup slides.
> 
>   \themename will automatically turn off slide numbering and progress bars for
>   slides in the appendix.
> \end{frame}
> 
> \end{document}

**Comment by benjamin-weiss** [comment]
The problem is, that you overwrite the default definition of background canvas metropolis uses, which handles the background color. It is defined as 

```tex
\defbeamertemplate*{background canvas}{default}
{%
  \ifbeamercolorempty[bg]{background canvas}{}{\color{bg}\vrule width\paperwidth height\paperheight}%
}
```
in  `beamerouterthemedefault.sty`.

**Comment by zhouyisu** [comment]
Thanks for answering my question. Any recommendation how to reset the default background canvas mid-way in the presentation?

**Comment by benjamin-weiss** [comment]
You have two options: Either you put the frames where you want to use a custom background in brackets (option 1) or you load the the default template after changing the background with `\setbeamertemplate{background canvas}[default]` (option 2).

### Example:
```tex
\documentclass[10pt]{beamer}
\usetheme{metropolis}

\begin{document}

% --- OPTION 1 ---
{
  \usebackgroundtemplate{
  \begin{picture}(100,280)
  \includegraphics[width=.7\paperwidth]{example-image-a}
  \end{picture}
  }%

  \begin{frame}{Custom Background}
  \end{frame}
}

\begin{frame}[standout]
Default Background
\end{frame}

% --- OPTION 2 ---
\usebackgroundtemplate{
\begin{picture}(100,280)
\includegraphics[width=.7\paperwidth]{example-image-a}
\end{picture}
}%

\begin{frame}{Custom Background}

\end{frame}

\setbeamertemplate{background canvas}[default]

\begin{frame}[standout]
Default Background
\end{frame}

\end{document}
```

**Comment by zhouyisu** [comment]
Thank you @benjamin-weiss. My issue is solved.
