### ISSUE TITLE
Problem with Acrobat

### ISSUE THREAD

**Issue by bjonnh** [matze/mtheme#232]
I tried to open a pdf file using acrobat and some slides are not complete (seems to be due to italicized fonts from hyperref).

When compiling my file using xetex, I get errors about fonts not existing:

LaTeX Font Warning: Font shape `EU1/FiraMono(0)/m/it' undefined
(Font)              using `EU1/FiraMono(0)/m/n' instead on input line 79.

LaTeX Font Warning: Font shape `OT1/FiraSansLight(0)/m/n' undefined
(Font)              using `OT1/cmr/m/n' instead on input line 79.

Could this be due to that?

Here is my minimal sample file:
\documentclass{beamer}
\usetheme{metropolis}
\begin{document}
\begin{frame}
\begin{quote}
Text
\tiny \url{SomeURL}
Some text
\end{quote}
Other context
\end{frame}
\end{document}

In acrobat it just displays "Text". In Okular (Linux) it works perfectly)

I guess some font declaration are missing?

**Comment by bjonnh** [comment]
Seems that Fira Mono doesn't provide Italic, have to use another font here…

https://github.com/mozilla/Fira/issues/38

**Comment by matze** [comment]
Because this is a font issue I will close this for now.
