### ISSUE TITLE
How to change color of text in the standout frame?

### ISSUE THREAD

**Issue by sgargbugreporter** [matze/mtheme#234]
I am changing some colors in my beamer presentation as the following:

```
\definecolor{myGreen}{RGB}{30,98,56}
\definecolor{myGold}{RGB}{226,168,43}

\setbeamercolor{normal text}{fg=myGreen}
\setbeamercolor{alerted text}{fg=myGold}
\setbeamercolor{frametitle}{fg=myGold, bg=myGreen}

```
Everything works as I want when I compile [demo.tex](https://github.com/matze/mtheme/blob/master/demo/demo.tex). However, the following `standout` does not work as I want:

```
\begin{frame}[standout]
  Questions?
\end{frame}
```
This sets the text **Questions?** as white on a `myGreen` background. However, I want it to be `myGold` on a `myGreen` background. 

How to get that?

**Comment by rchurchley** [comment]
By default, `frametitle` and the standout frame both inherit from the `palette primary` colour scheme. Changing `frametitle` to gold on green will not change the standout colour, but setting
```latex
\setbeamercolor{palette primary}{fg=myGold, bg=myGreen}
```
should change both.

**Comment by sgargbugreporter** [comment]
Thank you. That does solve it!

**Comment by shibumi** [comment]
Thanks a lot @rchurchley you made my day :), I have been searching for this for a while.
