### ISSUE TITLE
Allow to define the width of the progress bar

### ISSUE THREAD

**Issue by nplatis** [matze/mtheme#237]
I propose that the width of the progress bar be selectable by the user via a simple command / option. I have discovered that the current progress bar is hardly visible when the projector used is not of very high resolution, so a wider line would better serve the purpose of the progress bar.

**Comment by benjamin-weiss** [comment]
Just to prevent confusion of inexperienced TeX users. Here is an example on how to set the line width of the title separator, section page separator and the progress bar using the new variables:

```TeX
\documentclass{beamer}
\usetheme[progressbar=frametitle]{metropolis}

\makeatletter
\setlength{\metropolis@titleseparator@linewidth}{2pt}
\setlength{\metropolis@progressonsectionpage@linewidth}{2pt}
\setlength{\metropolis@progressinheadfoot@linewidth}{2pt}
\makeatother

\title{A minimal example}
\date{\today}
\author{Matthias Vogelgesang}
\institute{Centre for Modern Beamer Themes}
\begin{document}
  \maketitle
  \section{First Section}
  \begin{frame}{First Frame}
    Hello, world!
  \end{frame}
\end{document}
```

**Comment by RobinTournemenne** [comment]
Unfortunately, your piece of code return me the error: with LaTex or XeLaTex 
Undefined control sequence. <argument> \metropolis@titleseparator@linewidth

**Comment by nplatis** [comment]
Here it is working fine. Is it possible that you are using an older version of the theme? The latest one is 1.2 from 2017/01/23 (you can see it in the documentation pdf).

**Comment by RobinTournemenne** [comment]
Firstly, thank you for your quick response time and, secondly, thank you for the good piece of advise. It solved the problem, very clever. (On mac, I used the application Tex live utility to find the version number of my metropolis theme).

**Comment by mcfefa** [comment]
This is very helpful for me, I am using a light color for these bars and so a thin bar is not visible enough. 

For people finding this issue in the future, this width is the vertical size of the bar, which you might think of as height.
