### ISSUE TITLE
Fira font not found

### ISSUE THREAD

**Issue by luigipertoldi** [matze/mtheme#240]
I know this is very common but I searched through all the opened or closed issues and still I am not able to solve the problem. I correctly installed the Fira fonts on my OSX but trying to compile the simple example (with or without the `\setfont` instructions)

```\documentclass{beamer}
\usetheme{metropolis}
\setsansfont[BoldFont={Fira Sans}]{Fira Sans Light}
\setmonofont{Fira Mono}
\title{A minimal example}
\date{\today} \author{Luigi}
\institute{Centre for Modern Beamer Themes} \begin{document}
\maketitle
\section{First Section}
\begin{frame}{First Frame}
FiraSans Light
\end{frame}
\end{document}
```

I get the fontspec error "font-not-found" on all the Fira fonts. The fonts work well in all my other applications. What's wrong?

**Comment by matze** [comment]
Are you using XeLaTeX or LuaTeX to compile your example?

**Comment by luigipertoldi** [comment]
XeLatex

**Comment by luigipertoldi** [comment]
Got it, the problem was that the Fira fonts were installed under `~/Library/Fonts` and fontspec was looking only at `/Library/Fonts`. Sorry for the useless opened issue.
