### ISSUE TITLE
Background of content pages

### ISSUE THREAD

**Issue by immothep** [matze/mtheme#241]
Hi Together

This is a very nice template it fits mostly to my need. I would like to set background color for some content pages. 

Would it be possible to add a `metroset` for this?

`\metroset{current frame background=red}`

**Comment by benjamin-weiss** [comment]
I don't think we should do that. This can be easily solved directly with beamer.

```TeX
\documentclass[10pt]{beamer}

\usetheme{metropolis}

\begin{document}
\begin{frame}{Normal background color}
  Content
\end{frame}

{
\setbeamercolor{background canvas}{bg=red}
\begin{frame}{Red background color}
  Content
\end{frame}
}

\begin{frame}{Normal background color}
  Content
\end{frame}

\end{document}
```

**Comment by immothep** [comment]
Wau, so easy and works. 😛

I didn't know that curly brackets limit's a setting to to one page only. Great. 

Thanks a lot Benjamin.
