### ISSUE TITLE
Emphasize not working?

### ISSUE THREAD

**Issue by alcarazr** [matze/mtheme#256]
Hi,

I'm using the latest versions of both `beamer` (v3.40) and `metropolis` (v2.2). I just tried to `\emph{}` a word but nothing happens. `\textit{}` works though. The following MWE:

```
%!TEX TS-program = xelatex
\documentclass{beamer}
\usetheme{metropolis}

\begin{document}
 \begin{frame}{Test}
  \emph{emphasized text}
  \textit{italic text}
 \end{frame}
\end{document}
```

gives this:

![test](https://cloud.githubusercontent.com/assets/9049533/22247062/26b36bbc-e238-11e6-8cac-12924ea7451f.jpg)

Any clue? Thanks!

**Comment by josephwright** [comment]
Probably https://github.com/wspr/fontspec/issues/254: for the next day or so try `\let\emph\textit`.

**Comment by alcarazr** [comment]
Thanks @josephwright. I'm sure `fontspec` will get updated in a breeze to fix this.

**Comment by matze** [comment]
Thanks for the quick reaction Joseph!

**Comment by wspr** [comment]
Sorry for the inconvenience! Update sent to CTAN.
