### ISSUE TITLE
Reducing size of footer

### ISSUE THREAD

**Issue by beojan** [matze/mtheme#259]
Is it possible to reduce the size of the footer on slides? As it is, it takes up a considerable amount of space, leaving vertical space limited for figures.

**Comment by kellertuer** [comment]
Actually, for me, that's more a feature than a bug of this theme. Use a plain/blank slide with fullscreen image if that's so important to show en detail; otherwise – less text/crowded slides fit better :)

**Comment by beojan** [comment]
That only works if there's sufficient vertical space.

I'm showing one or two (side by side) plots per slide with a title. The
footer currently takes up close to a third of the vertical space.

Sincerely,
Beojan Stanislaus

**Comment by kellertuer** [comment]
Do you have an MWE (minimal working example)? Because I can't see “loosing” a third of the height to the footer on my slides.

**Comment by beojan** [comment]
On Tuesday, 14 February 2017 21:02:20 GMT Ronny Bergmann wrote:
> Do you have an MWE (minimal working example)? Because I can't see “loosing”
> a third of the height to the footer on my slides.

Try using the Solarized color scheme, which has a different color for the 
footer. Also note that I tend to use 16:9 slides.


Sincerely,
Beojan Stanislaus

**Comment by benjamin-weiss** [comment]
First of all you can easily just remove the footline like this:
```TeX
\setbeamertemplate{footline}{}
```
If you want to keep the footline I have two suggestions. You could reduce the fontsize used in the footline. The height of the footline depends on it.
```TeX
\setbeamerfont{page number in head/foot}{size=\tiny}
```
If this still doesn't satisfy your needs, you can use the footline definition in `metropolis` as a basis and redefine it. The definition is as follows:
```TeX
\setbeamertemplate{footline}{%
  \begin{beamercolorbox}[wd=\textwidth, sep=3ex]{footline}%
    \usebeamerfont{page number in head/foot}%
    \usebeamertemplate*{frame footer}
    \hfill%
    \usebeamertemplate*{frame numbering}
  \end{beamercolorbox}%
}
```
Just reduce the `sep` parameter to your liking.

@matze As I don't think we should add any option or make it any easier to reduce the height of the footline, this issue should be closed.

**Comment by matze** [comment]
I agree with the others, this is a wontfix because 1) the general theme is designed the way it is and 2) there are ways to change the footer (nicely shown by Benjamin) without bloating the theme even more.
