### ISSUE TITLE
The section page and TikZ external

### ISSUE THREAD

**Issue by kellertuer** [matze/mtheme#260]
I really like to use Metropolis since I discovered it. However, I have a few graphics I use in my talks, that are better to be prerendered and included, which is nicely done by the TiKz library external.

However when I activate external, every sectionpage produces also an extra externalized pdf (of just the line). Would it be possible to add an `\tikzexternaldisable` before and a `\tikzexternalenable`after each tikzpicture the theme generates? I know, that this can be done, I did it myself a while ago;
so this might also be seen as a reminder for myself ;) I am just not yet used to `dtx` files and haven't found my old files with the fix (in my old theme a while ago).

Best,
Kellertuer.

**Comment by kellertuer** [comment]
Hi, thanks for the quick fix, the one point to keep in mind is, that if you don't load the external library of TikZ your solution will throw an error, because then the `\tikzexternaldisable` and enable-commands are not defined. That's what I meant with i'll have to look for that, i'm sorry, that I wasn't more clear in the first place.

**Comment by matze** [comment]
Yep, you are right. I think we could either define those to NOPs if they don't exist or prematurely load `external`. Hmm ...

**Comment by kellertuer** [comment]
I still can't find my old code, but I think I had something to check whether `external` was loaded, stored that value in a boolean and sorrounded both commands by an if. Which is a little longer that your NOPs Idea. I wouldn't just prematurely load `external` though.
