### ISSUE TITLE
Check for TikZ external library seems to be a bit redundant.

### ISSUE THREAD

**Issue by yudai-nkt** [matze/mtheme#261]
In the current `master`, you have the following lines ([L135–L136][ifx-fi branch]):

```latex
\ifx\tikzexternalenable\undefined \newcommand{\tikzexternalenable}{} \fi
\ifx\tikzexternaldisable\undefined \newcommand{\tikzexternaldisable}{} \fi
```

These fallbacks are equivalent to

```latex
\providecommand{\tikzexternalenable}{}
\providecommand{\tikzexternaldisable}{}
```

I don't get why you used the `\ifx` branches. Just out of curiosity, but are there any particular reasons?

[ifx-fi branch]: https://github.com/matze/mtheme/blob/c13b01f948b8fefef72737f58b8c24f8eb1453ad/source/beamerthememetropolis.dtx#L135-L136

**Comment by yudai-nkt** [comment]
I've just prepared simpler fallbacks at yudai-nkt/mtheme@ca2c9ed9fe56fb52e907d039636411e54f0efa50. I'm ready to submit a PR if you agree to this change.

**Comment by matze** [comment]
Go ahead :+1:

**Comment by yudai-nkt** [comment]
Done in #262! :+1:
