### ISSUE TITLE
Adapt greek fonts for math usage

### ISSUE THREAD

**Issue by matze** [matze/mtheme#263]
According to Florian Frank, this theme – among others – has issues with greek math symbols which just do not fit their roman counterparts.

* Greek lowercase letters have a varying thickness contrary to Fira
* Greek uppercase letters are not set in italic

He proposes to add
```latex
\usepackage[sfdefault,scaled=0.90,lining]{FiraSans} %% TODO We need to decrease the size of the upper greek letters.
\usepackage[slantedGreek]{newtxsf}
```
which gives somewhat consistent results with roman letters. This example

```latex
\newcommand*{\abc}{abcdefghijklmnopqrstuvwxyz}
\newcommand*{\ABC}{ABCDEFGHIJKLMNOPQRSTUVWXYZ}
\newcommand*{\abcGreek}{\alpha\beta\gamma\delta\epsilon\varepsilon\zeta\eta\theta\vartheta\iota\kappa\lambda\mu\nu\xi\pi\rho\varrho\sigma\varsigma\tau\upsilon\phi\varphi\chi\psi\omega}
\newcommand*{\ABCGreek}{\Delta\Lambda\Xi\Pi\Sigma\Upsilon\Phi\Psi\Omega}
\newcommand*{\abcABC}{\abc\ABC}
\newcommand*{\abcABCGreek}{\abcGreek\ABCGreek}
\newcommand*{\onetwothree}{1234567890}
\begin{frame}{Font test}
\textbf{Text, normal}:\\
\abcABC\onetwothree
\\[0.5\baselineskip]
\textbf{Math, normal}:\\
$\abcABC\onetwothree$\\
$\abcABCGreek$
\\[0.5\baselineskip]
\textbf{Math, boldsymbol}:\\
$\boldsymbol{\abcABC\onetwothree}$\\
$\boldsymbol{\abcABCGreek}$
\\[\baselineskip]
$A\Lambda G\Omega$\\
$a\alpha b\beta d\delta e\epsilon$
\end{frame}
```
looks like

![orig](https://cloud.githubusercontent.com/assets/115270/23310098/98612b1e-fab1-11e6-886f-4189d942f1ea.png)

in the current version and like

![modified](https://cloud.githubusercontent.com/assets/115270/23310106/9fec3ec8-fab1-11e6-9424-2a0d24de3b68.png)

with the proposed changes.

**Comment by benjamin-weiss** [comment]
I don't think in any way this is the way to go. It completely changes the font weights of normal text by using the `FiraSans` package and is still only a halfhearted solution which uses another font. So I'm definitiv against putting this solution into the theme.

By the way in regular text one can just use the unicode symbols directly (example also included in the source below). 

As I already mentioned in former discussions about the fonts in equations in the theme, I just gave up using a sans-serif font in beamer presentations, as I couldn't find a solution which works as good (in all cases) as just using Computer Modern Serif. However, as a starting point for somebody who runs into this problem the following code could be helpful. **But:** I would not include this solution in the theme either, as `mathspec` is XeLaTeX only!

```TeX
\documentclass{beamer}

\usetheme{metropolis}
\usefonttheme{professionalfonts}
\usepackage{mathspec}
\setsansfont[BoldFont={Fira Sans}, Numbers={OldStyle}]{Fira Sans Light}
\setmathsfont(Digits,Latin,Greek)[Numbers={Lining,Proportional}]{Fira Sans Light}

\newcommand*{\abc}{abcdefghijklmnopqrstuvwxyz}
\newcommand*{\ABC}{ABCDEFGHIJKLMNOPQRSTUVWXYZ}
\newcommand*{\abcGreek}{\alpha\beta\gamma\delta\epsilon\varepsilon\zeta\eta\theta\vartheta\iota\kappa\lambda\mu\nu\xi\pi\rho\varrho\sigma\varsigma\tau\upsilon\phi\varphi\chi\psi\omega}
\newcommand*{\ABCGreek}{\Delta\Lambda\Xi\Pi\Sigma\Upsilon\Phi\Psi\Omega}

\begin{document}

\begin{frame}{Normal Text}
  \abc\\
  \ABC\\
  Α Β Γ Δ Ε Ζ Η Θ Ι Κ Λ Μ Ν Ξ Ο Π Ρ ϴ Σ Τ Υ Φ Χ Ψ Ω\\
  α β γ δ ε ζ η θ ι κ λ μ ν ξ ο π ρ ς σ τ υ φ χ ψ ω ∂ ϵ ϑ ϰ ϕ ϱ ϖ\\
\end{frame}

\begin{frame}{Math}
  \[\abc\]
  \[\ABC\]
  \[\abcGreek\]
  \[\ABCGreek\]
\end{frame}

\end{document}
```

**Comment by alcarazr** [comment]
I agree with @benjamin-weiss that the suggestion of Florian Frank changes too much the font weights when using the `Fira Sans` package. By the way, the first `.png` uploaded by @benjamin-weiss looks like a `.gif`, but switches too fast between both cases. Even if it's `XeLaTeX` only, I would suggest to include that solution in the theme, just checking if the user is using `XeLaTeX` (I guess that check is already donde for choosing which font the theme will use).

**Comment by benjamin-weiss** [comment]
Strange, I didn't have this behavior of switching images with Chrome on macOS. But looking at it on my mobile right now I experience the same. I will fix that.

Another option would be to add my solution to the documentation. A XeLaTeX only solution as part of the theme could be too confusing for the users.

**Comment by alcarazr** [comment]
Just FYI @benjamin-weiss, the first `.png` you attached still switches between both images as if it was a `.gif`.

**Comment by benjamin-weiss** [comment]
Thanks for the reminder, it should be fine now.

**Comment by benjamin-weiss** [comment]
@matze What's your take on this issue?

**Comment by matze** [comment]
I think you made good points first to not include the proposed changes (way too different) as well as keeping your XeTeX-specific solution out of the theme. I think that's again something we cannot do about anyway but have to rely somewhat on improved Fira support.

Anyway, it's good to keep this issue in mind and have the discussion around for further reference. But I'll close this for now.
