### ISSUE TITLE
Embedding video in Slide

### ISSUE THREAD

**Issue by ankur92** [matze/mtheme#264]
Hi, 

I am trying to embed a .avi file in my slide using multimedia package but it's not happening. 
Snippet of the code and I have define the \usepackage{mutlimedia} in the beginning
\movie[width=3cm,height=2cm,poster]{}{Images/Phy335/modehopping.avi}

Any suggestions?

**Comment by cjue** [comment]
Are you using XeLaTeX or LuaLaTeX?

To my knowledge, the "\movie" command from the multimedia package is incompatible with XeLaTeX.
Source: https://bitbucket.org/rivanvx/beamer/issues/135/xelatex-and-multimedia-package-not

It works fine with LuaLaTeX, though. If you have problems compiling with lualatex, try the "providecommand" fix from issue #218.

**Comment by benjamin-weiss** [comment]
This does not seem like a `metropolis` related issue. Does this problem really only occur if you are using the `metropolis` theme?

**Comment by matze** [comment]
Definitely not metropolis related and @cjue gave a good workaround anyway.

**Comment by ankur92** [comment]
Hi, 

Sorry for the late reply. I am using XeLateX on Windows 10. I tried LuLa as well but it didn't work. I also tried with multimedia on Overleaf but it didn't add the video. I finally found a post which used media9 package to embed the video. 

@benjamin-weiss Yes, I have used with other beamer template and it worked fine.

**Comment by cjue** [comment]
@ankur92: Yes, media9 appears to be the preferred way to embed videos on Windows for Adobe Reader. It works with XeLaTeX and LuaLaTeX. 

LuaLaTeX and the multimedia package have the advantage of also working on Linux in Okular.
