### ISSUE TITLE
Overfull when using Unicode subscript numbers (₂)

### ISSUE THREAD

**Issue by willismonroe** [matze/mtheme#265]
This is my first time using metropolis much less beamer for a presentation, so excuse my ignorance.  I'm trying to use subscripts on normal characters (not in an equation) i.e. "The sign: e₂".  My first issue is that these characters don't render in the output PDF, even though the Fira font has the glyphs.  Secondly, if I try to put them in using the _{} notation it consistently gives overfull \hbox and \vbox errors.  I found that "The sign: e\textsubscript{2}" does work, but I'd rather just use the Unicode characters as I've got them set to easy key-combos.

Also as an aside, is there any way to specify another OpenType font for use with the metropolis theme, this is probably super basic, but I'm not finding anything that works.

**Comment by benjamin-weiss** [comment]
First of all: You should always provide a [MWE](http://meta.tex.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-example-what-is-that) if you have a problem. This makes it easier for others to help you. Unfortunately I cannot reproduce your problem. The following code compiles without a problem on my machine with XeLaTeX and LuaTeX:
```TeX
\documentclass{beamer}
\usetheme{metropolis}
\begin{document}
  \begin{frame}{Subscript numbers}
    The sign: e₂
  \end{frame}
\end{document}
```
Maybe the encoding of your file is messed up?

To answer your other question: Have a look at the `metropolis` [documentation](http://mirrors.ctan.org/macros/latex/contrib/beamer-contrib/themes/metropolis/doc/metropolistheme.pdf) in section 3.3.

**Comment by willismonroe** [comment]
Got it, yeah sorry should have provided more detail.  I'm on Ubuntu 16.10 running the standard packaged versions of latex and texlive (and its packages).  I'm editing in LaTeXila and compiling with LuaTeX.

Disregard the title I gave this issue, I didn't really understand the problem initially.  Now I see it more as a font rendering problem in the PDF, which is not at all the themes issue.  For me, the subscript 2 (₂) doesn't render in the font if I use that glyph in the .tex file, where as the explicitly type \textsubscript{2} does render.   I suspect some googling about this issue more broadly in LaTeX will turn up an answer.
