### ISSUE TITLE
Match bullets with text color on "standout" slides

### ISSUE THREAD

**Issue by alhirzel** [matze/mtheme#267]
I am using standout slides as a flow-breaker and find it is helpful to put bullet lists on them. Therefore, I think the bullet color should match the text color for these slides. My current workaround is to override the `local structure` color:

```latex
\begingroup
\setbeamercolor{local structure}{fg=normal text.bg}
\begin{frame}[standout]
	\flushleft
	Agenda
	\begin{itemize}
	\item<2-> Item one
	\item<3-> Item two
	\item<4-> Item three
	\item<5-> Item four
	\end{itemize}
\end{frame}
\endgroup
```

**Comment by matze** [comment]
Thanks for reporting the issue!
