### ISSUE TITLE
Does metropoils support chinese

### ISSUE THREAD

**Issue by gaufung** [matze/mtheme#268]
I want to use this theme to prepare the graduation slide. But I'm not able to compile it when I use chinese. I use ctex package to handle the chinese typesetting. 

> \documentclass{beamer}
> \usepackage[fontset=mac, UTF8]{ctex}
> \usetheme{metropolis}

what can I do?

**Comment by benjamin-weiss** [comment]
First, in the future please provide a full [MWE](https://tex.meta.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-example-what-is-that). This makes it easier for others to help you. You should also mention which engine you are using (pdfTeX, XeLaTex, LuaTeX) and what error messages you are getting. Just saying that you are not able to compile something is not very helpful.

Second, I don't think this is a `metropolis` related problem. But, I'm obviously no expert on using TeX with Chinese. Nevertheless, the following example compiles fine for me using XeLaTeX.

```TeX
\documentclass{beamer}
\usepackage[fontset=mac, UTF8]{ctex}
\usetheme{metropolis}

\begin{document}
  \begin{frame}{高峰}
    高峰
  \end{frame}
\end{document}
```
![chinese](https://cloud.githubusercontent.com/assets/9158719/24589001/2b2a370e-17d3-11e7-9b19-efcb6a894e60.png)

And as described in [this](http://tex.stackexchange.com/questions/222980/how-to-use-chinese-with-lualatex) Stackexchange question, it seems like `ctex` does not support LuaTeX. So if you want to use LuaTeX you probably need to follow the instructions given in the answer there.

**Comment by matze** [comment]
> Second, I don't think this is a metropolis related problem.

This.
