### ISSUE TITLE
Remove lines below block titles

### ISSUE THREAD

**Issue by frankdilo** [matze/mtheme#269]
Hi, thanks for this wonderful theme.

I am trying to use blocks without titles, to achieve this effect.

<img width="639" alt="screen shot 2017-04-07 at 12 32 40" src="https://cloud.githubusercontent.com/assets/715405/24796694/59d080fe-1b8e-11e7-9fb8-fcf3365aaf46.png">

But, as you can see, there is this white line above the body of the block that is really bothering me.

<img width="605" alt="screen shot 2017-04-07 at 12 32 55" src="https://cloud.githubusercontent.com/assets/715405/24796712/6c52626a-1b8e-11e7-963e-c7aaf360a59c.png">

Is there an easy way to remove it?

**Comment by benjamin-weiss** [comment]
Please provide a [MWE](https://tex.meta.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-example-what-is-that).

**Comment by frankdilo** [comment]
Here is a MWE:
```latex
\documentclass{beamer}
\usetheme{metropolis}           % Use metropolis theme

% my custom code
\usepackage{tikz}
\setbeamertemplate{blocks}[rounded][shadow=false]
\addtobeamertemplate{block begin}{\pgfsetfillopacity{0.6}}{\pgfsetfillopacity{1}} 
\addtobeamertemplate{block example begin}{\pgfsetfillopacity{0.7}}{\pgfsetfillopacity{1}}


\title{A minimal example}
\date{\today}
\author{Matthias Vogelgesang}
\institute{Centre for Modern Beamer Themes}
\begin{document}
    {
    \usebackgroundtemplate{\tikz\node[opacity=0.2,inner sep=0]
   {\includegraphics[height=\paperheight,width=\paperwidth]{/Users/frankdilo/Tesi/thesis-writing/presentation/images/mab_slot.jpg}};} 
    \begin{frame}
        
        \begin{block}{}
	        This is a block without a title
        \end{block}
    \end{frame}
    }
\end{document}
```

This produces:

![image](https://cloud.githubusercontent.com/assets/715405/24799433/58fd2a6c-1b9b-11e7-8c95-e200a5773d57.png)

Which has that white line above the body of the block.

![image](https://cloud.githubusercontent.com/assets/715405/24799445/675efe46-1b9b-11e7-9330-3b2ffcbaef55.png)

**Comment by benjamin-weiss** [comment]
Beamer boxes are not very nice to handle. Especially the rounded beamer box is quiet complicated. So redefining it without a title would be kind of a mess. So I recommend, that you use the `tcolorbox` package. Here is an example:

```TeX
\documentclass{beamer}
\usetheme{metropolis}

% --- define custom box ---
\usepackage[most]{tcolorbox}
\newtcolorbox{titlelessblock}{
  enhanced,
  boxsep=0.25ex,
  arc=1.25ex,
  opacityframe=.6,
  opacityback=.6,
  colback=white,
  colframe=white,
  boxrule=0pt
}

\begin{document}
{
  \usebackgroundtemplate{\tikz\node[opacity=0.2,inner sep=0]
   {\includegraphics[height=\paperheight,width=\paperwidth]{example-grid-100x100bp}};}
  \begin{frame}
    \begin{titlelessblock}
      This is a block without a title
    \end{titlelessblock}
  \end{frame}
}
\end{document}
```

**Comment by frankdilo** [comment]
Thanks @benjamin-weiss, this is exactly what I needed. Cheers.

**Comment by benjamin-weiss** [comment]
You are welcome.
