### ISSUE TITLE
Fira Font not loading on Mac with pdflatex

### ISSUE THREAD

**Issue by dennis-tra** [matze/mtheme#270]
Hi there,

first of all, thank you for this awesome looking theme!

Unfortunately I can't get it to work properly with those Fira fonts.
I used the minimal example:
```latex
\documentclass{beamer}
\usetheme{metropolis} % Use metropolis theme
\title{Metropolis}
\subtitle{A modern beamer theme}
\date{\today}
\author{Matthias Vogelgesang}
\institute{Centre for Modern Beamer Themes}
\begin{document}
	\maketitle
	\section{First Section}
	\begin{frame}{First Frame}
		Hello, world!
	\end{frame}
\end{document}
````
Which produces this:

![screen shot 2017-04-07 at 13 07 23](https://cloud.githubusercontent.com/assets/11836793/24797792/27a202e2-1b93-11e7-8ea8-2532d0032633.png)

After inserting `\usepackage[sfdefault]{FiraSans}` after `\usetheme{metropolis}` it looks like this:
![screen shot 2017-04-07 at 13 08 01](https://cloud.githubusercontent.com/assets/11836793/24797820/3ef257c6-1b93-11e7-952f-875f7f76c6fe.png)

But if you look carefully on the [demo pdf](http://ctan.space-pro.be/tex-archive/macros/latex/contrib/beamer-contrib/themes/metropolis/demo/demo.pdf) you can see that the title is not as bold, as in the second picture:
![screen shot 2017-04-07 at 13 09 08](https://cloud.githubusercontent.com/assets/11836793/24797844/681840fc-1b93-11e7-87e2-5870e2097a9f.png)

I'm on MacOS sierra using pdflatex. I already installed the otf fonts from Firefox into macs font book. No difference. In the manual it says, that it should automatically pick the Fira font, so the extra line `\usepackage[sfdefault]{FiraSans}` shouldn't be necessary. Am I missing something?

I hope I gave all information needed.

Thanks in advance,
Dennis

**Comment by benjamin-weiss** [comment]
> I'm on MacOS sierra using pdflatex.

You have to use `XeLaTeX` or `LuaTeX` to get an output with the Fira Font. We use the `fontspec` package for that, which does not work with `pdfLaTeX`. Maybe the documentation is not explicit enough there.

**Comment by dennis-tra** [comment]
Oh no, you're right. I don't think the documentation is not explicit enough. Thank you!
