### ISSUE TITLE
Numbered (sub)sections in toc and (sub)sectionpage

### ISSUE THREAD

**Issue by Flowlishes** [matze/mtheme#271]
Hi,
I got the subsectionpages with the command:
`\usetheme[subsectionpage=progressbar]{metropolis}`
and the subsections into the toc by removing
`\tableofcontents %[hideallsubsections]`.

Is it possible to get numbered sections and subsections on their own pages, as well as numbered subsections in the table of contents.

Thank you very much.

**Comment by benjamin-weiss** [comment]
Do you mean like this?

![numbered_toc](https://cloud.githubusercontent.com/assets/9158719/24839407/ffff21de-1d59-11e7-8934-0d541621d75b.png)
![numbered_sectionpage](https://cloud.githubusercontent.com/assets/9158719/24839408/04185f06-1d5a-11e7-8f99-1045e6562377.png)

```TeX
\documentclass{beamer}
\usetheme[subsectionpage=progressbar]{metropolis}
\setbeamertemplate{section in toc}[sections numbered]
\setbeamertemplate{subsection in toc}[subsections numbered]

\makeatletter
\setbeamertemplate{section page}{
  \centering
  \begin{minipage}{22em}
    \raggedright
    \usebeamercolor[fg]{section title}
    \usebeamerfont{section title}
    \thesection.~\insertsectionhead\\[-1ex]
    \usebeamertemplate*{progress bar in section page}
    \par
    \ifx\insertsubsectionhead\@empty\else%
      \usebeamercolor[fg]{subsection title}%
      \usebeamerfont{subsection title}%
      \thesubsection.~\insertsubsectionhead
    \fi
  \end{minipage}
  \par
  \vspace{\baselineskip}
}
\makeatother

\begin{document}
\begin{frame}{TOC}
  \tableofcontents
\end{frame}
\section{Section}
\subsection{Subsection}
\begin{frame}{Frame}
  Content
\end{frame}
\subsection{Subsection}
\begin{frame}{Frame}
  Content
\end{frame}
\section{Section}
\subsection{Subsection}
\begin{frame}{Frame}
  Content
\end{frame}
\subsection{Subsection}
\begin{frame}{Frame}
  Content
\end{frame}
\end{document}
```

**Comment by Flowlishes** [comment]
Is it possible to get "1.1 subsection" below the "1. section" on the subsectionpage as well? The rest is perfect. Thank you

**Comment by benjamin-weiss** [comment]
Sure. Just replace:

```TeX
\thesubsection.~\insertsubsectionhead
```

with 

```TeX
\thesection.\thesubsection~\insertsubsectionhead
```

**Comment by Flowlishes** [comment]
Thank you very much

**Comment by MichaelTettehK** [comment]
@benjamin-weiss  @Flo-Wo  How can I indent the subsection numbering on the table of contents page.
