### ISSUE TITLE
pdf image with transparent background is displayed as dark theme color background.

### ISSUE THREAD

**Issue by nzer0** [matze/mtheme#277]
When I insert an image of pdf format which has transparent background,
it is displayed with the dark theme color background.

<img width="435" alt="image" src="https://cloud.githubusercontent.com/assets/2021812/25467499/817d7cc2-2b49-11e7-9beb-d6b30d8e581f.png">

I would like to make the background white or the same as the slide background color.
How can I do that?

**Comment by matze** [comment]
Could it be related to #123? Please check if it works with other PDF viewers or if other PDFs with transparent backgrounds have the same problem. I haven't seen this problem yet and I regularly display transparent PDFs.

**Comment by matze** [comment]
I will close this issue for now. If you still have a problem, don't hesitate to respond and re-open.
