### ISSUE TITLE
Using subfig leads to oversized labels, even with \usepackage[font=scriptsize]{subfig}

### ISSUE THREAD

**Issue by pakitochus** [matze/mtheme#279]
When using the subfig package with the metropolis theme, and using scriptsize for captions, as recommended in help (`\usepackage[font=scriptsize]{subfig}`), it leads to oversized labels (normal size) in contrast to captions (script size or any other selected), with its corresponding underused space. See figure for example. 

MWW:

```latex
% !TEX TS-program = xelatex
\documentclass[10pt]{beamer}

\usetheme[progressbar=foot,sectionpage=none,subsectionpage=progressbar,block=fill]{metropolis}
\usepackage[font=scriptsize]{subfig}

\usepackage[scale=2]{ccicons}

\usepackage{xspace}


\begin{document}
	\begin{frame}{Frame sample}
	\begin{figure}
		\centering
		\subfloat[Image A]{\includegraphics[width=0.4\textwidth]{example-image-a}\label{fig:ex_a}}
		\subfloat[Image B]{\includegraphics[width=0.4\textwidth]{example-image-b}\label{fig:ex_b}}\\
		\subfloat[Image C]{\includegraphics[width=0.4\textwidth]{example-image-c}\label{fig:ex_c}}
		\caption{Image samples.}
		\label{fig:samples}
	\end{figure}
\end{frame}
\end{document}
```

**Comment by benjamin-weiss** [comment]
Even though this is not a `metropolis` related question, here is a solution. Just adjust the labelfont size corresponding to the label text font size:
```
\usepackage[font=scriptsize,labelfont={scriptsize,bf}]{subfig}
```

**Comment by benjamin-weiss** [comment]
@matze Can be closed.

**Comment by pakitochus** [comment]
Thanks, that helped a lot. Sorry for including a question non-related to metropolis.
