### ISSUE TITLE
Indent of subsections in the toc

### ISSUE THREAD

**Issue by Flowlishes** [matze/mtheme#282]
Hallo,

bisher habe ich folgende Befehle, die das Inhaltsverzeichnis betreffen, in meiner Datei:

`\usetheme[outer/progressbar=foot, subsectionpage=progressbar]{metropolis}
\setbeamertemplate{section in toc}[sections numbered]
\setbeamertemplate{subsection in toc}[subsections numbered]
\makeatletter
`
Gibt es eine einfache Möglichkeit die subsections um einen bestimmten Abstand (z.B. `$\quad$`) im Inhaltsverzeichnis einzurücken?

Vielen Dank.

**Comment by benjamin-weiss** [comment]
Even though I speak german: Please translate your question to english!

**Comment by Flowlishes** [comment]
Hello,

is there a possibility to indent subsections in the toc with a specific distance (e.g `$\quad$`)?

I already got the following commands in my template:

`\usetheme[outer/progressbar=foot, subsectionpage=progressbar]{metropolis}
\setbeamertemplate{section in toc}[sections numbered]
\setbeamertemplate{subsection in toc}[subsections numbered]
\makeatletter
`

Thank you very much.

**Comment by benjamin-weiss** [comment]
This is not a metropolis related question, but here you go. You have to manually redefine the `subsecion in toc` template.

```TeX
\documentclass{beamer}
\usetheme[outer/progressbar=foot, subsectionpage=progressbar]{metropolis} 
\setbeamertemplate{section in toc}[sections numbered]
%%%%%%
\setbeamertemplate{subsection in toc}
{\leavevmode\leftskip=2em\rlap{\hskip-2em$\quad$\inserttocsectionnumber.\inserttocsubsectionnumber}$\quad$\inserttocsubsection\par}
%%%%%%
\begin{document}
\begin{frame}{Table of contents}
  \tableofcontents
\end{frame}
\section{Section 1}
\subsection{Subsection 1}
\begin{frame}{Frame 1}
	Content 1
\end{frame}
\subsection{Subsection 2}
\begin{frame}{Frame 2}
	Content 2
\end{frame}
\end{document}
```

**Comment by Flowlishes** [comment]
Thank you very much.
