### ISSUE TITLE
Definition of the default background colour

### ISSUE THREAD

**Issue by luigipertoldi** [matze/mtheme#283]
What if I want to use the very-light grey background colour (for example when filling objects in a TikZ-picture)? I couldn't find his definition in the code...

PS: Great beamer theme!

**Comment by benjamin-weiss** [comment]
The light grey is defined as `black!2`. But it probably makes more sense to make your tikz picture dependent on the beamer color `normal text`.

```TeX
\documentclass{beamer}
\usetheme{metropolis}
\begin{document}
\begin{frame}{Use metropolis colors in tikz}
\begin{tikzpicture}
  \usebeamercolor{normal text} % actually not really necessary in this case as it is the active color anyways
  \filldraw [fill=bg, draw=fg, very thick] (0,0) circle [radius=2cm];
\end{tikzpicture}
\end{frame}
\end{document}
```

**Comment by Nadrieril** [comment]
For anyone coming here who wants to know what color that is (for example to use it as background in included images), it's #FAFAFA
