### ISSUE TITLE
Feature request: \setscfont?

### ISSUE THREAD

**Issue by mandarm** [matze/mtheme#289]
Would it make sense / be possible to provide a \setscfont to set the font to be used for smallcaps? This might be useful if I wanted to use some font other than Fira (one that does not support smallcaps, say Roboto) for the frame body, but would still like to use Fira (with the (all)smallcaps option) for the frame title.

**Comment by benjamin-weiss** [comment]
I think the `fontspec` commands are sufficient to do something like this. I suppose for the example you described something like
```TeX
\setsansfont[SmallCapsFont={Fira Sans}, SmallCapsFeatures={Letters=SmallCaps}]{Roboto}
```
should work. So there is no need for a special `metropolis` command in my opinion.

**Comment by mandarm** [comment]
Perfect, thanks! Closing..
