### ISSUE TITLE
Bibliography entry colours in standout frames

### ISSUE THREAD

**Issue by logological** [matze/mtheme#296]
I occasionally want to use Biblatex's `\fullcite` command in a standout frame—for example, if the standout frame contains a quotation and I want to show the full citation underneath it.  While most text on the standout frame gets printed in the foreground colour, the output of `\fullcite` is printed in the background colour, rendering it invisible.  Here is a minimal example showing the problem:

```latex
\documentclass{beamer}
\usetheme{metropolis}
\usepackage{biblatex}
\addbibresource{\jobname.bib}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@inproceedings{bar2017,
  author       = {Foo Bar},
  title	       = {Baz},
  booktitle    = {Quux},
  year         = {2017},
}
\end{filecontents}

\begin{document}
\begin{frame}[standout]
  ``Foo bar baz.'' % This prints correctly

  \fullcite{bar2017} % This doesn't
\end{frame}

\end{document}
```

The problem, I think, is that Beamer provides variables for controlling the colour of bibliography entries, but Metropolis neglects to set them to something sensible for use on the background colour of standout slides.  Entering the following inside the standout frame, before `\fullcite`, makes the bibliography entry visible again:

```latex
\setbeamercolor{bibliography entry author}{fg=white}
\setbeamercolor{bibliography entry title}{fg=white}
\setbeamercolor{bibliography entry location}{fg=white}
\setbeamercolor{bibliography entry note}{fg=white}
```

Rather than the user remembering to do this on every standout frame, I wonder whether this is something that Metropolis should be doing automatically.

**Comment by matze** [comment]
Thanks for the report and possible solution!
