### ISSUE TITLE
Backgound color of "plain" frame

### ISSUE THREAD

**Issue by mghassany** [matze/mtheme#300]
Hi, thanks for this amazing template.

I want to know how to modify the color of the background when i use \plain{...}

Thanks in advance

**Comment by mghassany** [comment]
It's ok i did it using 

```
\setbeamercolor{palette primary}{
  fg=..,bg=..
}
```

**Comment by mghassany** [comment]
but the page number is shown.. it was hidden whith the default configuration.

**Comment by benjamin-weiss** [comment]
You shouldn't use the deprecated `\plain{...}` command. Instead you should use the `standout` frame. With respect to the page number have a look here: https://github.com/matze/mtheme/issues/272

Here is an example:
```TeX
\documentclass{beamer}
\usetheme{metropolis}
\begin{document}
{
\setbeamercolor{palette primary}{fg=black,bg=lightgray}
\begin{frame}[plain, standout]
Plain Frame
\end{frame}
}
\end{document}
```
