### ISSUE TITLE
Fails to compile with beamer 3.45

### ISSUE THREAD

**Issue by xsmile** [matze/mtheme#303]
Metropolis fails to compile with beamer version 3.45 while 3.44 doesn't cause this issue. The problematic file should be `beamerbasesection.sty`.

Error:
```
! Package beamerfontthememetropolis Error: Patching section title failed.
```

Minimal non-working example:
```
\documentclass{beamer}
\usetheme{metropolis}
\begin{document}
\end{document}
```

The error log is attached: [main.log](https://github.com/matze/mtheme/files/1523796/main.log)

**Comment by liubenyuan** [comment]
@josephwright 
Thanks! It solved my problem.
