### ISSUE TITLE
Errors with latest beamer version

### ISSUE THREAD

**Issue by alcarazr** [matze/mtheme#305]
Hi,
when compiling the following MWE:
```
\documentclass{beamer}
\usetheme{metropolis}           % Use metropolis theme
\title{A minimal example}
\date{\today}
\author{Matthias Vogelgesang}
\institute{Centre for Modern Beamer Themes}
\begin{document}
  \maketitle
  \section{First Section}
  \begin{frame}{First Frame}
    Hello, world!
  \end{frame}
\end{document}
```
I get the following errors:
```
ERROR   beamerfontthememetropolis.sty:275 — Package beamerfontthememetropolis Error: Patching section title failed.
ERROR   beamerfontthememetropolis.sty:291 — Package beamerfontthememetropolis Error: Patching section title failed.
```
I'm not entirely sure, but I'd say this is happening since the last `beamer` update (v3.45).

Thanks in advance,
Rodrigo

**Comment by josephwright** [comment]
Same as https://github.com/matze/mtheme/issues/303

**Comment by josephwright** [comment]
@alcarazr  I'll update `beamer` on CTAN later today to at least avoid giving an error (there was a 'safety' line that got removed by accident).

**Comment by alcarazr** [comment]
Thanks @josephwright. Really appreciate your work. Of course yours too @matze 😉.

**Comment by alcarazr** [comment]
> @alcarazr I'll update beamer on CTAN later today to at least avoid giving an error (there was a 'safety' line that got removed by accident).

I have not seen updates on CTAN. Did this happen? Thanks!

**Comment by josephwright** [comment]
@alcarazr  I got slightly distracted: it went last night.

**Comment by alcarazr** [comment]
Thanks @josephwright. Looking forward to it 😉.
