### ISSUE TITLE
hepparticles uses bold font in text

### ISSUE THREAD

**Issue by beojan** [matze/mtheme#306]
The hepparticles package allows you to typeset particle names and processes, and should automatically match the font and text style surrounding it. With metropolis, it uses a bold font when the surrounding text is not bolded.

**Comment by matze** [comment]
Do you have a minimum working example demonstrating the problem?

**Comment by beojan** [comment]
Here you go: 
[MWE.tar.gz](https://github.com/matze/mtheme/files/1889026/MWE.tar.gz)

**Comment by matze** [comment]
This is a problem with hepparticles' usage of math fonts which clashes with fontspec. You might have some luck with [this answer](https://tex.stackexchange.com/a/240657/16394).
