### ISSUE TITLE
Section page

### ISSUE THREAD

**Issue by e5k** [matze/mtheme#311]
Hi,

First thanks so much for this great theme. Second, this is more of a question than an issue, so apologies if this is misplaced.

Long story short, I am working on a presentation where I will present different research projects. I would like to break it in sections, where each section is a different research project, hence different co-authors. Ideally, I'd love to place the names of the co-authors below the progress bar of any section page. Is there an easy way to achieve that?

Thanks a lot!

S

**Comment by benjamin-weiss** [comment]
First of all: if you have a question or issue please provide a [MWE](https://tex.meta.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-example-what-is-that). It makes it a lot easier and less work for those who want to help you.

To answer your question (assuming I understood you correctly): you need to customize the `section page` beamer template. For my example I just removed the subsection title and replaced it with the newly defined `\coauthor`. But you can obviously customize the section page as you like.

```TeX
\documentclass{beamer}
\usetheme{metropolis}

\makeatother
\newcommand{\coauthor}{}
\setbeamertemplate{section page}{
  \centering
  \begin{minipage}{22em}
    \raggedright
    \usebeamercolor[fg]{section title}
    \usebeamerfont{section title}
    \insertsectionhead\\[-1ex]
    \usebeamertemplate*{progress bar in section page}
    \par
    \usebeamercolor[fg]{subsection title}%
    \usebeamerfont{subsection title}%
    \coauthor
  \end{minipage}
  \par
  \vspace{\baselineskip}
}
\makeatletter

\title{My Research Projects}
\date{\today}
\author{Sébastien Biass}
\institute{Centre for Modern Beamer Themes}
\begin{document}
\maketitle
\section{Introduction}
\begin{frame}{My Frametitle}
\end{frame}
\begin{frame}{My Frametitle}
\end{frame}
{ % it probably makes sense to group the renewcommand with the secion to limit the definition to the current section
\renewcommand{\coauthor}{Matthias Vogelgesang}
\section{My First Research Project}
}
\begin{frame}{My Frametitle}
\end{frame}
\begin{frame}{My Frametitle}
\end{frame}
\section{Intermission}
\begin{frame}{My Frametitle}
\end{frame}
\begin{frame}{My Frametitle}
\end{frame}
{
\renewcommand{\coauthor}{Benjamin Weiss}
\section{My Second Research Project}
}
\begin{frame}{My Frametitle}
\end{frame}
\begin{frame}{My Frametitle}
\end{frame}
\end{document}
```

**Comment by e5k** [comment]
Excellent, just what I needed, thanks. Sorry about the MWE!
