### ISSUE TITLE
Package AUR

### ISSUE THREAD

**Issue by ryukinix** [matze/mtheme#314]
I can create a package in AUR for this. There is some interesting from the community or from the owner about that? This should simplify handle dependency and installation from Arch Linux (or based distros) users.

BTW, I need to install a external dependency for proper working called [texlive-pgfopts].

[texlive-pgfopts]: https://aur.archlinux.org/packages/texlive-pgfopts/

**Comment by ArchangeGabriel** [comment]
The package existed before but was deleted because mtheme is already available in `texlive-latexextra`.

**Comment by ryukinix** [comment]
Thanks for pointing that, that knowledge  is not trivial.

**Comment by matze** [comment]
Hi @ryukinix we are only concerned that the theme is on CTAN. We like to see it elsewhere but that has to come from the communities themselves. And apparently your community already did it ;-)
