### ISSUE TITLE
high contrast theme

### ISSUE THREAD

**Issue by GarciaRios** [matze/mtheme#316]
I saw this push on v1.2 but it's not clear if it part of [background = high contrast(?)] or what? I read the updated documentation and is not there either

**Comment by matze** [comment]
It is used like any other color theme, i.e. add
```latex
\usecolortheme{metropolis-highcontrast}
```
to your preamble. I added a short note about that to the manual.

**Comment by GarciaRios** [comment]
thanks for adding it to the manual, I figure it would be something like that but  I was just doing: \usecolortheme{highcontrast}

which of course doesn't work
