### ISSUE TITLE
Another theme

### ISSUE THREAD

**Issue by azzamsa** [matze/mtheme#319]
Thank you for this awesome theme. I am sure thousand users like this theme a lot :)

I think you have great capability to mix color and font.
Hope there are other theme crafted by your hand :).

Thank you so much for this awesome theme.

**Comment by matze** [comment]
Thanks for the compliment. There are no other themes but it's pretty straightforward to customize things to get different but still clean looks. With a [few modifications](https://bloerg.net/2015/12/10/modern-beamer-theme-revisited.html) you can get this

![fonts](https://user-images.githubusercontent.com/115270/38796153-d648d9ae-415a-11e8-892c-b7712e2dd47d.png)

I also highly recommend the [owl color theme](https://github.com/rchurchley/beamercolortheme-owl) by Ross Churchley.

**Comment by azzamsa** [comment]
> I also highly recommend the owl color theme by Ross Churchley.
https://bloerg.net/2015/12/10/modern-beamer-theme-revisited.html

Wow. thank you for pointing out these links. Thanks lot.

Thank you for this awesome theme. :)
