### ISSUE TITLE
About FiraSans

### ISSUE THREAD

**Issue by azzamsa** [matze/mtheme#322]
According to this https://github.com/mozilla/Fira/issues/210 issue. 

> The good news is that the developer of this typeface carrois apostrophe studio is still expanding this typeface. This project has been moved to their GitHub page:
carrois/Fira

So I think it would be better if the link point in this readme also point to that repo.

And as mentioned in FiraSans Developer repo

> This will be the last version of Fira Sans. Development will continue with FiraGO. See FiraGO for plenty of new scripts (Arabic, Hebrew, Devanagari, Thai, Georgian) and manual TT hinting.

I don't know about [FiraGO](https://github.com/bBoxType/FiraGO). But I think it deserve a check out :)

**Comment by azzamsa** [comment]
![2018-04-20-04 04 24](https://user-images.githubusercontent.com/17734314/39018361-013a434e-4450-11e8-8e6f-b1bd99c74736.png)

**Comment by matze** [comment]
Thanks for that information!
