### ISSUE TITLE
Progress bar not working correctly with `\tikzexternalize`

### ISSUE THREAD

**Issue by gjkf** [matze/mtheme#328]
Externalizing Tikz pictures for faster compile time breaks the progress bar. Consider the following MWE

```
\documentclass[usenames,dvpinames,mathserif]{beamer}
\usepackage{tikz}
\tikzsetexternalprefix{figures/}
\tikzexternalize%
\usepackage{pgfplots}
\pgfplotsset{compat=1.14,cycle list=pgfplotsthemetol}

\title[Composizione Tipografica]{Storia della composizione tipografica di simboli matematici}
\subtitle{Da Monotype a \LaTeX}
\author{Davide Cossu}
\institute{Liceo Scientifico Giovanni Marinelli}
\date{A.S. 2018}
\subject{Composizione tipografica}
\keywords{tipografia,storia,composizione tipografica}

\usetheme[progressbar=head]{metropolis}

\begin{document}
\section{One}
\begin{frame}[c]{Ttitle1}
  Test
\end{frame}
\section{Two}
\begin{frame}[c]{Title2}
  Test 2
\end{frame}
\end{document}
```

This compiles fine but the progress bar will not be of the correct length, instead it will advance of a fixed distance, reaching 100% after many, many slides. Simply removing the `\tikzexternalize` command fixes it.

![image](https://user-images.githubusercontent.com/8215189/41193821-78b0e132-6c12-11e8-8ce0-ea0f42e7efa2.png)
![image](https://user-images.githubusercontent.com/8215189/41193823-8342d3a8-6c12-11e8-93a0-22fd2333b2cb.png)

You can see here the problem. Removing the command yields this:

![image](https://user-images.githubusercontent.com/8215189/41193831-9c27e7d2-6c12-11e8-9040-39f82adea94e.png)
![image](https://user-images.githubusercontent.com/8215189/41193836-a4411038-6c12-11e8-8748-394a89f1f392.png)

There must be some sort of incompatibility between externalization and the progress bar since other figures work just fine.

**Comment by jakobmoss** [comment]
Are you using the theme version shipped with TeXlive or the one from this GitHub repo? Because the externalization (issue #260 ) was fixed *after* the most recent release.
I had similar progress bar issues (however on the section pages). Using the newer packages from GitHub solved them for me.

**Comment by gjkf** [comment]
I  was using TeXLive's version, yes. I guess that solves it, thanks for the reference. Guess we can close this.
