### ISSUE TITLE
All-lowercase small caps titles ugly with brackets, apostrophes, numbers 

### ISSUE THREAD

**Issue by gmbrauer** [matze/mtheme#33]
All-lowercase small caps for titles look nice as long as they contain letters only.
It all starts looking very ugly, however, as soon as brackets, apostrophes, quotation marks, or numbers are added.
As noted before (https://github.com/benjamin-weiss/mtheme/commit/629c117f745069862d82838385639629a8b689d4), \textsc{\MakeLowercase{…}} should be replaced by \MakeUppercase{…} and the fontsize adjusted accordingly.
Using `Numbers=Lowercase` seems to solve this issue for numbers, but not for other punctuation characters. For possible solutions - which do not seem to work for Fira Sans, though - see also https://tex.stackexchange.com/questions/170293/parentheses-and-square-brackets-contextually-in-small-caps.

**Comment by matze** [comment]
Thanks for the feedback, I'll look into that soon. However, I think faking small caps using smaller upper case letters is a typographically wrong solution and will definitely look awkward.

**Comment by matze** [comment]
#58 fixed this issue in a quite elegant way.
