### ISSUE TITLE
usetitleprogressbar required?

### ISSUE THREAD

**Issue by G-Thomson** [matze/mtheme#34]
Hi. I really like this theme.

I found that I had to have the ```usetitleprogressbar``` has to be engaged for the section titles to work. However in the demo.tex file the option is not used despite section titles being included.

**Comment by matze** [comment]
Hmm, `usetitleprogressbar` is not required if you mean "section titles to work" that a frame is inserted whenever `\section` is used.

**Comment by G-Thomson** [comment]
Ah, I found that if I run xelatex twice without ```usetitleprogressbar``` a frame is inserted whenever ```\section``` is used. Is this normal? I have not used xelatex before.

Also I am getting ```Package pgfkeys Error: Choice '1.9' unknown in key ...``` errors everytime which might be related.

**Comment by matze** [comment]
> Ah, I found that if I run xelatex twice without usetitleprogressbar a frame is inserted whenever \section is used. Is this normal? I have not used xelatex before.

It's not specific to xelatex. To determine the length of the progressbar the theme must know how many frames are produced.

> Also I am getting Package pgfkeys Error: Choice '1.9' unknown in key ... errors everytime which might be related. 

This looks more like your pgfplots is a bit old. You could remove [this](https://github.com/matze/mtheme/blob/master/beamerthemem.sty#L314) line and check again.

**Comment by G-Thomson** [comment]
That did the trick. Thank you. 
What did that line do?

**Comment by matze** [comment]
It sets the pgfplots version that should be used. I don't use specific features but the labels in the diagrams are much closer by default with version 1.9. So that might look off for you. In any case, I will close this issue now, since your problems are resolved.
