### ISSUE TITLE
No subtitle support

### ISSUE THREAD

**Issue by mmcdermott** [matze/mtheme#340]
This theme is great, but it doesn't naively support \framesubtitle. I think adding this:
```
  {
    \ifx\insertframesubtitle\@empty%
      {}
    \else {
      \hfill\ \linebreak
      {\small \insertframesubtitle}%
    }%
    \fi
  }%
```
here: https://github.com/matze/mtheme/blob/master/source/beamerouterthememetropolis.dtx#L173 would work. Or, at least, that's what I added on overleaf to get it to work. But, I've never worked with beamer themes before, so that may be a bad idea for reasons I don't understand.

**Comment by matze** [comment]
It's a feature not a bug, see #135 for more information.
