### ISSUE TITLE
Supported range / Fallback setup with XeLaTeX?

### ISSUE THREAD

**Issue by cpitclaudel** [matze/mtheme#377]
Thanks for your work on this font!

Is there a list somewhere of all supported glyphs?  I'd like to use this font in a Beamer presentation, but since it's missing some symbols I need a fallback; it would be convenient to define the fallback font as the default and then use `\setmathfont{Fira Math}[range=…]`.

(Two of the glyphs I'm missing are ∃ and ∀)

**Comment by ArchangeGabriel** [comment]
I think you want to open that in https://github.com/firamath/firamath/ instead. ;)

**Comment by cpitclaudel** [comment]
How did that happen?! Yes, of course.

**Comment by cpitclaudel** [comment]
(And sorry for the noise)
