### ISSUE TITLE
Tikz node color changes to black after \color{}

### ISSUE THREAD

**Issue by Pastells** [matze/mtheme#380]
This seems to be a tikz issue, but I encountered it using the metropolis theme, so it might be helpful to someone else.
When unsing a Color inside a tikz node, as well as the alert command from metropolis, the color changes to black afterwards. It can be easily changed back to the default as I show below.
Feel free to mark it as solved if you feel no action should be done from your side.

```tex
\documentclass{beamer}
\usetheme{metropolis}
\usepackage{tikz}

\begin{document}

\begin{frame}
\begin{tikzpicture}
    \node (a) {$ 1 + \alert{1} = 2$};
    \node (b) [below of=a] {$ 1 + {\color{blue}1} = 2$};
    \node (c) [text=mDarkTeal, below of=b] {$ 1 + \alert{1} = 2$};
\end{tikzpicture}
\end{frame}

\end{document}
```

**Comment by hmenke** [comment]
This issue (https://github.com/pgf-tikz/pgf/issues/361) was fixed in https://github.com/pgf-tikz/pgf/commit/7ee3a2ca3f0964beb939b1a3cdc34a7210bbd5cb which is part of PGF 3.1.5 (released 2019).
