### ISSUE TITLE
make clean should remove _minted-demo/

### ISSUE THREAD

**Issue by ghostofkendo** [matze/mtheme#40]
Hi,

The `clean` target in the Makefile should remove the directory `_minted-demo`, with `git clean -d` for example.
Not deleting this directory between builds can cause puzzling issue such as:

    ! Undefined control sequence.
    <argument>     \PYGtrac 
                            {k}{\PYGtracZbs {}documentclass}\PYGtrac {n+nb}{\PYG...
    l.2 ...acZob{}}beamer\PYGtrac{n+nb}{\PYGtracZcb{}}"

while Pygments (and pygmentize) were correctly installed.
This issue was caused by the minted files generated during a previous attempt at build the demo before I installed pygmentize.
It took me a moment before realising this, and I guess you know how unpleasant it is to debug strange error with LaTeX :-).

**Comment by matze** [comment]
Seems to be dependening on the minted version. I don't see this directory.

**Comment by ghostofkendo** [comment]
I have minted v2.0, as provided by texlive-latexextra 2014.36706 in Arch Linux.
