### ISSUE TITLE
Progress bar in footer?

### ISSUE THREAD

**Issue by foreachthing** [matze/mtheme#46]
How can I put the progress bar in the footer, without inserting the section head?
Thanks!

(sorry, if such questions don't belong here - didn't know where to go/put)

**Comment by matze** [comment]
Hmm, good question. I haven't tried that yet but do you think that makes sense? Where would that bar be located? Right on the bottom of the frame?

**Comment by foreachthing** [comment]
Yeah ... something like that (see file attached).
![beamer_progress_footer](https://cloud.githubusercontent.com/assets/10420187/7500490/52e82e4c-f42e-11e4-8d9e-e9e1c3e04d41.PNG)
Weather it makes sense or not ... I'd like to know how much longer I have to sit through the presentation! :-)

**Comment by benjamin-weiss** [comment]
Have you seen the `usetitleprogressbar` option of the theme? If I understand you right, this is exactly what you want. With the only difference that the progress bar is right under the frame title instead of in the footer. And from a design point of view this even makes more sense (in my opinion).

**Comment by matze** [comment]
@foreachthing: do you still see a valid reason for having the progressbar on the bottom rather than on the title bar?

**Comment by rchurchley** [comment]
I ran into one possible use case last week, when I gave a diagram-heavy talk that looked best with no frame titles at all. (The progress bar is never displayed when the frame title is empty.)

It could be valid in such cases to want a progress bar somewhere outside the frame title template. From a design point of view, I'd prefer it to be snug (no margins) against the top or bottom of the slide. This should probably wait until we have key-value options, though, so we can use memorable options like

```
[progressbar=none/title/top/bottom]
```

**Comment by foreachthing** [comment]
Matze: A VALID reason? No, I guess not. I just like it better - is that a reason ;-)
It's like with a program that's doing a long job: I'd like to know every percent of progress, not just 20%, 40%, 100% done.

I like rchurchley's idea! Margin-less top or bottom.

**Comment by matze** [comment]
Alright, then let's wait until #90 is merged and we can start thinking of an implementation.
