### ISSUE TITLE
Make it easier to use different colors?

### ISSUE THREAD

**Issue by eddelbuettel** [matze/mtheme#55]
Teal and orange is a lovely default, and as someone in front of solarized etc editor scheme I quite like.

*But* a very common standard is blue in various shades.  By a quick look at the [paletton.com](http://paletton.com) site you reference I found a pretty nice default for the header background I like better -- so I override it via `\definecolor{mDarkTeal}{HTML}{....}` in a header.   Is there way to pass this in via style options?

As I mentioned, I work from (R)markdown via beamer so the obvious quick edit to the top of the tex file is not a given (though we leave an `\include{}` open for a header which is what I use).  

What do other people use, or is default colours for everyone?

**Comment by benjamin-weiss** [comment]
I would probably write my own color theme and just import it via:

    \usetheme{m}
    \usecolortheme{myColorTheme}

I don't know if that makes it any easier for you using markdown, as I don't use it.

**Comment by eddelbuettel** [comment]
Right.  I needed / wanted one more change (cf #53) so I wrote a local copy of `m` as `m2`.  I later realized that for just the color aspect, a local copy of the "metropolis" color scheme would have done.

Things are fine with markdown.  The only small snag I hit was that in order to process Markdown from R, you go via the this [texfile template in the rmarkdown package](https://github.com/rstudio/rmarkdown/blob/master/inst/rmd/beamer/default.tex) also defines part, section, subsection so I still end up needing a file to be included.  Small price to pay...

**Comment by matze** [comment]
> So in sum we can probably close this.

Alright!
