### ISSUE TITLE
Graphics for sections

### ISSUE THREAD

**Issue by oars** [matze/mtheme#65]
No idea how feasible this is, but ￼being able to include a graphic for sections in a similar way to how the title screen does it would be great.

Awesome job on this theme.

**Comment by rchurchley** [comment]
Do you want the section slides to all have the same graphic as the title slide, or did you want to have a different graphic on each section slide?

**Comment by benjamin-weiss** [comment]
And where do you think the graphic should be positioned? Above or below the section title? Either way, design-wise I think an additional graphic will look probably a bit out of place on the section page. Maybe you can make a quick sketch?

**Comment by matze** [comment]
@oars: do you have additional information that addresses the concerns?

**Comment by matze** [comment]
Please re-open if this is still an issue for you.
