### ISSUE TITLE
Distribution of the theme via CTAN

### ISSUE THREAD

**Issue by benjamin-weiss** [matze/mtheme#68]
The manual installation of the theme is annoying and maybe difficult for beginners. For example I have to install the theme on every PC and for every user separately. So I think it would help a lot to distribute the theme as a package via [CTAN](http://ctan.org). It would also reach more users, as a lot of the TeX community is probably not active on GitHub. Also this would make other ways of distribution like the .deb package obsolete. We would have only one way of distribution left for everyone.

As far as I looked into it, this is what has to be done:

* Add dates to `\ProvidesPackage` commands
* Create a Makefile rule which creates the zip file to be uploaded to CTAN
* Create a documentation PDF
    - This is not mandatory, but very useful. If I want to get infos about a package I do not know I always use `texdoc {packagename}`.
    - The easiest way do do that is probably to adjust the README.md that pandoc creates a nicely formatted PDF.
* In this context it would be useful to rename the theme from `m` to something more self-explanatory like `modernbeamer`.
* Upload it to CTAN [here](http://ctan.org/upload/)

If I get it right the folder structure of the zip file should look like this in our case:

    mtheme.zip:
      mtheme/
        README   % to use as a changelog
        doc/
          mtheme.md   % renamed README.md
          mtheme.pdf  % using pandoc created documentation
        tex/
          beamercolorthememetropolis.sty
          beamerfontthememetropolis.sty
          beamerthemem.sty

Or for a very simple package without documentation just:

    mtheme.zip:
      mtheme/
        README.md
        beamercolorthememetropolis.sty
        beamerfontthememetropolis.sty
        beamerthemem.sty

Does anybody have experience with CTAN and can confirm my infos or can give some more insights?

**Comment by ChipmunkMath** [comment]
I agree that distributing the theme through CTAN is a good idea: it would increase access to a beautiful theme. However, how easy is it to update the theme if it's on CTAN? Will it slow down the ability to push out changes? Right now, it still seems like there's regular modifications. If distributing via CTAN will slow that process down, this should probably be put on hold for a couple of months, at least until the theme has stabilized further.

**Comment by matze** [comment]
> I agree that distributing the theme through CTAN is a good idea [...]

Indeed. I didn't upload to CTAN yet because I wasn't willing to spend much time on bringing everything up to their standards. But from what I can tell, it doesn't look horribly difficult.

> Will it slow down the ability to push out changes? Right now, it still seems like there's regular modifications. If distributing via CTAN will slow that process down, this should probably be put on hold for a couple of months, at least until the theme has stabilized further.

I don't think that's a big issue. From my perspective it would go on like with every other piece of software: continue development on GitHub as fast or slow as necessary and once in a while push a stable version to CTAN.

**Comment by benjamin-weiss** [comment]
> Create a documentation PDF ... The easiest way do do that is probably to adjust the README.md that pandoc creates a nicely formatted PDF.

After a bit of thinking I really do not like the easy `README.md` to PDF via pandoc way. So I decided to start a TeX file for the documentation. Maybe take a look at what I got so far and tell me what you think: https://github.com/benjamin-weiss/mtheme/tree/docs/docs

If we decide to use a PDF documentation we can obviously strip down the `README.md` to a bare minimum. So just include a short description, a screenshot, license information and redirect for more info to the proper PDF documentation.

**Comment by matze** [comment]
Very nice! Indeed, the README has gotten out-of-hand way too much anyway. A PR for integrating the docs is more than welcome.

**Comment by benjamin-weiss** [comment]
Ok. So I start a PR for the docs, that we have a place to discuss matters regarding the PDF documentation. But I would prefer to add some more things before we merge.

**Comment by rchurchley** [comment]
I haven't done this before, but it is probably worth looking into converting the theme to Documented LaTeX format to produce the README. Many (most?) CTAN packages are distributed this way. See https://www.tug.org/TUGboat/tb29-2/tb92pakin.pdf

**Comment by benjamin-weiss** [comment]
That sounds interesting. I will look into that.

**Comment by matze** [comment]
It's [there](http://ctan.org/pkg/beamertheme-metropolis), full distribution on all mirrors still takes a while though.
