### ISSUE TITLE
Handling plot "themes"

### ISSUE THREAD

**Issue by matze** [matze/mtheme#69]
Right now the pgfplots theme is hardcoded into the Beamer theme itself. This is not good for various reasons. First of all, the color definitions might clash with a different color theme (once #64 is merged this will be much more of an issue). And even worse: pgfplots might not be available.

Ideally we would have a command to load a pgfplot theme just like `\usecolortheme`, i.e. something like `\usepgfplottheme`. In the best case pgfplots would provide that, but I don't know about such thing.
This command could also take care to not issue `pgfplotset` in case pgfplots is not available.

**Comment by rchurchley** [comment]
I've had my eye on this too :+1: 

Even if `\usepgfplottheme` doesn't exist, we can still bundle off the pgfplots code into a little sub-package and include it with `\RequirePackage`. We can then call the package only when `pgfplots` is available, much like we currently `\usefonttheme` only under XeLaTeX or LuaLaTeX. [This answer](http://tex.stackexchange.com/questions/15306/conditional-if-a-package-is-available) appears to show how to do that.

**Comment by benjamin-weiss** [comment]
From #88:
> Right now the pgfplot theme is tied to a particular color. Ideally we would have a pgf color theme, which could actually come from the color theme itself in order to provide consistency, and a structural theme, i.e. all those axes, legend and grid customizations.

I think it would be sufficient to define the set of colors in the `plotcyclelist`. Axes, legend, grid and so on seems to be working just fine already.

![screenshot_dark_plot](https://cloud.githubusercontent.com/assets/9158719/8201852/0ad75ae8-14d5-11e5-9912-981df519b3d9.png)
  
Screenshot created using the following color adjustments:

    \definecolor{mBloodRed}{HTML}{FF0000}
    \definecolor{mYellowBastard}{HTML}{EAF02C}

    \setbeamercolor{normal text}{%
      fg=white,
      bg=black!90
    }

    \setbeamercolor{alerted text}{%
      fg=mBloodRed
    }

    \setbeamercolor{example text}{%
      fg=mYellowBastard
    }

**Comment by rchurchley** [comment]
> Axes, legend, grid and so on seems to be working just fine already.

Which version of the theme are you working under? I briefly broke the behaviour of `mbarplot` on my branch, so if you have that checked out you may be seeing the default `beamer` colour-choosing behaviour. Perhaps this is a sign to drop the Tol colours from the theme altogether?

**Comment by benjamin-weiss** [comment]
That was the current Master with your first patch in #88 applied. As I was focusing on the axis, and grid color I didn't recognize that it was broken.

So, what I wanted to show is that with respect to the axis, grid and legend colors it is already dependent on the beamer color `normal text`. So here is a new Screenshot (without broken `mbarplot` behavior):

![screenshot_dark_plot](https://cloud.githubusercontent.com/assets/9158719/8202270/bec09f30-14d8-11e5-81a0-066b34941cfa.png)

**Comment by benjamin-weiss** [comment]
I think after we split the pgfplotstheme into a separate file this is essentially solved and can be closed, right? Or are there still pending issues?

**Comment by matze** [comment]
> Or are there still pending issues?

Nope, absolutely right.
