### ISSUE TITLE
Version requirements

### ISSUE THREAD

**Issue by drahnr** [matze/mtheme#7]
Fedora 20 does ship `Fira {Sans,Mono}` as `Fira {Sans,Mono} OT` and also lacks the `ExtraLight` variant, causing xelatex to thrown upon.

0.3.x is the minimum I guess, at least I did not see the `ExtraLight` in the 0.2.x tarball. About the OT not sure if this is fedora specific or also a change between 0.2.x and 0.3.x

**Comment by Leonidas-from-XIV** [comment]
Wouldn't it be nice to have the font configurable? I mean, Fira Sans is pretty okay, but what if I'd like to have a different font?

**Comment by matze** [comment]
Hi, yes indeed it would be preferable and I will provide this if time allows (actually, half the work is done by splitting the font definition into its own style file). In any case, you can already override the font by using `\setsansfont` and friends after loading the package.

**Comment by ripatti** [comment]
I just wonder how to install the Fira fonts to other-than-linux machine to be used by mtheme. Running a beamer document with mtheme with xelatex stops when it does not find "Fira Sans Lig.cfg" file. The https://github.com/mozilla/Fira does not have this .cfg file.

**Comment by matze** [comment]
I cannot help you with that particular problem but will add any information to the README if you find a solution.
