### ISSUE TITLE
Block paddings and margins

### ISSUE THREAD

**Issue by benjamin-weiss** [matze/mtheme#76]
The block paddings and margin do not look particularly nice when using `blockbg` (as can be seen on the first screenshot). What you see on the second screenshot is the definition I used in the hsrmbeamertheme. If you agree I will integrate the code into the theme once we decided how we will further organize the development regarding the `dtx` implementation. Maybe we can optimize it even more. E.g. a little `vskip` before the block or take a deeper look on how to adjust the block paddings and margins in case `blockbg` is *not* activated.

**Old**

![screenshot_blocks_blockbg_old](https://cloud.githubusercontent.com/assets/9158719/8144342/4c0c91ca-11da-11e5-8524-a24055c412e9.png)

**New**

![screenshot_blocks_blockbg_new](https://cloud.githubusercontent.com/assets/9158719/8144345/55158dc6-11da-11e5-9f30-e93b81cc1d92.png)

**Comment by matze** [comment]
That would be a great change. Everytime I see this (I personally do not have `blockbg` enabled), I have a bad feeling. But AFAICT, the block title is still a bit on the lower side, right?

**Comment by benjamin-weiss** [comment]
> But AFAICT, the block title is still a bit on the lower side, right?

You are right. I will look into it.
