### ISSUE TITLE
Using Beamer's [t] option breaks section slides

### ISSUE THREAD

**Issue by bgat** [matze/mtheme#80]
I usually use Beamer's [t] option. When doing so with mtheme, it causes the text of the section header slides to also get pushed to the top of the slide, which looks strange (at least to me).  It seems they should always be centered.

I propose the following patch, which forces the section slides to always be centered:

    diff --git a/beamerthemem.dtx b/beamerthemem.dtx
    index ad5ad0d..85bf59c 100644
    --- a/beamerthemem.dtx
    +++ b/beamerthemem.dtx 
    @@ -412,7 +412,7 @@
         \ifbeamer@inframe
           \sectionpage
         \else
    -      \frame[plain]{\sectionpage}
    +      \frame[plain,c]{\sectionpage}
         \fi
       }
     \fi

**Comment by matze** [comment]
Do you want to open a PR or should I just add this myself?

**Comment by bgat** [comment]
Feel free to add it yourself. :-)

On Tue, Jun 16, 2015 at 9:37 AM Matthias Vogelgesang <
notifications@github.com> wrote:

> Do you want to open a PR or should I just add this myself?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/matze/mtheme/issues/80#issuecomment-112321997>.
>
-- 

Bill Gatliff
bgat@billgatliff.com
