### ISSUE TITLE
Remove unused files

### ISSUE THREAD

**Issue by rchurchley** [matze/mtheme#82]
I'm curious to see how many of the current files are unused and could be deleted.

- I assume `images/valley.jpg` was once used in the demo slides, but currently is not.
- If `make` is our supported build method, then `build.sh` and `latexmkrc` might be unnecessary.
- Do we need to complicate the project with `contributors.py`, `contributors.tex` and `login.json`? Personally, I think it's sufficient to acknowledge us contributors with a [link to the full list](https://github.com/matze/mtheme/graphs/contributors), which has the advantage of being automatically updated without the need for us to maintain a parallel list.
- We should investigate the `fira` bundle to see if it can be relied on to provide the fonts. If so, we will be able to remove `contrib/Dockerfile` and `contrib/getFiraFont.sh`.

**Comment by matze** [comment]
> I assume images/valley.jpg was once used in the demo slides, but currently is not.

Yes, that's a leftover that was used to demonstrate the `\plain` command.

> build.sh and latexmkrc might be unnecessary.

I remember that `build.sh` was called in the Dockerfile. But apparently that's not the case anymore, so we can safely remove that. Concerning `latexmkrc`, yes we should remove that too and prominently advertise Make-based builds.

> We should investigate the fira bundle to see if it can be relied on to provide the fonts.

What is the `fira` bundle?

**Comment by benjamin-weiss** [comment]
> Do we need to complicate the project with `contributors.py`, `contributors.tex` and `login.json`?

Yeah it probably got a little out of hand. But I kind of like it to have the complete list inside the documentation. But your way is also ok with me.

> What is the `fira` bundle?

A fairly new package which provides the Fira Sans font face. See the discussion in #75.

**Comment by benjamin-weiss** [comment]
The contributors issue is resolved. It seems like we decided to keep the docker related files for now. So it's only left to remove the images folder and we can close this, right?

**Comment by matze** [comment]
And the `latexmkrc` but since there are no objections I will just remove both.
