### ISSUE TITLE
Use key-value options

### ISSUE THREAD

**Issue by rchurchley** [matze/mtheme#90]
The `pgfopts` package allows for options of the form `key=value`, which would let us reimplement the options list with much more memorable names. For example:

```
noslidenumbers & usetotalslideindicator
    -> numbering={none, count, fraction}

protectframetitle & \mthemetitleformat{} 
    -> frametitle={plain, protect, lowercase, uppercase}

darkcolors
    -> colors={light, dark}
```

**Comment by matze** [comment]
:+1: on all accounts.

**Comment by rchurchley** [comment]
I made an ill-advised attempt to implement this during pull request #93, which should have addressed #89 only. It's now been decided to deal with that issue properly in a future separate pull request, so discussion should revert back to here.

It turns out `pgfkeys` is very powerful but programming it can be a bit overwhelming. Hopefully, we can set up a bit of helper code so the interface for adding new options and changing old ones is as simple as possible. @benjamin-weiss suggested that this could (or should) be done through custom `pgfkeys` handlers. With the right definitions of `.choose between` and `.compare`, it should theoretically be possible to have something like this:
```latex
\usepackage{beamerthememetropolisfunctions} % contains helper code
\pgfkeys{
  /metropolis/.cd,
  numbering/.choose between={none, counter, fraction},
  numbering=counter, % set default value
}

\pgfkeys{/metropolis/numbering/.compare=counter} % returns "true"
\pgfkeys{/metropolis/numbering/.compare=fraction} % returns "false"

\pgfkeys{/metropolis/numbering=none} % change keys mid-document
\pgfkeys{/metropolis/numbering=banana} % ...but throws a warning for bad values
```

I've managed to construct [a working example](https://gist.github.com/rchurchley/9ce4389bb39cdb90015a) of helper code that implements this. Comments?

**Comment by benjamin-weiss** [comment]
Nice work on the handlers. It definitely seems to work. One minor remark: It should be an error and not only a warning in my opinion. By the way have you tested if your implementation is capable of setting multiple values at once?

Yet I'm still on the fence what implementation we should use. Yours definitely produces shorter option definitions. But what are we gonna do with the `section slide` like options? There we still would have to go back to an option definition like in my [Implementation 3](https://gist.github.com/benjamin-weiss/b11749b4af26f2e3aeac), right? So this would lead to two different kinds of option definitions. It would be nice to have one common style. 

The major downside of my third Implementation is the significantly longer option definition. Although usually when I program I focus not so much on how much code I have to write, but on how good is it to read.  And readability is defiantly given.

Another major question is: Do we want everything to be implemented using `if` conditions (handler implementation) or is it more sensible to use a macro based approach (my implementation 3).

@matze I'd love to hear your opinion on this matter.

**Comment by benjamin-weiss** [comment]
A thought regarding the long `if` statements: We can obviously shorten them with an additional macro to the form.

```TeX
\ifoption{/metropolis/numbering/}{counter}{True}{False}
```

**Comment by rchurchley** [comment]
> One minor remark: It should be an error and not only a warning in my opinion.

Sure, that's reasonable.

> By the way have you tested if your implementation is capable of setting multiple values at once?

My version of `\metropolissetoption` does not, but multiple options can of course be set at once with `\pgfkeys`. Except for the fact that I needed to replace a `\pgfkeyscurrentpath` with `\pgfkeyscurrentkey` to support multiple options, but I've [fixed that bug now](https://gist.github.com/rchurchley/9ce4389bb39cdb90015a)

> So this would lead to two different kinds of option definitions. It would be nice to have one common style.

I feel like we are talking about (at least) two truly distinct types of options:

- those used to switch between different appearances of a beamer template (e.g., `numbering`, `progressbar`, `sectionpage=none`, `frametitle=protect`)
- those invoking a predefined command having a global effect (e.g. your `parlength`, `color=dark`)

These are different enough behaviours that I don't think they necessarily have follow the same style. I think it's natural to implement the first type using `if` statements (using, as you suggest, a macro to shorten them). The second type is most natural using `pgfkeys`'s built-in `.if choice`, as in your Implementation 3.

If you like, I can spend some time tomorrow figuring out whether it's possible to implement `.choose between` as an `.is choice` so at least one syntax would be a subset of the other.

**Comment by benjamin-weiss** [comment]
> it's natural to implement the first type using if statements

That's where I tend to disagree. I feel like `if` statements should only be used in TeX if absolutely necessary. The main tool to organize things should be macros.

> My version of `\metropolissetoption` does not, but multiple options can of course be set at once with `\pgfkeys`. Except for the fact that I needed to replace a `\pgfkeyscurrentpath` with `\pgfkeyscurrentke`y to support multiple options, but I've fixed that bug now

Thought about it again and combined our approaches. A macro like this is probably the right way to set our options.

```TeX
\newcommand{\setmetropolisoption}[1]{\pgfkeys{/metropolis/.cd,#1}}
```

**Comment by rchurchley** [comment]
I now *think* it's possible to create custom handlers for the following syntax, which would be a little closer to unifying the two different types of options.

```latex
\usepackage{beamerthememetropolisfunctions} % contains helper code
\pgfkeys{
  /metropolis/.cd,
  numbering/.is choice,
  numbering/.values={none, counter, fraction},
  numbering=counter, % set default value
}

\pgfkeys{/metropolis/numbering/.compare=counter} % returns "true"
\pgfkeys{/metropolis/numbering/.compare=fraction} % returns "false"
```

**Comment by benjamin-weiss** [comment]
> I feel like we are talking about (at least) two truly distinct types of options.

You classify from a user perspective, right? I wouldn't do that. For the user every option should behave the same way. E.g. if you want to implement the `sectionpage` option with an `if` statement it is not possible to change the option mid-document. That shouldn't be the case.

So the better classification is imho the one I chose.

- Is there code to be executed every time the element is used?
- Is there code to be execute when the option is changed?

**Comment by rchurchley** [comment]
> I feel like if statements should only be used in TeX if absolutely necessary. The main tool to organize things should be macros.

I generally agree with the philosophy with regards to TeX, but at the same time I feel that manually managing a bunch of macros goes against the spirit of Beamer's template system.

> You classify from a user perspective, right?

I now realize that what I really wanted to ask was: "Should this option be a beamer template?" (You're right, my original classification had `sectionpage` in the wrong category). After checking the manual, I think my preferred solution is actually much closer to your implementation 3 than I thought:

```latex
% insert code like options
\defbeamertemplate{page number}{-}{none}
\defbeamertemplate{page number}{1}{counter}
\defbeamertemplate{page number}{1/9}{fraction}
 
\pgfkeys{
  /metropolis/.cd,
    numbering/.is choice,
    numbering/none/.code=\setbeamertemplate{page number}[none],
    numbering/counter/.code=\setbeamertemplate{page number}[counter],
    numbering/fraction/.code=\setbeamertemplate{page number}[fraction],
    numbering=counter, % set default value
}
```

**Comment by benjamin-weiss** [comment]
> Should this option be a beamer template?

It definitely should be! I That is the way to go.

I think we should maybe make some changes with respect to the style. E.g. combine all the default settings in one `\pgfkey{•}` call at the end. And maybe change the path directly to the key.

```TeX
\pgfkeys{
  /metropolis/numbering/.cd,
    .is choice,
    none/.code=\setbeamertemplate{page number}[none],
    counter/.code=\setbeamertemplate{page number}[counter],
    fraction/.code=\setbeamertemplate{page number}[fraction],
}
```

**Comment by benjamin-weiss** [comment]
@rchurchley Just that you know. I started with the implementation of `pgfopts`. (https://github.com/benjamin-weiss/mtheme/tree/pgfkeys-based-options)

A little bit annoying is, that we have to place the options code after all beamertemplates are set up for it to work. It would be nice to have the options code at the top of each document. Any idea?

And FYI, you accidentally switch the position of the `\defbeamertemplate` arguments. Confused me a little bit. So your example should be:

```TeX
% insert code like options
\defbeamertemplate{page number}{none}{-}
\defbeamertemplate{page number}{counter}{1}
\defbeamertemplate{page number}{fraction}{1/9}
```

**Comment by rchurchley** [comment]
> Just that you know. I started with the implementation of `pgfopts`.

Sounds good! I'll let you lead the way on this one.

> I think we should maybe make some changes with respect to the style. E.g. combine all the default settings in one \pgfkey{•} call at the end. And maybe change the path directly to the key.

Sounds fine to me.

Incidentally, we may need to consider namespacing or otherwise making sure the options in each sub-package remain distinct. Under the current proposal, if `beamercolorthememetropolis` and `beamerinnerthememetropolis` both provide a `block=fill` option, then only one of them will work (the second sub-package called will overwrite `/metropolis/block/fill/.code`).

> A little bit annoying is, that we have to place the options code after all beamertemplates are set up for it to work. It would be nice to have the options code at the top of each document.

That is annoying. Do the `\defbeamertemplate`s have to come before all the options code or just before `\ProcessPgfOptions`? It may be possible to define the options first, then set up all the beamer templates, then `\ProcessPgfOptions` at the very end of the package. It'd still be a bit weird, but it would at least be an improvement.

> And FYI, you accidentally switch the position of the \defbeamertemplate arguments. Confused me a little bit.

Sorry about that — it was 3am here and I wanted to quickly make the suggestion before I went to bed! :)

**Comment by benjamin-weiss** [comment]
> Incidentally, we may need to consider namespacing or otherwise making sure the options in each sub-package remain distinct.

Haven't thought about that. Accidentally I'm right at this point. I have to think about that.

> Do the \defbeamertemplates have to come before all the options code or just before `\ProcessPgfOptions`?

They have to come before `\ProcessPgfOptions` and before we set the default values.

**Comment by rchurchley** [comment]
> They have to come before `\ProcessPgfOptions` and before we set the default values. 

Right, I forgot that setting defaults will try to execute `\setbeamertemplate` at the top of the file as well.

I don't have a great solution yet, but here are a couple brainstormed options:

- put all option code at the *bottom* of the file instead of the top. It would be weird, but at least it would work.
- put `\ProcessPgfOptions` at the bottom of the file and remove the defaults from `\pgfkeys`. We could effectively set the defaults by adding `\setbeamertemplate`s at the appropriate points in the code. This wouldn't be ideal, but it would still be an improvement over the current situation.

Does this spark any ideas?

**Comment by benjamin-weiss** [comment]
> put all option code at the bottom of the file instead of the top. It would be weird, but at least it would work.

That's what I'm doing right now.

> We could effectively set the defaults by adding `\setbeamertemplates` at the appropriate points in the code.

I think this would be too confusing.

What about combining all the defaults into a macro which calls `\pgfkeys`. Then put a call of this macro and `\ProcessPgfOptions` at the bottom of the file. Like this:

```TeX
\pgfkeys{
  /metropolis/inner/block/.cd,
    .is choice,
    transparent/.code=\setlength{\@metropolis@blockskip}{0ex},
    fill/.code=\setlength{\@metropolis@blockskip}{1ex},
}
\pgfkeys{
  /metropolis/inner/sectionpage/.cd,
    .is choice,
    none/.code=\@metropolis@sectionpage@none,
    progressbar/.code=\@metropolis@sectionpage@progressbar,
}
\newcommand{\@metropolis@inner@setdefaults}{
  \pgfkeys{/metropolis/inner/.cd,
    sectionpage=progressbar,
    block=fill,
  }
}

% Code setting up all the templates.

\@metropolis@inner@setdefaults
\ProcessPgfOptions
```

**Comment by rchurchley** [comment]
> What about combining all the defaults into a macro which calls `\pgfkeys`. Then put a call of this macro and `\ProcessPgfOptions` at the bottom of the file.

That makes the most sense to me!

**Comment by benjamin-weiss** [comment]
Ok, then I will implement it that way.

Do you by any chance have still your backwards compatibility code lying around?

And an off topic question: Do you have any idea why there is a macro called `\mreducelistspacing` in `beamerthemem`? It is not used anywhere as far as I can tell.

**Comment by benjamin-weiss** [comment]
> Do you by any chance have still your backwards compatibility code lying around?

Nevermind, found it.

**Comment by benjamin-weiss** [comment]
There is another annoyance. We can easily forward all the options to the sub-packages via the `.search also` handler. But this does not work for options that affect multiple sub-packages

**Comment by rchurchley** [comment]
> And an off topic question: Do you have any idea why there is a macro called \mreducelistspacing in beamerthemem? It is not used anywhere as far as I can tell.

I have no idea. I don't think it's used anywhere either. It might have been intended as a feature for the user, but if so I think it might be a little out-of-place in a theme.

**Comment by benjamin-weiss** [comment]
I just did a `git blame` on the file. And it seems like @matze added that macro. So, @matze is the macro still of any use or can we delete it?

**Comment by matze** [comment]
Yes, you can remove that. I had a spacing issue with normal text vs. itemize environments inside a block.

**Comment by matze** [comment]
Since that macro is actually independent of this issue, I'll close this since key-value-support is in now.
