### ISSUE TITLE
Minor design improvements for the title page

### ISSUE THREAD

**Issue by benjamin-weiss** [matze/mtheme#95]
Even if the title page looks well designed on its own, it feels a little bit too light in comparison to the other slides. First of all it is the only place we use the `ExtraLight` font (for the author and the date) and the dividing line is a little bit thinner than the progress bar.

So I think we should change the author and date font to `Light`, change the institute font to `ExtraLight` and use the same thickness for the divider and the progress bar.

![screenshot_titlepage](https://cloud.githubusercontent.com/assets/9158719/8244614/4246f14c-1623-11e5-81e0-be471f9f5797.png)

If you guys agree I will make a PR.

**Comment by matze** [comment]
*Going to see the difference …* yes, go for it. By the way, maybe we could include a fake logo or use one of the symbols on slide 21 to represent something like an institutional logo. I guess it's not too uncommon to have some such on the very first slide.

**Comment by ChipmunkMath** [comment]
As someone who needs a logo on their title page, I would love to see some sort of easy image inclusion.

**Comment by benjamin-weiss** [comment]
I don't really like the idea of a "random" logo. But an official mtheme logo would be nice. Wanna design one? Sadly my design skills would produce a logo unworthy of the theme. :smile:

> I would love to see some sort of easy image inclusion.

That is already possible. See #30. Maybe we should mention that in the documentation.

**Comment by matze** [comment]
Well, considering that the theme's (still?) inofficial name is Metropolis, we could use the logo from the iconic movie

![Metropolis logo](https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Metropolis1927-logo.svg/200px-Metropolis1927-logo.svg.png)

but that might be a bit too extreme. I'll try to come up with something.

**Comment by benjamin-weiss** [comment]
Hehe. Interesting idea. But this logo basically screams *noise* and not so much *minimal visual noise*. So it is not really fitting I think.

**Comment by bgat** [comment]
Related, at some professional conferences the logo appears on the lower
right of the title page, and as a banner in the footers of body pages. I'm
not against hacking the template myself to accomplish this, but haven't
been able to do so thus far without wrecking the whole thing. Is there a
structural improvement that would make this easier?

Second, I prefer to include a "title page" at the end of the document,
which is just like the first page but adds the copyright/redistribution
terms for the material in small print near the bottom of the frame. Can you
consider adding a \license{} variable, and then e.g. a parameter to
\maketitle that will show that variable's contents if requested?

Finally, please add my vote FOR ease of logo addition on the title page,
and AGAINST that particular... logo. :-)

On Fri, Jun 19, 2015, 8:47 AM Benjamin Weiss <notifications@github.com>
wrote:

> Hehe. Interesting idea. But this logo basically screams *noise* and not
> so much *minimal visual noise*. So it is not really fitting I think.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/matze/mtheme/issues/95#issuecomment-113396198>.
>
-- 

Bill Gatliff
bgat@billgatliff.com

**Comment by matze** [comment]
> Finally, please add my vote [...] AGAINST that particular... logo. :-)

Alright, alright. Here's a draft of a logo that resembles what some university logos look like. It incorporates dark teal and Fira Sans and uses the Metropolis skyline (sans name) to give it more edge. Needs some polishing though:

![metropolis](https://cloud.githubusercontent.com/assets/115270/8250046/6c991400-1670-11e5-8eef-be75d982b528.png)

**Comment by bgat** [comment]
OK, that's a candidate I might be able to get behind. :-)

Would be especially cool if it was provided in several formats, including
EPS, JPG, SVG, and PNG, so that stupid users like me could test/confirm
that my setup works for all of them. But, that's probably asking too much...

On Fri, Jun 19, 2015, 10:47 AM Matthias Vogelgesang <
notifications@github.com> wrote:

> Finally, please add my vote [...] AGAINST that particular... logo. :-)
>
> Alright, alright. Here's a draft of a logo that resembles what some
> university logos look like. It incorporates dark teal and Fira Sans and
> uses the Metropolis skyline (sans name) to give it more edge. Needs some
> polishing though:
>
> [image: metropolis]
> <https://cloud.githubusercontent.com/assets/115270/8250046/6c991400-1670-11e5-8eef-be75d982b528.png>
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/matze/mtheme/issues/95#issuecomment-113435554>.
>
-- 

Bill Gatliff
bgat@billgatliff.com

**Comment by bgat** [comment]
Ohh! Ohh!!

Since it "needs polishing", maybe add a "beamer" of light that shines an
mtheme logo on the clouds, Batman-style? :-P

On Fri, Jun 19, 2015, 10:52 AM Bill Gatliff <bgat@billgatliff.com> wrote:

> OK, that's a candidate I might be able to get behind. :-)
>
> Would be especially cool if it was provided in several formats, including
> EPS, JPG, SVG, and PNG, so that stupid users like me could test/confirm
> that my setup works for all of them. But, that's probably asking too much...
>
> On Fri, Jun 19, 2015, 10:47 AM Matthias Vogelgesang <
> notifications@github.com> wrote:
>
>> Finally, please add my vote [...] AGAINST that particular... logo. :-)
>>
>> Alright, alright. Here's a draft of a logo that resembles what some
>> university logos look like. It incorporates dark teal and Fira Sans and
>> uses the Metropolis skyline (sans name) to give it more edge. Needs some
>> polishing though:
>>
>> [image: metropolis]
>> <https://cloud.githubusercontent.com/assets/115270/8250046/6c991400-1670-11e5-8eef-be75d982b528.png>
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/matze/mtheme/issues/95#issuecomment-113435554>.
>>
> --
>
> Bill Gatliff
> bgat@billgatliff.com
>
-- 

Bill Gatliff
bgat@billgatliff.com

**Comment by benjamin-weiss** [comment]
> Related, at some professional conferences the logo appears on the lower right of the title page

Interesting point. I think we should look at that again when #90 is implemented. Then we could make a option like

    titlegraphic={top, top left, top right ...}

> Can you consider adding a `\license{}` variable, and then e.g. a parameter to `\maketitle` that will show that variable's contents if requested?

Shouldn't be that much work. Disabling would be just setting license empty, just like with the subtitle right now.

> Here's a draft of a logo that resembles what some university logos look like.

I like it!

**Comment by bgat** [comment]
Note that it would be "disabled" on the first slide, but "enabled" on the
last one. So it's not quite the same as the subtitle.

On Fri, Jun 19, 2015, 10:56 AM Benjamin Weiss <notifications@github.com>
wrote:

> Related, at some professional conferences the logo appears on the lower
> right of the title page
>
> Interesting point. I think we should look at that again when #90
> <https://github.com/matze/mtheme/issues/90> is implemented. Then we could
> make a option like
>
> titlegraphic={top, top left, top right ...}
>
>  Can you consider adding a \license{} variable, and then e.g. a parameter
> to \maketitle that will show that variable's contents if requested?
>
> Shouldn't be that much work. Disabling would be just setting license
> empty, just like with the subtitle right now.
>
> Here's a draft of a logo that resembles what some university logos look
> like.
>
> I like it!
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/matze/mtheme/issues/95#issuecomment-113437733>.
>
-- 

Bill Gatliff
bgat@billgatliff.com

**Comment by benjamin-weiss** [comment]
In a sense it is. You just would have to set `\license` after you called `\maketitle` the first time.

Another thing: Could you please not attach the whole Email on every post. This makes the discussion quite awful to read here on the GitHub page. Thank you!

**Comment by benjamin-weiss** [comment]
I think the best way to support title graphics on the top and on the bottom is to have two `beamertemplates`. One for the top and one for the bottom.
```TeX
\defbeamertemplate{titlegraphic top}{none}{}
\defbeamertemplate{titlegraphic top}{left}{•}
\defbeamertemplate{titlegraphic top}{center}{•}
\defbeamertemplate{titlegraphic top}{right}{•}

\defbeamertemplate{titlegraphic bottom}{none}{}
\defbeamertemplate{titlegraphic bottom}{left}{•}
\defbeamertemplate{titlegraphic bottom}{center}{•}
\defbeamertemplate{titlegraphic bottom}{right}{•}
```
Using `pgfkeys` we set them according to the option given by the user and in `\setbeamertemplate{title page}{•}` we check with `\ifbeamertemplateempty{•}{•}{•}` if we have to insert the top or bottom template.

Agreed? Then I will start implementing it.

**Comment by matze** [comment]
Sounds like a reasonable approach.

**Comment by benjamin-weiss** [comment]
Thought about it a bit more. My previous approach would limit the system to one graphic on the title page. Do we want the user to be able to place graphics on each position independently? Then we have to think of sth. else.

**Comment by matze** [comment]
For full customization, the user can always use TikZ overlays and arrange images freely. So, in my opinion the current approach – which solves like 80% of the use cases – is good enough.

**Comment by dcherian** [comment]
Has the positioning for `titlegraphic` (e.g. bottom right) been implemented yet? If so, how do I use it?

**Comment by rchurchley** [comment]
@dcherian: I believe we decided not to implement `titlegraphic` positioning. You can easily position an image in the top left or top right yourself:

```latex
\titlegraphic{\includegraphics{logo.pdf}}         % top left
\titlegraphic{\hfill\includegraphics{logo.pdf}}   % top right
```

For logos in the bottom, we recommend using TikZ overlays. For example, you might try:
```latex
\titlegraphic{
    \tikz[overlay,remember picture]
        \node[at=(current page.south east), anchor=south east] {
            \includegraphics[height=1.5cm]{logo.pdf}
        };
}
```
