### ISSUE TITLE
Set up a wiki page with coding style guideline and implement it

### ISSUE THREAD

**Issue by benjamin-weiss** [matze/mtheme#97]
Although the coding style is overall quite decent already, I think it is reasonable to set up a small wiki page. Helps to keep us all on the same page.

**Comment by matze** [comment]
I am not opposed to a Wiki but for coding style guidelines a CONTRIBUTING.md file is the way to go on GitHub. We can link to it and whenever someone wants to open a PR there will be a big notice to review the content of this file.

**Comment by benjamin-weiss** [comment]
Never heard nor seen a `CONTRIBUTING.md` file on GitHub before. But you are right. That seems be the GitHub way of doing a style guide. So we should do a `CONTRIBUTING.md` instead of a wiki page.
