### ISSUE TITLE
Fix vertical alignment of frame title in all cases

### ISSUE THREAD

**Issue by benjamin-weiss** [matze/mtheme#99]
As the following animation shows the vertical alignment is quite decent for our default small caps lowercase. But when using any other formatting the alignment is way off.

![screenshot_title](https://cloud.githubusercontent.com/assets/9158719/8302951/9df99588-199a-11e5-96b1-b053b89dc974.gif)

**Comment by tmgriffiths** [comment]
See Fix #115

**Comment by rchurchley** [comment]
Great work, @tmgriffiths!
